### ISSUE TITLE
make use of the official package and package base lists

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#290]
With the AUR 3.5.0 release, the package list and package base list are now official and available for download. See the [release announcement](https://lists.archlinux.org/pipermail/aur-dev/2014-November/002968.html).

Investigate and see if these lists might be used in some useful way in pacaur.

**Comment by rmarquis** [comment]
Don't see any real use of that capability. Maybe later... closing for now.

**Comment by rmarquis** [comment]
Here's an example: https://github.com/worzel666/aurtab
The list could be used to improve tab completion response time, by caching the AUR packages list locally.

**Comment by AladW** [comment]
It can be useful to do regex matches on, and send the result to the RPC (most likely `info`). That said, you need [some logic](https://github.com/AladW/aurutils/blob/master/aursearch#L13) to keep the list updated, or fetch it on every search (for a 200kb file).

**Comment by rmarquis** [comment]
Thanks, but pacaur uses cower for search, so regex capabilities are already implemented. Truly, I only believe this could be useful to speed up tab completion.

**Comment by AladW** [comment]
cower's regex abilities are fairly unreliable though (using the first two non-regex characters, then filter the result for the actual pattern), though I guess this should be fixed on the cower end.

That said, as far as I understand `aurtab`, it fetches the package list on every completion. So unless you add said update check, I doubt this would be faster than the existing cower completion.

**Comment by rmarquis** [comment]
The 2 characters limit is due to AUR. Cower implementation is not perfect but works relatively well, and I have no complaint so far for simple regex patterns. Also, the RPC allows request to be made on name, name and description or even maintainer while regex can only be done on pkgname or pkgbase with the provided AUR lists.

As for completion, cower allows online completion for AUR packages, and the AUR only command set of pacaur makes use of it. It is however disabled for AUR when using "pacman style" tab completion due to its slowness. This is where this file could be handy.

**Comment by rmarquis** [comment]
This is actually not faster than relying on cower directly. The bottleneck here seems to be the sheer number of AUR packages rather than the network connection.

I'll enabling completion with `-S` by default.
