### ISSUE TITLE
Cannot connect to AUR as unprivileged user

### ISSUE THREAD

**Issue by furbyhater** [rmarquis/pacaur#295]
I have become unable to connect to the AUR using pacaur as a normal user. If I use sudo, it fails at the makepkg step. If I use cower, everything works (checking for updates and downloading the package).

This is the output of bash -x pacaur -S flite as an example (not very informative): http://pastebin.com/UAU3SsTr

I don't have any pacaur.conf file either in ~/.config or in /etc

EDIT: Here's the output of using curl as an unprivileged user (same command as in the bash log): http://pastebin.com/Ly48RSTD

EDIT2: Files inside /tmp/pacaur-username with root-ownership were causing the problem. Fixed! Closing the issue.

**Comment by rmarquis** [comment]
The fix in dfc918a8a9e01be8dfd54dc25f5c8de578f47f73 should prevent this situation to occur again.
