### ISSUE TITLE
Clean option should be disabled when -m flag is enabled

### ISSUE THREAD

**Issue by crossroads1112** [rmarquis/pacaur#299]
Leaving the clean option enabled causes the built packages to be "cleaned" (read: deleted) immediately which defeats the whole purpose of the flag.

Instead, the script should check if the clean option is enabled. If it isn't, proceed as usual. If it is, disable it, do the build, then re enable.

To reproduce: Turn on the clean option and run pacaur -Smw dropbox
Check in $builddir and nothing will be there except files ignoretemp and rpc.json
Turn off clean option
pacaur -Smw dropbox
$builddir/dropbox/dropbox-3.0.4-1-x86_64.pkg.tar.xz exists
-w is needed because of #297

**Comment by rmarquis** [comment]
Fixed in 2284b3cf6c8d77da6253e2ff011ea5064671684a.
