### ISSUE TITLE
-Syuw exits with code 1 even though packages are successfully built

### ISSUE THREAD

**Issue by crossroads1112** [rmarquis/pacaur#301]
Title says it all. I tried to use pacaur -Syuw and even though packages were successfully built, the exit code was nonzero

pacaur version 4.2.17

**Comment by rmarquis** [comment]
Fixed in 59532b4ed2110699963e4b2955014336f3ad2de2.

**Comment by rmarquis** [comment]
Code has been cleaned up and reverted in f89bf850ef2910dd13f62eddd74062d10ef3fa84. Not sure what was the original issue here, but I cannot reproduce.
