### ISSUE TITLE
Setting "makeopts" not available anymore?

### ISSUE THREAD

**Issue by willemw12** [rmarquis/pacaur#304]
Is the "makeopts" setting not available anymore?

On archlinuxarm, in /etc/xdg/pacaur/config:

    makeopts+=("--ignorearch")             # pass command line options to makepkg

I could install any AUR package. Now I get:

    $ pacaur -S  wcalc
    ...
    :: Checking wcalc integrity...
    ==> ERROR: wcalc is not available for the 'arm' architecture.
        Note that many packages may need a line added to their PKGBUILD
        such as arch=('arm').

(Also the error message from makepkg about adding "arch=('arm')" does not seem a good suggestion to me.)

**Comment by rmarquis** [comment]
Should be fixed in 7e486cdc1e8faa1f21fee1bea7030bdf4ce25d45. Install pacaur-git and try again.

**Comment by willemw12** [comment]
Yes, it is fixed now.
