### ISSUE TITLE
aurvote support

### ISSUE THREAD

**Issue by Edenhofer** [rmarquis/pacaur#308]
Maybe one could add aurvote (https://aur.archlinux.org/packages/aurvote/) support as an optional dependency.

**Comment by rmarquis** [comment]
I thought about this in the past, and no, this won't be implemented.
It simply doesn't make sense: you usually don't vote for a package at install time, but after you actually used it and found it useful. The standalone "aurvote" or aurtomatic (python3-aur) packages are just what you need.

**Comment by Edenhofer** [comment]
Sure that makes sense...
My phylosophy is that I install a package and alwas vote for it, removing my vote only if it does not work as expected. But I am totally fine with going the other way around.
