### ISSUE TITLE
Save AUR packages

### ISSUE THREAD

**Issue by oshazard** [rmarquis/pacaur#309]
The successfully built and packaged **.pkg.tar.xz** file(s) should optionally be saved by `pacaur` to a cache directory. This would act in a similar way to *pacman*'s cache location *(/var/cache/pacman/pkg*).

**Benefits:**
* Avoid a potentially long recompile
* Reduce network bandwidth
* Share with other machines on network

**Requirements:**
* Save package(s) to local non-tmpfs directory
* Check for cached *AUR* packages on install (allow `--needed` here)
* For *VCS* packages determine if cached version newer than exists in *AUR*
* Allow skipping cached packages (allow `--rebuild` here)

**Comment by rmarquis** [comment]
Please read the man pages, including `man makepkg`.
