### ISSUE TITLE
Error when installing something that uses a makedepends in prepare

### ISSUE THREAD

**Issue by aereaux** [rmarquis/pacaur#317]
I get an error when installing and updating blueman from the AUR:

    ==> Starting prepare()...
    ./autogen.sh: line 26: intltoolize: command not found
    ==> ERROR: A failure occurred in prepare().

One of the makedepends is intltool, and it is used in the prepare function, but pacaur does not install makedepends until after it executes prepare.

**Comment by rmarquis** [comment]
Hi,

Could tell me which is the failing AUR package?

**Comment by aereaux** [comment]
[blueman](https://aur.archlinux.org/packages/blueman/)

**Comment by rmarquis** [comment]
Thanks. This is kinda related to #313. I'm not sure yet what will be the best way to handle this issue.

**Comment by rmarquis** [comment]
Should be fixed in 87a0371f0a8b5b862e053e52302d4a9280e4826d.
