### ISSUE TITLE
Strange locale issue

### ISSUE THREAD

**Issue by Weishaupt** [rmarquis/pacaur#322]
I use de_DE locale. (`env` tells me `LANG=de_DE.UTF-8`)
When I use pacman, it is fully localized into German. Pacaur is not, and this is where it gets strange. When I do:

    $ pacaur -S pacaur
    :: Package(s) pacaur not found in repositories, trying AUR...
    :: resolving dependencies...
    :: looking for inter-conflicts...
    :: pacaur-4.2.22-1 is up to date -- reinstalling
    
    AUR Packages  (1): pacaur-4.2.22-1  
    
    :: Proceed with installation? [Y/n] y
    $

Pacaur aborts instead of continuing with the installation. When I instead press the localized `j` (German: "Ja" means "Yes") then the installation continues.

**Comment by rmarquis** [comment]
Thanks for the report. This is likely a regression introduced in this 17ce8c8d5dac36f8778442089858e158c061f956, and I have pushed a possible fix in 361f5ee23cd7de48196ccb9b198bb8bbf959939c. Could you install pacaur-git and check if the issue still exists?

**Comment by Weishaupt** [comment]
Hey, this seems to fix the issue.
