### ISSUE TITLE
Print installed version in -Ss if it differs from the repository version

### ISSUE THREAD

**Issue by willemw12** [rmarquis/pacaur#323]
Feature request: print the installed version of a package in -Ss if it differs from repository version. For example:

    $ pacaur -Ss pacaur
    aur/pacaur 4.2.23-1 (279) [installed]

This can be misleading if the installed version is not 4.2.23-1. Expected in that case:

    $ pacaur -Ss pacaur
    aur/pacaur 4.2.23-1 (279) [installed: 4.2.19-3]

**Comment by rmarquis** [comment]
The search feature is entirely provided through [cower](https://github.com/falconindy/cower). Please redirect your request there.
