### ISSUE TITLE
add internationalization support for -Si/-i

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#329]
Pacaur currently calls `cower -i` directly for info about AUR packages, thus not allowing any string translation.

Check if this can be done with cower's `--format` flag, or move the info code entirely on the pacaur side.

**Comment by rmarquis** [comment]
I'll likely never do that by myself. Calling to community contributors.

**Comment by ChuckDaniels87** [comment]
It looks to me as an upstream issue. I think it is easier to fix in cower.

**Comment by rmarquis** [comment]
True, but cower doesn't support internationalization and will likely never do.

**Comment by ChuckDaniels87** [comment]
I've done a little script to show you an idea:
```bash
#!/bin/bash
readarray cower_info < <(cower -i pacaur --format "%n\n%v\n%D")
echo -ne "Name \t\t : ${cower_info[0]}"
echo -ne "Version \t : ${cower_info[1]}"
echo -ne "Depends On \t : ${cower_info[2]}"
```

We store the output of `cower` in a BASH array. Then, we print that array mimicking the output format of pacman. This should generate the locale files to be translated in `pacaur`.

If you like it, I can try to implement this in `pacaur`.

**Comment by rmarquis** [comment]
Yes please! 👍

**Comment by ChuckDaniels87** [comment]
I only see one problem with this: if you want to get the info of several packages you got to call cower once for each package. However, we could fix that with a more elaborated filter.

I'll work a bit on this on a fork. :+1:

**Comment by rmarquis** [comment]
Hmm, that's unfortunate. Cower actually allows to call all packages at once... Is there no way to make it work in a similar way?

**Comment by ChuckDaniels87** [comment]
I'm sure we can figure it out. I'm thinking right now on a table or an array of arrays purely written in bash.

**Comment by ChuckDaniels87** [comment]
I think I got it:

```bash
#!/bin/bash

# Get all info: each package is in a different line 
# and its info is separated by commas.
readarray cower_array < <(cower -i pacaur cower --format "%n,%v,%D\n")

# Extract the rows, then create a new array changing 
# commas to linebreaks and print the info.
for rows in "${cower_array[@]}"
do
    readarray cower_info < <(echo $rows | tr ',' '\n')
    echo -ne "Name \t\t : ${cower_info[0]}"
    echo -ne "Version \t : ${cower_info[1]}"
    echo -ne "Depends On \t : ${cower_info[2]}"
    echo -ne "\n"
done

```

**Comment by rmarquis** [comment]
Good, I'll have a closer look tomorrow.

**Comment by ChuckDaniels87** [comment]
I've coded a first implementation of this idea, you can check/test it in [this fork of pacaur](https://github.com/ChuckDaniels87/pacaur).


There are still several problems to really fit the actual print formatting of `pacman`:
* Indentation is broken with long strings (larger than the terminal width).
* Optional Deps appears as only _one line_.
* _Installed_ flag in the package name is missing.
* Info indentation is fixed using printf, this can cause troubles when translating the strings since the width may vary. I've seen you got a function called `GetLength()`. I think it could be useful to fix this problem.

**Comment by ChuckDaniels87** [comment]
I've changed the code to a more complex and elaborated solution. 

The only issue that is still present is the missing [Installed] flag in the package name. I think at least a call to pacman is needed to determine if the package is installed.

**Comment by rmarquis** [comment]
This can be done with expac, maybe even with a single call.

**Comment by ChuckDaniels87** [comment]
I've just noticed that `pacman -Si` does not use any [Installed] flag in the name. That flag only appears in `cower -Si`. Should we stick to `pacman` format?

**Comment by rmarquis** [comment]
A different info order is fine, but please stick to cower content and colors.

**Comment by rmarquis** [comment]
Done in 1cd27405e762ac42ca473282a3c8b45824759d91.
