### ISSUE TITLE
--check should be aware of --devel

### ISSUE THREAD

**Issue by crossroads1112** [rmarquis/pacaur#332]
I've written a script that relies on pacaur and it involves getting a list of what pacaur intends to update. It does this by storing the output of `pacaur --check` however development packages don't show up in the output. I can understand why they would not by default but when running `pacaur --check --devel` i would expect development packages to be included as well.

**Comment by rmarquis** [comment]
Yes, there's room for improvement here. As --check is basically the same as --update (but without update), it makes sense to make the --devel works here too.

**Comment by rmarquis** [comment]
Done in 6e8de4c80f429ca2873b5d2e86b364aa428fddb0.
