### ISSUE TITLE
-cc doesn't seem to work

### ISSUE THREAD

**Issue by crossroads1112** [rmarquis/pacaur#333]
A picture is worth 1000 words right? [Here](http://i.imgur.com/z6SBaGA.png) is my problem in a nutshell. Basically, I run pacaur -cc but my build directory is still full and unchanged.

**Comment by rmarquis** [comment]
I can reproduce.Will have a look shortly.

**Comment by rmarquis** [comment]
Fixed in 4413f6febffa178e4fd1eca9e9b361695cb2c13a. This was introduced in 17ce8c8d5dac36f8778442089858e158c061f956 in scope of issue #315.
