### ISSUE TITLE
Ignorerepo not working

### ISSUE THREAD

**Issue by ishitatsuyuki** [rmarquis/pacaur#334]
pacaur --ignorerepo=repo-ck -d linux-ck
:: linux-ck is available in repo-ck (ignore this with --ignorerepo=repo-ck)
Tried arranging parameter, but it doesn't work.
Searched code but nothing matches ignorerepo.
Is it stub?

**Comment by rmarquis** [comment]
Thanks, the ignorerepo flat Isn't supported by pacaur. You might want to
use cower directly here .

**Comment by rmarquis** [comment]
Implemented in eb104995dd4118f4270d5b8a7b33e96ccc85cb87.
