### ISSUE TITLE
A more easy way to install pacaur?

### ISSUE THREAD

**Issue by gutenye** [rmarquis/pacaur#335]
I've followed, https://wiki.archlinux.org/index.php/Pacaur#Installation, it works, but require a lot of steps.

I suggest that upload {cower,pacaur}.pkg.tar.xz and {bower,pacaur}.pkg.tar.xz.sig to a server, then install it with one command:
```
# pacman -U http://server/cower.pkg.tar.xz http://server/pacaur.pkg.tar.xz
```

For those who are interested, I've setup my personal use at https://github.com/gutenye/archive, it does contain any signatures though.

**Comment by rmarquis** [comment]
Hi Guten Ye,

I understand your point of view and appreciate that you have interest in making the installation easier. However, I'm actually very against this idea. AUR helpers shouldn't encourage users not to learn the manual process with makepkg, as this brings more problems than it solves issues for new users. Yaourt does it wrong and it imho hurts the community by doing so.

I'd appreciate if you don't make prebuilt package available publicly. I'd also suggest you to look into aur.sh if you want to ease the installation.

**Comment by gutenye** [comment]
OK, Thanks for the clarification, I want to help the Arch Linux coummunity, too. And for power users like myself, I'll keep it as my personal use and I've update the issue.
