### ISSUE TITLE
AUR 4 support

### ISSUE THREAD

**Issue by crossroads1112** [rmarquis/pacaur#336]
See title. Some excellent features could be implemented with the new git integration

**Comment by rmarquis** [comment]
Please expand on wanted features. I'm only aware of the feature described
in #231 which might be possible to implement.

**Comment by rmarquis** [comment]
The RPC interface currently doesn't work with AUR 4. Waiting for a fix before uploading the pkgbuilds.

**Comment by rmarquis** [comment]
Compatibility has been added in AUR4 and the git repositories uploaded (pacaur & pacaur-git).
