### ISSUE TITLE
download using git

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#343]
As AURv4.0.0 is using git repositories, it is now possible to use git for download instead of relaying on cower fetching ability.

```
To clone first time:

$ cd <build directory>
$ git clone <package url>
$ cd <package name>
$ makepkg -sfi

Then:

$cd <package name>
$ makepkg -c
$ git pull
$ makepkg -sfi
```

This would be a requirement for implementing #231.

Pro:
* don't rely on the backward compatible, but not recommended URLPath RPC field
* might be a first step to provide pacaur independently of cower. 

Con:
* add a dependency on git

**Comment by rmarquis** [comment]
Seems [some cower patches](https://github.com/kyrias/cower/commits/git) are ready to replace the old curl download ability with a git-based feature. Let's work on that instead of reinventing the wheel here.

**Comment by HLFH** [comment]
Hi. Any news on this git-based feature with pacaur? Thanks.

**Comment by rmarquis** [comment]
Not really. Cower didn't move to git as of yet, and I'm not sure if it will ever do. A few patches from @kyrias have been written, but the work isn't complete yet. I played a bit with these path in my own cower fork, but didn't do any significant progress (and quite frankly I don't really want to maintain these in cower codebase, as I've heard on IRC that falconindy isn't interested in doing so).

This said, the only real advantage to move to a git based approach for pacaur is displaying PKGBUILD diff (see #231). So I'm a bit on the fence here: either do it the hard but clean way and integrate git support in cower, or do it in bash and handle the download part in pacaur directly, without using cower.

@kyrias: any news from your side?

**Comment by kyrias** [comment]
Not really. I'm planning on implementing it in cower SomeTime™, but haven't really been in a mood to bother the last few weeks. Though if I do end up implementing it, I might start over from another AUR RPC codebase that falconindy started on, which would be basically a rewrite of cower.

Anyway, while the snapshots are sort of a legacy feature, they should continue being supported for the foreseeable future so there's not much of a hurry.

**Comment by rmarquis** [comment]
@kyrias That's interesting. Any pointer to that other AUR RPC codebase? I've never heard about it. I actually can think of many improvements cower could make use of. For example, it still does not use the multiinfo RPC response but threaded info response, has some issues with versioned dependencies and afaik it isn't exactly easy to use to retrieve dependencies chain in the right order, especially with split packages (there has been a partial patch written or that, but that was never completed). Let me know if I could be of any help.

@HLFH Since PKGBUILDs diff is something I'd like to include soon, I guess I'll have to hack git support outside of cower for the time being.

**Comment by HLFH** [comment]
@rmarquis Cool :) Thank you so much. You rock.

**Comment by kyrias** [comment]
@rmarquis It's not published anywhere right now I'm afraid, but you could ask him if he wants to send it to you. And there'll always be issues with versioned deps in AUR packages really, since they aren't built  yet so the pkgver doesn't mean much yet.

**Comment by rmarquis** [comment]
@kyrias I'm actually referring to https://github.com/falconindy/cower/issues/91 which concerns versioned provides/conflicts in the binary repositories. But this is an edge case that isn't really common. 

As for the "new" cower source, well, if it isn't public then I don't see a real reason to hack that code. We'd eventually end up with 3 incompatible codebase. But let me know if/when you start this cower rewrite. I'd gladly help the best I could.
