### ISSUE TITLE
--domain breaks build directory

### ISSUE THREAD

**Issue by jpkotta** [rmarquis/pacaur#348]
I'm using pacaur 4.2.27.14.gf7f2567.

Somehow --domain prevents the internal variable $builddir from being set.

```
$ pacaur --domain aur4.archlinux.org -S debootstrap
:: Package(s) debootstrap not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1): debootstrap-1.0.71-1  

:: Proceed with installation? [Y/n] 

:: Retrieving package(s)...
[sudo] password for jpkotta: 
/usr/bin/pacaur: line 727: cd: /tmp/pacaurtmp-jpkotta/debootstrap: No such file or directory
:: Checking debootstrap integrity...
==> ERROR: PKGBUILD does not exist.
:: failed to verify debootstrap integrity
```

Indeed, the directory /tmp/pacaurtmp-jpkotta/debootstrap doesn't exist (I have clean=false, BTW).  I inserted a `echo "builddir = $(pwd)"` at line 728, just after it cds to the $builddir, and it printed the $PWD, not the expected build directory.

I also did a `pacaur -cc` and it cleaned the $PWD (fortunately nothing valuable was in there).  I'm not sure if this is the same problem because --domain was not given.

**Comment by rmarquis** [comment]
Are you actually using cower-git?

**Comment by jpkotta** [comment]
No.

**Comment by rmarquis** [comment]
See note in the [Arch wiki](https://wiki.archlinux.org/index.php/Pacaur).

**Comment by jpkotta** [comment]
If pacaur-git breaks with cower, shouldn't it depend on cower-git?

**Comment by rmarquis** [comment]
At this right moment, yes, but frankly I don't care. If you're courageous enough to use pacaur-git, I expect you to know about expac-git and cower-git.

Pacaur-git is only for people that really know what they are doing. If you don't want any breakage, use the stable version.
