### ISSUE TITLE
Allow checking for updated devel packages with --check and --devel

### ISSUE THREAD

**Issue by aereaux** [rmarquis/pacaur#352]
It would definitely be cool if pacaur could support checking for updates to devel packages with some set of options, maybe --check and --devel.  This would be especially easy and quick when the clean option is set to false for devel packages, as all that would be needed is to check to see if the repository needs updating.

**Comment by rmarquis** [comment]
Do you mean actually downloading all --devel sources and updating pkgver()? This is actually never done before displaying the prompt because it is a slow operation, and eventually not that important when you do your regular update with ``--devel``.

**Comment by aereaux** [comment]
Yes, that is exactly what I mean.  I agree that it is not that important, but it would be kind of nice to have.  Also, it is not extremely slow when cleandevel is set to false.

**Comment by rmarquis** [comment]
True, it might be worth it if cleandevel is set to false. I'll have a look shortly.

**Comment by benutzer193** [comment]
I don't know if I should open a new issue for this, as it could be a solution or addition to this issue:

Could you add an option that, if you use --devel and a package is already up-to-date, skips that package? So you can update git packages, even if pkgver() hasn't changed, without updating already up-to-date packages.
If there is already an option to do that, please tell me and ignore my request ;).

**Comment by aereaux** [comment]
@benutzer193: The --needed option, used along with the --devel option should do what you want.

**Comment by rmarquis** [comment]
@benutzer193 Yes, ```--needed``` is what you are looking for.

**Comment by benutzer193** [comment]
@aereaux  @rmarquis  thank you very much!

**Comment by DoctorJellyface** [comment]
@aereaux @rmarquis I second that, wonderful feature, thanks!

**Comment by rmarquis** [comment]
Also need to fix the output alignment:

**Comment by rmarquis** [comment]
Done is ce7cf4f58ae36fc6886340b66aee2e73312a2871. As this is unsurprisingly slow, the `--needed` flag is required, otherwise the standard behavior is used.
