### ISSUE TITLE
Store built AUR packages in pacman's cache

### ISSUE THREAD

**Issue by djmattyg007** [rmarquis/pacaur#353]
I'm starting to use containers with systemd-nspawn, and am bootstrapping the container OSes with `pacstrap`. This command lets you use the package cache of the host if packages are available there, rather than re-downloading them for each guest (which is obviously desirable).

There are quite a few AUR packages I would like to install inside my containers as well, but unfortunately at the moment AUR packages built using pacaur are never stored into pacman's cache. I did some reading and discovered that if you use a `file://` URI, pacman will automatically store the package in its cache. See this: https://wiki.archlinux.org/index.php/Pacman#Additional_commands

I dug through the pacaur source, and believe packages are installed automatically with makepkg's `-i` flag, which gives no opportunity for using a `file://` URI, and therefore no chance of having these packages stored into the cache. Would it be possible to add a configuration option for pacaur to have it use `file://` URIs, so that built packages can be stored into pacman's cache?

**Comment by rmarquis** [comment]
No, ```makepkg -i``` is used for better compatibility when installing split packages (and also less duplicate code too).

Have you had a look at the ```$PKGDEST``` makepkg variable instead?

**Comment by djmattyg007** [comment]
I had not previously. I have now, and it suits my needs just fine. Thank you very much!

**Comment by rmarquis** [comment]
You're welcome.
