### ISSUE TITLE
pacaur clears terminal, unresponsive, near fakeroot

### ISSUE THREAD

**Issue by slester** [rmarquis/pacaur#354]
I've been trying to install neovim-git with pacaur, and inevitably when it gets to fake root (or some step nearby), it quickly flashes to a blank terminal (no history, can't ctrl+c/z/d). This doesn't happen when makepkging normally.

**Comment by rmarquis** [comment]
Sounds similar to issue #325. Might be an upstream issue triggered by pacaur.

**Comment by rmarquis** [comment]
This has now been fixed in #197.

**Comment by rmarquis** [comment]
Issue #197 has been reopened. The "fix" actually has unwanted side effects.
Instead, you might want to report the issue to neovim and tell them to fix there tag generation properly. This a similar (or the very same) issue as #325.
