### ISSUE TITLE
Installation of python-related packages fails with '/usr/bin/makepkg: line 110: GREEN: unbound variable'

### ISSUE THREAD

**Issue by slowbro** [rmarquis/pacaur#357]
This has happened to me with the following packages:

python-botocore
python-colorama
aws-cli

Pacaur fails the installation with:

```
running install_scripts
/usr/bin/makepkg: line 110: GREEN: unbound variable
:: python-botocore cleaning skipped
:: failed to build python-botocore package(s)
```

Full log linked near the end of this report. I have verified that the packages build just fine with `makepkg -s` and `makepkg -si`. This is happening with both *pacaur* abd *pacaur-git* packages.

When running pacaur, no colors are being displayed on the console (versus when running `makepkg -si`) - leading me to believe this may be a color stripping issue of some sort?

Full log: http://www.slowbro.org/python-botocore-pacaur.txt
Debug (bash -x) log: http://www.slowbro.org/python-botocore-debug.txt

Additional information about my system:

```
[katelyn@sanic ~]$ uname -a                                                                                            
Linux sanic 4.1.5-1-ARCH #1 SMP PREEMPT Tue Aug 11 15:41:14 CEST 2015 x86_64 GNU/Linux
[katelyn@sanic ~]$ pacman -Qs pacaur
local/pacaur-git 4.2.27.42.gada2dec-1
    A fast workflow AUR helper using cower as backend
```

**Comment by slowbro** [comment]
Looking into this more.. because I can't help myself. Looks like this may actually be a bug with makepkg or this package specifically. Running `makepkg -sfi --nocolor --noconfirm` (similar to what pacaur runs) results in the same error:

/usr/bin/makepkg: line 110: GREEN: unbound variable

**Comment by slowbro** [comment]
Yep, I think this is an issue with these packages - sorry! Looks like in package() it runs `set -u`, which forces bash to error when `--nocolor` is used because `$GREEN` is not set. If that makes sense and you agree, I will report this bug to these package maintainers.

**Comment by rmarquis** [comment]
Yes, ```set -u``` in a PKGBUILD is a terrible idea.
