### ISSUE TITLE
"no results found for [package]"

### ISSUE THREAD

**Issue by Binero** [rmarquis/pacaur#358]
When running pacaur, I often run into a lot of errors saying a specific package isn't found. Here is an example output: 

```
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Starting AUR upgrade...
:: resolving dependencies...
:: no results found for [megasync]:
:: no results found for [minecraft]:
:: no results found for [nautilus-megasync]:
:: no results found for [pacaur]:
:: no results found for [paper-gtk-theme-git]:
```

I find this odd, because when doing `pacaur -Sa megasync` it *can* actually find it. It does not do this for all AUR packages either. I for instance have android-studio and the Oracle JDK installed but it doesn't complain about not being able to find those.

**Comment by rmarquis** [comment]
This is usually due a misconfigured DNS server. Cower threads run too fast and can't connect.
See the wiki page for troubleshooting.

**Comment by mmrezaie** [comment]
Nope, the only thing happened for me was it just resolved faster but I still get the error messages! I did changed the DNS settings too. my primary DNS server is 8.8.8.8.

**Comment by rmarquis** [comment]
Do you use pacaur-git? Does this issue happen with cower (try ```cower -u```)? If yes, you can alternatively try to decrease number of threads of cower.

**Comment by rmarquis** [comment]
No response, closing now.

**Comment by Rufflewind** [comment]
Ran into the same problem.  Did:

```sh
d=${XDG_CONFIG_HOME-$HOME/.config}/cower &&
mkdir -p "$d" &&
echo "MaxThreads = 1" >>"$d/config"
```

and now it works without error.
