### ISSUE TITLE
Error when sorting by popularity

### ISSUE THREAD

**Issue by protist** [rmarquis/pacaur#360]
With the new config defaulting to `sortby=popularity`, pacaur won't show AUR results anymore.

    $ pacaur -Ss qt5
    ...
    <Official repo hits>
    ....
    error: invalid argument to --rsort

Reverting the config to `sortby=votes` lists AUR hits as previously.

**Comment by rmarquis** [comment]
Works for me. Have you correctly merged your pacaur config file?

**Comment by protist** [comment]
Thanks, it works fine now. I merged the config fine, but cower-git wasn't updated. Do you know if the PKGBUILD can depend on specific minimum version of cower-git?

**Comment by rmarquis** [comment]
Probably, but it doesn't make real sense to constraint the version. If you're using -git packages, then you should ensure these are up-to-date.

**Comment by protist** [comment]
Yes, I suppose that makes sense. Otherwise, I suppose you'd have to constantly update the PKGBUILD, which doesn't make sense. (FWIW I only noticed because the PKGBUILD was updated in the first place.) Thanks for the quick reply.

**Comment by rmarquis** [comment]
Yes, exactly. The purpose of updating the PKGBUILD for the pacaur-git package is to ensure all people using it get the update (more guinea pigs for testing!). I'll iron this new version out before releasing it to the stable branch. I'll also wait for/ask for cower to have a new release before releasing.
