### ISSUE TITLE
pacaur doesn't find anything in aur

### ISSUE THREAD

**Issue by nogo** [rmarquis/pacaur#362]
pacaur -Ss packagename
error: invalid argument to --rsort

**Comment by rmarquis** [comment]
Please use another helper. Pacaur is for advanced users that know what they are doing.

**Comment by nogo** [comment]
I'm using pacaur quite a while and was happy with it. But this is no anwser to me.

**Comment by nogo** [comment]
@rmarquis I found the problem was a missmatch with the cower version. But it would really help to be nicer to your users.

**Comment by rmarquis** [comment]
Feel free to use pacaur if you've no basic understanding of basics of PKGBUILD and makepkg (yes, handling -git packages is 101), but don't dare asking me about it. I do not intent to be "nicer" to users that are not the intended target of this helper, and I won't provide support to them unless they pay me.
