### ISSUE TITLE
Heads up for --pkg

### ISSUE THREAD

**Issue by rumpelsepp** [rmarquis/pacaur#364]
Just read this on pacman-dev; I think it may be important for pacaur:
https://lists.archlinux.org/pipermail/pacman-dev/2015-September/020347.html

**Comment by rmarquis** [comment]
Thank you! Definitely a change that will require a complete rework... hopefully, I could just switch back to the old code that didn't take split package into account.

**Comment by rmarquis** [comment]
I might need to drop the ```-i``` flag of makepkg and implement the install part  with ```pacman -U``` instead. Afaik, there might be a few drawback due to arch overriding in PKGBUILD, but this would make easy to implement #197 and #338.

**Comment by rmarquis** [comment]
An alternative way to avoid the limitation of ```pacman -U``` could be to create a repository of built packages with ```repo-add```, install with regular ```pacman -S```, then (optionally) remove the created repository with ```repo-remove```. Both tools are provided by the pacman package.

**Comment by rmarquis** [comment]
Done in 6b2c1ed9726538434cfae0865c637579be430765 (using ```pacman -U```).
