### ISSUE TITLE
pacaur is broken on AUR web 4.1

### ISSUE THREAD

**Issue by rumpelsepp** [rmarquis/pacaur#366]
Since AUR web 4.1 pacaur seems to be broken:

```
$ pacaur -S atom-editor-bin
:: Package(s) atom-editor-bin not found in repositories, trying AUR...
:: resolving dependencies...
:: no results found for atom-editor-bin
```

Can you confirm this?

**Comment by rmarquis** [comment]
See https://bugs.archlinux.org/task/46547.

**Comment by rmarquis** [comment]
(reopening until the AUR is fixed - so other people won't open another issue)

**Comment by rumpelsepp** [comment]
Ah nice, thx for that pointer!

**Comment by rmarquis** [comment]
AUR 4.1.1 is now online, closing.
