### ISSUE TITLE
Entering y/n at a prompt doesn't behave like pacman

### ISSUE THREAD

**Issue by MachFour** [rmarquis/pacaur#371]
When pacaur displays a prompt like 'Proceed with installation? [Y/n]', pressing y or n shouldn't immediately confirm the prompt (i.e. you should have to press y <enter> to confirm) because this disagrees with the behaviour of the prompts in actual pacman. 

A related (and perhaps less subjective) problem is that if you accidentally press a key after entering a pacaur command, the extra keystroke won't be cleared by the time such a prompt comes up. Since it isn't necessary to press enter at the prompt to say yes or no, the accidental keystrokes can end up confiming or cancelling actions that the user didn't want to. 

The change would be to simply change the 'read -n 1 answer' lines in the Proceed() function to 'read answer' instead.

**Comment by rmarquis** [comment]
This exact, and actually done on purpose as this basically divide keystrokes by two, which is appreciable when reviewing quite a few PKGBUILDs. The rationale being "users know what they are doing" with ctrl-c being the safeguard.

The drawback is that this doesn't match pacman behavior (which is sad), but I'm not sure it is really worth matching it when the main purpose of pacaur is to provide a "fast workflow" with minimum user interaction.

I might consider changing it, but imho the drawbacks outweigh the benefits here.

**Comment by MachFour** [comment]
Yeah fair enough. I guess it's an easy enough change to make to a locally installed copy of the pacaur script for those who do prefer the consistent behaviour (and don't review many PKGBUILDs ;) )
