### ISSUE TITLE
When one package fails, any other installs

### ISSUE THREAD

**Issue by analca3** [rmarquis/pacaur#376]
Hi! Sorry for my English. I noticed that when a package install fails (downloads, pacman error, etc) all other packages that remains stop installation. Is this the desired behaviour? A bug, maybe? Maybe https://github.com/rmarquis/pacaur/issues/369 ?

Thank you :)

**Comment by rmarquis** [comment]
This is the expected behavior. Not related to #369.

**Comment by analca3** [comment]
Do you have a plan for editing it or do you want maintain this behaviour? Only for knowing :) !

**Comment by rmarquis** [comment]
No change of behavior planned. If there is an error, then the operation should stop.
