### ISSUE TITLE
error: invalid argument to --rsort

### ISSUE THREAD

**Issue by xkonni** [rmarquis/pacaur#377]
for like 2 weeks i'm getting this error:
```
~ $ pacaur -Ss pacaur
error: invalid argument to --rsort
```
while cower works as expected
```
~ $ cower -s pacaur
aur/archupdate 1-1 (0)
    A simple script to update archlinux using pacmatic and pacaur.
aur/pacaur 4.3.2-1 (352)
    A fast workflow AUR helper using cower as backend
aur/pacaur-git 4.3.2-1 (21) [installed: 4.3.2.14.ga59dc2e-1]
    A fast workflow AUR helper using cower as backend
```

Tried updating both to latest git versions, didnt change anything.
Any ideas would be appreciated, really like using pacaur ;)

**Comment by rmarquis** [comment]
What's your cower version?

**Comment by xkonni** [comment]
ok now i feel stupid. updated cower again and now it works. i'm sure i did this a few days ago.

thanks for your time ;)

**Comment by rmarquis** [comment]
;)

**Comment by jose1711** [comment]
i am on cower 12 and it does not recognize popularity as a key for (r)sort:
cower --rsort=popularity -i cower
error: invalid argument to --rsort

       --sort=KEY, --rsort=KEY
           Sort the results in ascending or descending order, respectively, by KEY where KEY is firstsubmitted, lastmodified, maintainer, name, outofdate, version or votes.

fixed by changing sortby to votes in /usr/bin/pacaur - maybe this should be the default?

**Comment by rmarquis** [comment]
Why don't you use the latest cower?

**Comment by jose1711** [comment]
warning: cower-2:12-2 is up to date -- reinstalling

**Comment by rmarquis** [comment]
$ pacaur -Ss cower
aur/cower 14-2 (563, 16.91) [installed]

Stop using third party repo if you're unable to manage them properly.

**Comment by jose1711** [comment]
ouch, sorry. i did not quite realize this came from an untrusted repo.. works now

**Comment by rmarquis** [comment]
Note you can use the VerbosePkgLists option in pacman.conf to display repositories when installing/updating packages. That option also extends the main prompt of pacaur for AUR packages.

**Comment by jose1711** [comment]
thanks for the tip!
