### ISSUE TITLE
Mention -Sy combinations in the Readme

### ISSUE THREAD

**Issue by Awebb** [rmarquis/pacaur#380]
If we point people to the readme, they cannot know whether -Sy combinations will actually do anything, because they are not explicitly mentioned. I had to read the source code to see, if it actually does anything.

**Comment by rmarquis** [comment]
Thank for your feedback. It is not listed as ```-Sy``` isn't modified in any way; it's behavior is strictly similar to pacman (as is -Sg, all remove, query, update and database operations).

This is in the current man page:
> Pacaur will also pass any pacman related options to the pacman binary.

Would changing this to the following would be good enough?
>  Pacaur will also pass any other pacman operation and their related options to the pacman binary.

**Comment by rmarquis** [comment]
Done in 9584dcde71cfb73df7d024e591c59241cddfe6a3.
