### ISSUE TITLE
Unresolvable conflicts on split packages

### ISSUE THREAD

**Issue by zoqaeski** [rmarquis/pacaur#389]
PKGBUILDs which make split packages (such as mozc) sometimes fail to install due to unresolvable conflicts. Installing with `makepkg -i` works fine. I'd provide the output, but for some odd reason this issue wouldn't occur a second or third time and the original was lost in my scrollback buffer.

**Comment by rmarquis** [comment]
No output means I am not able to fix that issue. This said, if the issue doesn't occur every time, this means an external factor is taken into account. I'm closing this ticket, please reopen if you get more info.
