### ISSUE TITLE
allow rebuilding all AUR dependencies of AUR packages

### ISSUE THREAD

**Issue by v01d** [rmarquis/pacaur#390]
It is very common that upgrades con officially maintained packages requires rebuilds of locally compiled packages, obtained from AUR. When this breakage occurs, it becomes quite troublesome to find which packages require a rebuild. This is specially complicated for ROS (all ros-indigo-* packages, for example). It would be nice to be able to request all AUR dependencies (recursively) for a given package be rebuilt.

**Comment by rmarquis** [comment]
Have you looked at the existing --foreign flag?

**Comment by v01d** [comment]
I've read about it in the man page but I don't understand what it does.

**Comment by rmarquis** [comment]
> When used with build, install and update operations, also consider already installed foreign dependencies.

When installing/updating AUR packages, the dependency solver won't ignore already installed AUR dependencies - and thus rebuild them even if they are already up-to-date.

**Comment by v01d** [comment]
Ah ok, thanks for the clarification. So it wont attempt to build non-AUR
from source, right? If so, it is exactly what I needed.

**Comment by rmarquis** [comment]
Yes.
