### ISSUE TITLE
Problem with epochs

### ISSUE THREAD

**Issue by DoctorJellyface** [rmarquis/pacaur#392]
Hey. Today I tried to install `lib32-sdl2_mixer`, which has `lib32-smpeg2` as a dependency.

`lib32-smpeg2` needs the 64-bit `smpeg2` to compile, but `smpeg2`, unlike `lib32-smpeg2` uses an epoch, so in the `lib32-smpeg2` PKGBUILD you'll find:
```
depends=("${pkgname#*-}=1:$pkgver")
```

However, upon trying to install `lib32-sdl2_mixer` I got an error, saying something along the lines of `smpeg=1 not found` (I lost the output when my terminal crashed for some reason, and I'm not willing to got through the installation again, I'm glad I got it installed), but it definitely wanted to find `smpeg` version 1.

I initially thought that it was the PKGBUILD's fault, but I tried manually building the package and and had no problems whatsoever.

**Comment by rmarquis** [comment]
Indeed, thanks for the report. Seems that is a regression when I did some cleanup in 2c28bec0af4b4ed3f52286d3d1f4d4acae7bdf1e. This is now fixed in 81afd122adfb3e6fbf1bc926ca7732bec0ca22bf. Available in pacaur-git.
