### ISSUE TITLE
Use "(n)vim -d" to show diff of PKGBUILDS and install scripts if available

### ISSUE THREAD

**Issue by benutzer193** [rmarquis/pacaur#394]
At the moment you are using *git show* to compare PKGBUILD and install script diffs, if I looked correctly in the pacaur script. Git is using a pager for git show, so it is not possible change anything in the diff.
My suggestion is to compare the old local PKGBUILD and install script to the new ones using *(n)vim -d*, if available on the system. This way also allows to copy changes you make regularly to specific PKGBUILDS or install scripts.

**Comment by rmarquis** [comment]
There is no old PKGBUILD stored on the system, only the git repo.
