### ISSUE TITLE
Visudo configuration

### ISSUE THREAD

**Issue by protist** [rmarquis/pacaur#395]
Is there a way to configure `visudo` so that I don't need to type my `sudo` password when I run `pacaur -Syu`? I tried a few combinations, such as the following.

    my_username ALL=(ALL) NOPASSWD: /usr/bin/updatedb,/usr/bin/pacman -Syu

This obviously works fine for `pacman -Syu`, but I still need to type the `sudo` password for `pacaur -Syu`. The only configuration that worked for me was to allow all of `/usr/bin/pacman`, but then this leaves a security hole (e.g. `/usr/bin/pacman -U` of arbitrary packages). Is there a way around this, or does `pacaur` require `-U` or similar?

**Comment by rmarquis** [comment]
Pacaur requires ```-U``` to install built packages, and so does makepkg.
