### ISSUE TITLE
git-latest oddity

### ISSUE THREAD

**Issue by sdothum** [rmarquis/pacaur#398]
I have similar Arch installs on several computers. For some reason, pacaur -Sua insists on listing

grub-btrfs-git-latest

for update on some arch installs, and not others (all have the same version of grub-btrfs-git installed) independent of whether the --devel flag is used or not. I've uninstalled the grub-btrfs-git package but after reinstallation, the problem persists even though the --devel flag is not enabled.

Any ideas how to track this down or fix the erroneous reporting?

Not a show stopper. I ignore it but it's puzzling.

**Comment by rmarquis** [comment]
Start by checking ```cower -u``` output.

**Comment by sdothum** [comment]
Okay.. on the server which doesn't report grub-btrfs-git-latest for update, cower -u reports nothing. On the problematic servers cower -u reports:

:: grub-btrfs-git v1.7.r6.g4388c33-1 -> v1.7.r6.g4388c33-1-1

Not sure if this is the appropriate action but renaming /var/lib/pacman/local/grub-btrfs-git-v1.7.r6.g4388c33-1 to v1.7.r6.g4388c33-1-1 clears up the problem. (The non-problematic server actually had an older version of the package).

If there is some other course of action I should take or investigate, I would be interested to know. Otherwise, feel free to close this issue.

Thanks!

**Comment by rmarquis** [comment]
Well, you'll need to figure out why installing latest grub-btrfs-git doesn't produce the same installed version... unless the installed versions weren't the same across all your machines. In any case, not a pacaur issue, closing now.
