### ISSUE TITLE
aur builds do not cache output

### ISSUE THREAD

**Issue by arnottcr** [rmarquis/pacaur#399]
On aur builds, pacaur does not copy the output *.pkg.tar.xz file from /tmp/pacaurtmp-<user>/<package>/ to /var/cache/pacman/pkg/ like pacman does with regular repository installs. I have seen this with other aur helpers, and would appreciate it.

As a side note, it would be nice for pacaur to check for a matching version in /var/cache/pacman/pkg/ before rebuilding from source. This may get tricky for git/svn/darcs/etc based development packages, but rebuilding those is usually desired.

**Comment by zoqaeski** [comment]
Yes it does. You need to set `PKGDEST` in either `/etc/makepkg.conf` or `$XDG_CONFIG_HOME/pacman/makepkg.conf`. Another trick is to add an environment variable called `AURDEST` and pacaur will clone all builds in a fixed directory. All my packages get built in ~/source, and the final package ends up in ~/packages

**Comment by rmarquis** [comment]
Yes, that's implemented (by makepkg). Read the man page please.

**Comment by arnottcr** [comment]
cool, thanks for the info; I have had other aur helpers cache builds to var for the user, so I thought this burden was on the helper, it is awesome that makepkg does this for you.

**Comment by rmarquis** [comment]
@arnottcr Makepkg has always done it, at least as far as I can remember. The issue mostly comes from yaourt that duplicates existing settings in its own config file.

**Comment by arnottcr** [comment]
@rmarquis would it be of merit to better document this on the [aur helpers](https://wiki.archlinux.org/index.php/AUR_helpers) or [aur](https://wiki.archlinux.org/index.php/Arch_User_Repository) page on the archwiki, so that others do not make my mistake in the future?

**Comment by rmarquis** [comment]
@arnottcr It's already on the [makpekg](https://wiki.archlinux.org/index.php/Makepkg) page. I wouldn't add it on the AUR page, since makepkg isn't AUR specific. Truly, I feel the issue is due to helpers unnecessarily duplicating settings, which confuses new and even older Arch users.

**Comment by arnottcr** [comment]
Alright, that makes sense; my thought was to link to the makepkg page in one of those two pages, as users could go to the helper page looking for how to change this behavior. But I am still new to arch, so I will trust your judgement.

**Comment by rmarquis** [comment]
@arnottcr The global consensus is that Arch users should learn to build manually with makepkg before using an AUR helper, so makepkg behavior is assumed to be known.

On a sidenote, this is also the reason AUR helpers are only available in the AUR and can't be installed without a manual install with makepkg.

Lastly, welcome to Arch, hope you'll enjoy it!

**Comment by arnottcr** [comment]
I follow you, that reasoning makes a lot of sense; thanks for your time and assistance with this.
