### ISSUE TITLE
can't install codependent packages

### ISSUE THREAD

**Issue by alexhenrie** [rmarquis/pacaur#402]
`pacaur -S cndrvcups-lb cndrvcups-common-lb` fails because these two packages depend on each other, but instead of invoking `pacman -U cndrvcups-lb.tar.xz cndrvcups-common-lb.tar.xz`, pacaur tries to execute `pacman -U cndrvcups-lb.tar.xz` and `pacman -U cndrvcups-common-lb.tar.xz` separately.

A simple solution would be to build all the packages sequentially, then install them all at once.

**Comment by rmarquis** [comment]
This is similar to #370. Especially, see [this comment](https://github.com/rmarquis/pacaur/issues/370#issuecomment-152723211). Modifying the install sequence order of packages is far from trvial, and here again, the solution is actually to remove the unnecessary versioned dependency.
