### ISSUE TITLE
Fix command pacaur -Syua

### ISSUE THREAD

**Issue by HLFH** [rmarquis/pacaur#403]
Hi,

With [`yaourt`](https://archlinux.fr/yaourt-en), the best alternative to `pacaur` (I switched to `pacaur`), I can use `yaourt -Syua` and it does the following: sync database, upgrade packages from [Arch Linux repos](https://wiki.archlinux.org/index.php/official_repositories) and from AUR.

But with `pacaur`, the command `pacaur -Syua` seems to do the following: sync database, upgrade package from AUR, and it forgets to upgrade packages from official Arch Linux repos.

Is that an issue? Do you plan to fix it? Am I completely wrong?

Thanks,
HLFH

**Comment by rmarquis** [comment]
Please read the man page.

**Comment by HLFH** [comment]
I read it. Ok, so  `pacaur -Syu` seems to do the trick with your solution.
