### ISSUE TITLE
no results found for error

### ISSUE THREAD

**Issue by pahofmann** [rmarquis/pacaur#415]
When upgradning my system I get the following error:
```
patrick $ pacaur -Syu
...
:: Starting AUR upgrade...
:: resolving dependencies...
:: no results found for error
```

I found similar issues here on github, but they occured when people tried to install new packages.
I have not installed new packages on that machine for a time.

Is there a way to find out which packages is causing the dependencie error?
`--debug` yields no results.

**Comment by rmarquis** [comment]
See #412.
