### ISSUE TITLE
sanitize variables

### ISSUE THREAD

**Issue by s0nspark** [rmarquis/pacaur#423]
When searching the AUR with the -s option I do not get results even when supplying a known package name. I do get results when performing the same search using cower. I'm using fresh installs of pacaur 4.5.2-1 and cower 14-2 on a fully updated system.

**Comment by rmarquis** [comment]
Can you give me an example? Search is directly passed to cower, without much tinkering beforehand.

**Comment by s0nspark** [comment]
Sure... :)

```bash
tim in ~ on teepee $ pacaur -s freshplayerplugin
:: target not found
tim in ~ on teepee $ cower -s freshplayerplugin
aur/freshplayerplugin 0.3.4-1 (109, 11.19) [installed]
    PPAPI-host NPAPI-plugin adapter.
aur/freshplayerplugin-git v0.3.3.r0.g6018406-1 (136, 6.72)
    PPAPI-host NPAPI-plugin adapter.
```

**Comment by rmarquis** [comment]
Cannot reproduce here:

```
$ pacaur -s freshplayerplugin
aur/freshplayerplugin 0.3.4-1 (109, 11.19)
    PPAPI-host NPAPI-plugin adapter.
aur/freshplayerplugin-git v0.3.3.r0.g6018406-1 (136, 6.72)
    PPAPI-host NPAPI-plugin adapter.
```

Could you provide a complete debug output with `bash -x pacaur -s freshplayerplugin`? This is weird.

**Comment by s0nspark** [comment]
No problem... I am also including my cower and pacaur configs, just in case they are somehow to blame.

[pacaur-search-debug-output.txt](https://github.com/rmarquis/pacaur/files/129786/pacaur-search-debug-output.txt)
[cower-config.txt](https://github.com/rmarquis/pacaur/files/129787/cower-config.txt)
[pacaur-config.txt](https://github.com/rmarquis/pacaur/files/129788/pacaur-config.txt)

**Comment by rmarquis** [comment]
Thanks. I see two things that raise my attention in your debug output:
- two `grep '^Color' /etc/pacman.conf` while I do have only one. I assume you have `Color` disabled in pacman.conf, is this correct? Can you attach your pacman.conf here?

- This, near the end : `+ [[ -n /home/tim/Dropbox/Working/s0nspark/sysadm/dotfiles ]]`. I have no idea how you did your setup, but I feel this might likely be related to your issue. Can you tell me more about this?

**Comment by s0nspark** [comment]
Here is my pacman.conf... I have not set any Color option there. 

As for the -n option referencing my dotfiles repo, I have no clue where that is being pulled from or why. Are there any other config files that come into play?

[pacman.conf.txt](https://github.com/rmarquis/pacaur/files/129798/pacman.conf.txt)

**Comment by s0nspark** [comment]
Dang... found it. I had unwittingly set a $repo env variable as an alias for my dotfile dir, not realizing that was being used elsewhere. I unset it and bingo - I get results now. Sorry for the bother!

**Comment by rmarquis** [comment]
Thanks, I was really wondering what was happening here. Yes, if both the `$repo` and `$aur` variables are set, this means pacaur should avoid looking into the repo and the aur altogether - which triggers the "target no found" message and exits.

I guess I might be able to sanitize the code so similar issues don't happen in the future by using locale variables when that does make sense.

**Comment by s0nspark** [comment]
Thanks again for the help... :)

**Comment by rmarquis** [comment]
Thanks to you... That's a pacaur issue after all.

**Comment by rmarquis** [comment]
Done in 89d673b61a632a22bdb07048dcab4fde62ad5969.
