### ISSUE TITLE
package failed to install

### ISSUE THREAD

**Issue by Tyrsen** [rmarquis/pacaur#427]
http://i.imgur.com/Yhwrckf.png

package fails to install, says to check srcinfo against pkgbuild for discrepancies, but none are visible

**Comment by rmarquis** [comment]
The discrepancy is in the `pkgrel` version. Ping the maintainer about it, .SRCINFO should be updated.

**Comment by Tyrsen** [comment]
ah, there's me being blind

**Comment by rmarquis** [comment]
:D
