### ISSUE TITLE
Request: config to skip "View PKGBUILD?"

### ISSUE THREAD

**Issue by entrity** [rmarquis/pacaur#431]
In the pacaur config file, may we have an option to omit the prompt `View <package> PKGBUILD? [Y/n]` which appears when a package is installed?

Alternatively (or additionally), may we have an option to change the default from `Y` to `N`?

Thanks in any case.

**Comment by rmarquis** [comment]
This is already implemented. Please read the man page.

I will not change the default prompt order.
