### ISSUE TITLE
change default clonedir path to home dir

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#434]
Currently, the default clonedir path is set to `$TMPDIR` if the env var $AURDEST isn't defined yet.
This is bad practice since `/tmp` is by default set to memory on Arch and users might have issues when compiling big package. The default path should be set to the user home directory (for example `~/aur/clone` which is what I personally use, but better suggestion are welcome).

Advanced user would want to set `clonedir` to a non volatile location anyway, and define `$BUILDDIR` to /tmp if they really want to build in /tmp.

**Comment by AladW** [comment]
How about ```XDG_CACHE_HOME/pacaur``` ? It has a similar purpose as /tmp, compare:

```
$XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.
```
https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html
```
~/.cache
Persistent user cache data. User programs may place non-essential data in this directory. Flushing this directory should have no effect on operation of programs, except for increased runtimes necessary to rebuild these caches. If an application finds $XDG_CACHE_HOME set, it should use the directory specified in it instead of this directory.
```
https://www.freedesktop.org/software/systemd/man/file-hierarchy.html

**Comment by rmarquis** [comment]
Good! Then `$XDG_CACHE_HOME/pacaur` it will be, with a fallback to `~/.cache/pacaur`.

Or maybe even `$XDG_CACHE_HOME/aur/clone`, as only PKGBUILDs are cloned and are helper independent. Might be an opportunity to define a common location for existing or future helpers here.

**Comment by rmarquis** [comment]
Done in c5d750f75f040b21249fff100a2c8875348d03d1.
