### ISSUE TITLE
"No results found for error" - fixed

### ISSUE THREAD

**Issue by pfrenssen** [rmarquis/pacaur#435]
When using pacaur I was getting a "No results found for error" error on updating with `pacaur -Syu` on two separate systems. I was able to update each package on its own without errors.

This can be solved by updating pacaur and cower manually:

```
$ pacaur -S pacaur cower
```

**Comment by rmarquis** [comment]
This is due to the new pacman version (libalpm soname bump). Well known issue, hopefully I could fin a way to make the error more explicit in the future.
