### ISSUE TITLE
Supress the "aur/" prefix when I execute a search with "-s"

### ISSUE THREAD

**Issue by simonbcn** [rmarquis/pacaur#440]
When I execute a search with `-s`, `pacaur` shows a list with `aur/`prefix in all package names:
```
$ pacaur -s libreoffice                         
aur/libreoffice-extension-languagetool 3.2-1 (217, 6,00)
    An Open Source style and grammar checker (30 languages)
aur/libreoffice-faenza-mod 0.4.2-3 (96, 0,00) [installed]
    An icons pack for LibreOffice, inspired by Faenza icons
aur/bibus 1.5.2-5 (41, 0,00)
    A bibliographic database that can directly insert references in
    OpenOffice.org/LibreOffice and generate the bibliographic index.
aur/libreoffice-style-papirus 20160301-3 (37, 8,00) [installed]
    Libreoffice Papirus theme
....
```

The `-s` option is an AUR specific operation, so I see redundant show this prefix. 
It seems only a cosmetic change but it would improve the usability and readability of the search results.

**Comment by rmarquis** [comment]
Search is entirely provided by cower. Also, I personally prefer it that way.

**Comment by simonbcn** [comment]
I have added a feature request in cower: https://github.com/falconindy/cower/issues/123
