### ISSUE TITLE
Pacaur doesn't install a package if sudo times out

### ISSUE THREAD

**Issue by marmistrz** [rmarquis/pacaur#445]
Sometimes building a package takes a long time (see: `atom-editor`). Pacaur asks for the password at the beginning, takes a lot of time to build.

Once I visit the terminal, I can see the sudo password prompt (although I didn't enter any password) which is no longer active - the shell awaits commands. The package is not installed.

**Comment by AladW** [comment]
Did you read the manual? See "sudoloop".

**Comment by rmarquis** [comment]
Alternatively, set up the `passwd_timeout` sudo parameter.
