### ISSUE TITLE
please add an option to add a second confirmation to install

### ISSUE THREAD

**Issue by bigmittens** [rmarquis/pacaur#450]
allow the user to use the [Y/n] dialog that pacman queries.

**Comment by rmarquis** [comment]
What the exact issue here? I'm not sure what is the problem.

**Comment by bigmittens** [comment]
not so much of an issue as a request, you don't have to add it if you don't like. it would be nice to be able to have a second confirmation from the user before installing in case a warning has been thrown during the build or you've changed your mind about installing whatever it may be.

if you're not sure what i'm talking about, normally after a .tar.xz file is made, pacman will ask ":: Proceed with installation? [Y/n]" and then you'll type your answer. when pacaur is run, yes is automatically chosen.

**Comment by rmarquis** [comment]
Well, no.

**Comment by bigmittens** [comment]
:"(
