### ISSUE TITLE
do not check build files with diff is empty

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#452]
When updating with `--devel --needed`, VCS packages will be checked for update and only built if their source has been updated. However, the prompt to inspect build files will be displayed regardless of the outdated status of the sources.

Display the build files inspection prompt only for VCS packages that will be rebuilt. This should only apply when both `--devel` and `--needed` are used.

**Comment by rmarquis** [comment]
Not sure how tired I was when I entered this issue, but it doesn't make sense. For one thing, build files retrieval (git clone) is completely independent from the actual project source files, and if `--devel` is passed it means the build files have not changed at all. If the build files have been updated by the maintainer on the AUR, then there will be a new pull and diff view if enabled.

Instead, the build files diff should be skipped when empty.

**Comment by rmarquis** [comment]
Done in a2fe4aaf86c125b564e5fb70307378f045944c7e.

**Comment by rmarquis** [comment]
@avelkei @pakapusta @Yoshi2889 @ChuckDaniels87 @MakeNowJust @kyak 

The above commit adds a single new string to translate (sorry!). Since you guys have an otherwise 100% complete translation, you might want to send an update before the next release.

Instructions are in the po/HOWTO file.

I hope to make the new release at the end of the week.

**Comment by MakeNowJust** [comment]
@rmarquis Ok, I will work it today. Thanks. 水曜日, 06 4月 2016, 06:28午前 +09:00 from Remy Marquis < notifications@github.com> :

**Comment by Yoshi2889** [comment]
I'll try to update my translation today :) though my laptop will be going
in for repair so I'll need to setup a VM on my Mac or desktop.

I'll also fix the colorW issue on AUR upgrade.

Op wo 6 apr. 2016 03:14 schreef TSUYUSATO Kitsune <notifications@github.com

**Comment by avelkei** [comment]
Thanks for the heads up, made a pull request.

**Comment by rmarquis** [comment]
@Yoshi2889 I can update the file for you if you tell me the translation (see a2fe4aaf86c125b564e5fb70307378f045944c7e).

**Comment by Yoshi2889** [comment]
@rmarquis That'd be great, thanks.

${colorW}$i${reset} build files are up-to-date -- skipping
translates to:
build bestanden voor ${colorW}$i${reset} zijn up-to-date -- overgeslagen

If you could also fix this issue while you're at it, that'd be great:
msgstr "$(colorW)AUR upgrade starten...${reset}"
needs to become:
msgstr "${colorW}AUR upgrade starten...${reset}"
(bracket change)

Thanks!

**Comment by rmarquis** [comment]
@Yoshi2889 Done in 677a77b328fc7e23e0a4c8e045283e7a34aa69dd.
