### ISSUE TITLE
Add interactive search(like yaourt)

### ISSUE THREAD

**Issue by jck** [rmarquis/pacaur#454]
It would be nice to have a way to search repos/aur simultaneously and enter a number to install the package.

**Comment by rmarquis** [comment]
I never really liked that feature, and I'm not interested in spending time in implementing and maintaining it. You can however find a [python wrapper](https://github.com/dgoltzsche/pacaur-wrapper) that adds this feature if you really want it.

**Comment by DoTheEvo** [comment]
+1 but I guess pointless unless mind changed in a year

I tried switching to pacaur on my fresh new ryzen build with fresh arch install, but it feels like I am being punished for it.

I dont remember exact package names, and with pacaur I have to do search offical repos and aur separatly to see all the options and afterwards manually write out the names of what I found to actually start the installation. 

I thought with some aliases pacaur would get easier, but I would need several...

I guess I should not try to fix whats not broken

**Comment by rmarquis** [comment]
Mind didn't change, but there is a [new wrapper](https://aur.archlinux.org/packages/pac/) in the AUR to mimic yaourt search.

>  I have to do search offical repos and aur separatly to see all the options

No idea what that means.
