### ISSUE TITLE
$AURDEST directory becomes cluttered

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#461]
The `$AURDEST` directory tends to become cluttered over time, mostly with symlink and leftover of the makepkg build process, even though the sources and built packages are configured to be stored elsewhere (SRCDEST, PKGDEST).

Find a way to keep it clean, maybe by extending the -Sc operation. Keep in mind that extra files are also kept there if some of the env variables ($SRCDEST, $PKGDEST, $LOGDEST, ..) aren't set in makpekg.conf.

**Comment by AladW** [comment]
I might be missing something, but doesn't AURDEST only contain the git 
clone directories, where the actual build is performed?

**Comment by rmarquis** [comment]
> doesn't AURDEST only contain the git clone directories, where the actual build is performed?

Yes. Isn't that exactly what I wrote above?

**Comment by AladW** [comment]
Oh, you mean cluttering of the /sub-directories/ of AURDEST. :D

In the absence of LOGDEST, you could create a "log" directory in a clone 
directory, and pass the LOGDEST variable directly to makepkg, e.g

mkdir -p log
LOGDEST=${LOGDEST:-./log} makepkg <args>

You could remove symbolic links with find, though this is hairy:

[[ -d $AURDEST ]] && find "$AURDEST"/* -maxdepth 1 -type -l -delete

Otherwise I'd let makepkg -c and friends do the job.

**Comment by rmarquis** [comment]
Yeah, subdirectories, my bad. :)

The `makepkg -c` option is already passed by default, I'll have to check why some leftover files aren't removed. Might actually be because PKGDEST is defined - the symlink is still created.

**Comment by rmarquis** [comment]
The `makepkg -c` option indeed doesn't remove symlink to build packages and log files.
In pacaur, log files are only created when the --silent option is set.

**Comment by AladW** [comment]
FWIW, I use this script to clean up AURDEST:
```
#!/bin/sh
readonly argv0=cleanup.sh
cd /home/aur || exit

# Remove regular files in the parent directory.
find -maxdepth 1 -type f -not -name "$argv0" -delete

# Remove source tarballs.
find -maxdepth 2 -type f -name '*.tar.gz' -delete

# Remove backup files.
find -maxdepth 2 -type f -name '*~' -delete

# Remove symbolic links to packages.
find -maxdepth 2 -type l -name '*.pkg*' -delete

# Remove non-empty pkg/src directories.
find -maxdepth 2 -type d -name pkg -or -name src -print0 | xargs -0 rm -r
```

**Comment by rmarquis** [comment]
Thanks!

**Comment by AladW** [comment]
Note that all of the above can be replaced with `git clean`:
```
find -maxdepth 2 -type d -name '.git' -execdir git clean -xi \;
```
This includes a nice selection dialog for what files you want to delete.

**Comment by rmarquis** [comment]
Thanks, git clean is indeed cleaner to use here, although I'd prefer to clean automatically without the interactive part.

Also, I probably should think about some option to remove clone directories of packages that aren't installed anymore.

**Comment by rmarquis** [comment]
From #559:

> Maybe git clean should be run automatically after a successful build, and also extend -Scc to delete the git folders of uninstalled packages as two separate features?

I am unsure about automatic cleaning after a successful build. This isn't what makepkg does, and users that haven't configured PKGDEST or SRCDEST expect the source and build files to be there.

**Comment by terencode** [comment]
Yes it should not be automatic and at least let the user decide what to do if added.

**Comment by rmarquis** [comment]
Done in 10baa520f66b1fabd7eed7c6596bc74cb1a3940b, as a `-Sc` command extension.
