### ISSUE TITLE
Git diff package files: Exclude .SRCINFO

### ISSUE THREAD

**Issue by Edenhofer** [rmarquis/pacaur#462]
Pacaur is capable of diffing cached package files. However viewing the diffs may get pretty cluttered without any sane reason since the diff of the whole git repo is presented including the .SRCINFO file. This file is not mandatory for the build process and serves no other purpose than to pass certain package properties to the AUR. Therefore it is reasonable to exclude it from the diff.

**Comment by rmarquis** [comment]
Yeah, agree. I have currently some reserve as the .SRCINFO is not always updated by maintainers and the diff allows to quickly check that too, but this is definitely something to implement in the future.

**Comment by rmarquis** [comment]
Potential implementation [here](http://stackoverflow.com/questions/10415100/want-to-exclude-file-from-git-diff):

```
git diff `git status -s |grep -v ^\ D |grep -v file/to/exclude.txt |cut -b4-`
```

Hopefully I could find something cleaner.

**Comment by Edenhofer** [comment]
There is a much nicer build in git-diff paramter to fix this probelm: `git diff . ':!\.SRCINFO'`, respectively `git diff . ':(exclude)\.SRCINFO'`. The only downside is, that it was added fairly recently.
By the way, the same parameter is valid for `git log`, where I initially once found [this](http://stackoverflow.com/questions/5685007/making-git-log-ignore-changes-for-certain-paths/21079437#21079437).

**Comment by rmarquis** [comment]
This looks great, thanks for the heads up! I guess there is no downside at all since Arch is a rolling distro with the latest version of any software available.

**Comment by Edenhofer** [comment]
I guess you are right.

**Comment by rmarquis** [comment]
Should be implemented in 7eff3d6bd4f2406970b03365af9d883e19c3a10b. Feedback welcome here.

**Comment by Edenhofer** [comment]
Looks good.

**Comment by Edenhofer** [comment]
Things stopped working for me... I guess it is related to 1f217be.

**Comment by rmarquis** [comment]
Can you confirm?

**Comment by Edenhofer** [comment]
I tried to mimic the behaviour as good as possible and the approach in the pacaur script worked fine but pacaur still displays the .SRCINFO diff for me.

**Comment by rmarquis** [comment]
Likely, that part of the code isn't triggered. Do you see the `View <package> build files diff?` message?

**Comment by Edenhofer** [comment]
Yes, I do see that question. I also get the `<package> build files diff viewed` message. Therefore I think the code is actually triggered.

**Comment by rmarquis** [comment]
Yup, something weird is going on...

**Comment by blueyed** [comment]
@Edenhofer "stopped working" means the `.SRCINFO` file appeared in the output again?
Can you please try the update with (#522), which uses git-log, and then git-bisect it to really find the commit that broke it for you, please?

**Comment by Edenhofer** [comment]
Yes, the `.SRCINFO` is displayed again even with #522. I am actually quite surpised I am the only experiencing this. I will have another look at it and report back if I find something suspicious.

**Comment by rmarquis** [comment]
I can also reproduce the issue. I just updated to git 2.9.0, this might be related but I'm not certain about it.

**Comment by Edenhofer** [comment]
Switching `$diffcmd` to `eval $diffcmd` works for whatever reason...

**Comment by blueyed** [comment]
Yes, it looks like the single quotes do not work with just `$diffcmd`.
I think `eval` is a good approach here.
And it should also use `--` to separate the paths.
I'll do a PR.

**Comment by Edenhofer** [comment]
Yes, would make sense if it was all about the quotes... Eitherway it works flawless now.
