### ISSUE TITLE
store cache packages

### ISSUE THREAD

**Issue by gutenye** [rmarquis/pacaur#47]
after pacaur install a aur package, I'd like to put the package 'foo_x86-64.pkg.tar.xz` into '/var/cache/pacman/pkg', so that I can keep a copy of packages. for example, when I copy a whole system from one computer to another, I can use /var/cache/pacman/pkg, instead of download all packages from Internet(which is slow).

something like this:

```
pacaur -S pacaur --cache 

# /etc/pacaur.conf
cache = false  # cache the package to /var/cache/pacman/pkg default is false
```

**Comment by EgonSpengler** [comment]
Sorry for bringing back a very old issue, but this is something I'd love to have the option for, without changing makepkg.conf and running pacaur as root.  I actually had thought pacman did this by default and was surprised to not find an installed AUR package in the pkg cache.

It's possible to let pacman cache the package file itself as it installs.  Per the [Arch Wiki][1],
```# pacman -U /path/to/package/package_name-version.pkg.tar.xz```
will just install a package, but
```# pacman -U file:///path/to/package/package_name-version.pkg.tar.xz```
will copy it to /var/cache/pacman/pkg before it installs.

I understand that this would be a bad default behavior, but it would be a nice configuration option to make pacaur fit more seamlessly.

[1]:https://wiki.archlinux.org/index.php/Pacman#Additional_commands

**Comment by rmarquis** [comment]
Pacaur doesn't use `pacman -U` to install AUR packages, but use the `-i` flag of makepkg instead for technical reasons (proper way to ensure correct behavior when installing split packages).

If you want to store AUR packages in `/var/cache/pacman/pkg`, you don't need to run makepkg as root. Simply configure the `PKGDEST` variable accordingly and add write permission for your user.

**Comment by EgonSpengler** [comment]
I see, thanks for the input.  I guess I was misled by the message ```==> Installing package <package> with pacman -U...``` when installing AUR packages.
