### ISSUE TITLE
Pacaur doesn't check AUR for new dependancies

### ISSUE THREAD

**Issue by Spagy** [rmarquis/pacaur#474]
When installing a package from the AUR, if the list of dependancies in PKGBUILD  is changed to include another AUR package then installation fails.

Here is the output when installing ricin-git. I changed the dependancy from meson to meson-git (available from the AUR).
```
:: Building ricin-git package(s)...
==> Making package: ricin-git 0.540.62bb688-1 (Wed  6 Apr 21:24:12 BST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
error: target not found: meson-git
==> ERROR: 'pacman' failed to install missing dependencies.
:: failed to build ricin-git package(s)
```

**Comment by rmarquis** [comment]
This is because pacaur uses the AUR RPC interface to solve the dependency tree, and never actually parses PKGBUILDs. You should either fix it in the PKGBUILD upstream (ping the maintainer about it), or tinker manually with cower. Yes, this is by design.

**Comment by Spagy** [comment]
Thanks, I'll have a look at cower. You're right ideally the upstream PKGBUILD should be fixed. Not in this case but sometimes the maintainer is unresponsive.
