### ISSUE TITLE
[Regression] -D --asexplicit does not automatically call sudo anymore

### ISSUE THREAD

**Issue by spider-mario** [rmarquis/pacaur#478]
The regression seems to have been introduced in c76cd81e494f8fae6a81832443e290f162f540e5 because of the `--asexp` instead of `--asexplicit` in the regexp.

**Comment by rmarquis** [comment]
Indeed, good catch.

**Comment by rmarquis** [comment]
Fixed in 830fc3fd73388df3bf7342439f220b77782c7997.
