### ISSUE TITLE
"mismatching data with PKGBUILD" in the keybase-git package

### ISSUE THREAD

**Issue by oconnor663** [rmarquis/pacaur#483]
Pacaur seems to be upset with something about how our `pkgver` function formats the version number. Here's what we have now (which fails):

```bash
pkgver() {
    "$srcdir/client/packaging/version.sh" prerelease | sed 's/-/_/g'
}
```

That produces version numbers like `1.0.15_20160412164431+b747605`. If instead we use this function adapted from the `peru-git` package, the error goes away:

```bash
pkgver() {
    cd "$srcdir/client"
    echo $(git rev-list --count master).$(git rev-parse --short master)
}
```

I see several closed issues related to "mismatching data", but it looks like those have all been fixed. I just repro'd this issue with both `pacaur` and `pacaur-git`. Are our version numbers evil?

(Would it be possible to add some more output about exactly what difference pacaur is seeing?)

**Comment by rmarquis** [comment]
Seems the `+` is the evil part here. See [guidelines](https://wiki.archlinux.org/index.php/PKGBUILD#pkgver).

> (Would it be possible to add some more output about exactly what difference pacaur is seeing?)

Unfortunately, not possible without parsing the PKGBUILD itself.

**Comment by oconnor663** [comment]
Ok, I've fixed this on our end. It's an unfortunate limitation, since it doesn't support SemVer.

**Comment by rmarquis** [comment]
Yes. Note this is related to `vercmp`, and not directly related to pacaur.

**Comment by oconnor663** [comment]
Hmm, removing the `+` hasn't fixed the issue. When I diff `~/.cache/pacaur/keybase-git`, I see this:

```diff
diff --git a/PKGBUILD b/PKGBUILD
index e76607b..12193e3 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -3,7 +3,7 @@
 pkgname=keybase-git
 pkgdesc='the Keybase Go client, filesystem, and GUI'
 license=('BSD')
-pkgver=1.0.15_20160412195754_74b75aa
+pkgver=1.0.15_20160412200627_743277d
 pkgver() {
   "$srcdir/client/packaging/version.sh" prerelease | sed 's/[-+]/_/g'
 }
```

And here's the `.SRCINFO`:

```
# Generated by mksrcinfo v8
# Tue Apr 12 19:58:08 UTC 2016
pkgbase = keybase-git
	pkgdesc = the Keybase Go client, filesystem, and GUI
	pkgver = 1.0.15_20160412195754_74b75aa
	pkgrel = 1
	install = keybase.install
	arch = i686
	arch = x86_64
	license = BSD
	makedepends = go
	makedepends = npm
	makedepends = git
	makedepends = rsync
	depends = fuse
	conflicts = keybase
	conflicts = keybase-release
	source = git+https://github.com/keybase/client
	source = git+https://github.com/keybase/kbfs-beta
	md5sums = SKIP
	md5sums = SKIP

pkgname = keybase-git
```

**Comment by rmarquis** [comment]
Yep, this is weird. I'll have a closer look.

**Comment by oconnor663** [comment]
`vercmp` does seem willing to compare versions with `+`'s in them, and even `-`'s.

Apologies in advance for our painfully long build time on that package. You can repro the problem even if you clear out `build()` and `package()` and replace their bodies with `:`, which avoid wasting time on npm. Thanks for taking a look.

**Comment by rmarquis** [comment]
Your custom versioning system is indeed completely evil. Every time you run `makepkg` on it, a different `pkgver` is generated, even though the source files are _strictly_ the same.

I have no idea why you'd want to do that, but in any case I'd suggest you to get rid of the timestamp part of your custom pkgver. It just doesn't make sense.

Note that prior to pacman 5, that kind of system could have worked with pacaur as it used to use `makepkg -i`, but I had no choice but replace it (see #364) and pacaur has to "manually" track the version prior to installation, which fails here.

Also note your system might work with older helpers that don't make use of the RPC interface to retrieve info, or with bauerbill as it uses a custom, patched `makepkg` instead of relaying of the official script.

**Comment by oconnor663** [comment]
Interesting :) The version number we were using was the same scheme as the build number we use internally, for the Debian and RPM packages we host. I've switched it to a format without the timestamp. Thanks again for digging through this.
