### ISSUE TITLE
pacaur reinstalls the same package multiple times

### ISSUE THREAD

**Issue by rastilion** [rmarquis/pacaur#485]
Example:

command: pacaur -Syu (--devel, makes no difference)

AUR Packages  (42): (package list)

(checks)

:: Installing chromium-pepper-flash cached package... <---------------Note here
loading packages...
warning: yaourt-git-1.8.1.r15.g2cc7ba3-1 is up to date -- reinstalling <--------------- ...and here
resolving dependencies...
looking for conflicting packages...

Packages (1) yaourt-git-1.8.1.r15.g2cc7ba3-1

Total Installed Size:  0,77 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? Y/n 
(1/1) checking keys in keyring                                                                                                 [#############################################################################] 100%
(1/1) checking package integrity                                                                                               [#############################################################################] 100%
(1/1) loading package files                                                                                                    [#############################################################################] 100%
(1/1) checking for file conflicts                                                                                              [#############################################################################] 100%
(1/1) checking available disk space                                                                                            [#############################################################################] 100%
:: Processing package changes...
(1/1) reinstalling yaourt-git                                                                                                  [#############################################################################] 100%
:: Installing atom-editor cached package... <--------------- same here
loading packages...
warning: yaourt-git-1.8.1.r15.g2cc7ba3-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) yaourt-git-1.8.1.r15.g2cc7ba3-1

Total Installed Size:  0,77 MiB
Net Upgrade Size:      0,00 MiB

in this case, yaourt-git gets reinstalled 41 times (42 packages -1 update)
Repo-packages are updated correctly, only updates on AUR are affected.

**Comment by rmarquis** [comment]
Which version are you using?

**Comment by rastilion** [comment]
pacaur 4.5.6 and 4.6.1 showed this behaviour, switching to 
4.6.1.11.gc3bb05d git seems to fix it.
I switched to git version after writing the issue down, sorry.

**Comment by rmarquis** [comment]
That issue was in fact fixed in 4.6.1.

**Comment by yoelion** [comment]
I'm still at a same problem. then not fixed

**Comment by rmarquis** [comment]
@yoelion 

Post
```
pacaur -v
```

Then
```
pacaur -S <package>
bash -x pacaur -S <package>
```

**Comment by yoelion** [comment]
'pacaur -Syu' make problems, but not only
[pacaur.txt](https://github.com/rmarquis/pacaur/files/219105/pacaur.txt)

**Comment by rmarquis** [comment]
According to your debug output, the command `pacaur -S cower-git` works as expected. Your other output is incomplete.

Again, please post

```
pacaur -Syu
bash -x pacaur -Syu
```

**Comment by yoelion** [comment]
[pacaur.txt](https://github.com/rmarquis/pacaur/files/219234/pacaur.txt)

**Comment by yoelion** [comment]
i disabled powerpill

**Comment by rmarquis** [comment]
@yoelion Looks like the very same issue as #475 to me.

**Comment by yoelion** [comment]
so expac-git?
