### ISSUE TITLE
reimplement ignorerepo support

### ISSUE THREAD

**Issue by atmenta** [rmarquis/pacaur#486]
Feature request: please reimplement ignorerepo support.

Since v4.6.0 cower is not used for update checks, thus its `IgnoreRepo` config option is not honoured, consequently pacaur can not detect AUR updates for packages also found in some of the affected repos. Please consider the reimplementation of this functionality. I would prefer to have such an option in the config file and as a command line option as well.

**Comment by rmarquis** [comment]
Avoiding to use cower for update check avoids a lot of issue from a maintainer point of view, and also reduces noise in official channels from people that shouldn't be using a helper in the first place (but unfortunately do). The drawback is that ``--ignorerepo`` is now gone, but it is not coming back.
