### ISSUE TITLE
Update does't find new dependency with --devel, but does without

### ISSUE THREAD

**Issue by jakebailey** [rmarquis/pacaur#489]
I've seen #480, but I'm on 4.6.2, so this isn't the same issue.

When updating `android-sdk`, there's a new dependency (`ncurses5-compat-libs`). If I update with `--devel`, the new dependency isn't found. Without the option, it is found. Here are two corresponding debug outputs up until the prompt. (The `--aur` flag doesn't affect the behavior, I just have it there to skip updating repo packages which are broken right now thanks to two official packages packing bash completion files for `mount` and `unmount`.)

[With --devel](http://termbin.com/phmt)

[Without --devel](http://termbin.com/013a)

If you need anything else, let me know.

**Comment by rmarquis** [comment]
Thanks for the report. Sounds indeed like a bug.

**Comment by rmarquis** [comment]
This is a regression introduced in 1424f0b9f5e3506c3874c6f5063911c0ea086262 (in #reorder devel), see #441. The other `comm -3` replacement might be buggy too.

**Comment by rmarquis** [comment]
Fixed in dffcab88685e6adcdc64efb72de15fd7b1dab474. An array was overwritten mid-course. The other `comm -3` replacement call was not concerned by this issue.
