### ISSUE TITLE
Arguments with spaces not forwarded to pacman correctly

### ISSUE THREAD

**Issue by chaoren** [rmarquis/pacaur#490]
E.g.,
```
$ touch "foo bar"
$ pacaur -Qo foo\ bar
error: failed to find 'foo' in PATH: No such file or directory
error: failed to find 'bar' in PATH: No such file or directory
$ pacman -Qo foo\ bar
error: No package owns foo bar
```

You should quote everything so that arguments get forwarded exactly as is. E.g.,
```
"$pacmanbin" "${pacmanarg[@]}" "${pacopts[@]}" "${pkgs[@]}"
```
instead of
```
$pacmanbin ${pacmanarg[@]} ${pacopts[@]} ${pkgs[@]}
```

Upon further inspection, there's another problem with your script. Places like this:
```
[[ -z "${repopkgs[@]}" ]]
```
should be like this instead:
```
[[ -z "${repopkgs[*]}" ]]
```

FYI,
```
foo=(a "b c")
"${foo[@]}" # expands to "a" "b c"
"${foo[*]}" # expands to "a b c"
 ${foo[@]}  # expands to "a" "b" "c"
 ${foo[*]}  # expands to "a" "b" "c"
```

**Comment by rmarquis** [comment]
Thanks, this is related to #460. I am aware of that issue and never fixed it since nobody should use silly space in filenames. So the question remains: Why would you use space in filename? What is your usercase?

**Comment by ChuckDaniels87** [comment]
Well, even if there is any usercase, `pacaur` shouldn't break `pacman` usability.

**Comment by chaoren** [comment]
There are packages that contain files with spaces in their names. I have no control over this. Doing `pacaur -Qo` on these files to find out which package owns them should just work.

I personally don't have strong opinions on whether file names should contain spaces, and that's irrelevant, since these files do exist, and your script chokes on them.

**Comment by rmarquis** [comment]
Tracking in #460, closing here.
