### ISSUE TITLE
Add option to bypass cache

### ISSUE THREAD

**Issue by sammoth** [rmarquis/pacaur#491]
If I run `pacaur -S firefox-developer` [1], I get the following:

    :: Retrieving package(s)...
    :: Checking firefox-developer integrity...
    ==> Making package: firefox-developer 47.0a2-1 (Tue Apr 19 19:51:31 BST 2016)
    ==> Retrieving sources...
      -> Found firefox-47.0a2.en-US.linux-x86_64.tar.bz2
      -> Found firefox-developer.desktop
      -> Found vendor.js
    ==> Validating source files with sha512sums...
        firefox-47.0a2.en-US.linux-x86_64.tar.bz2 ... Skipped
        firefox-developer.desktop ... Passed
        vendor.js ... Passed

However the cached copy of firefox-47.0a2.en-US.linux-x86_64.tar.bz2 is not current as it is regularly updated on the server and pacaur's cached copy is old. Is there any way to force pacaur to update the package without manually deleting the cached file?

[1] https://aur.archlinux.org/packages/firefox-developer/

**Comment by rmarquis** [comment]
Already implemented. Please read the man page.

**Comment by sammoth** [comment]
I have read `man pacaur` quite thoroughly before asking - could you point me at the right command please? I have tried `--rebuild`, `--download`, `--update`, `--sync`.

**Comment by rmarquis** [comment]
If  ```--rebuild``` doesn't work here, then it's not supported. Using the same version number for different build is stupid anyway.

**Comment by sammoth** [comment]
Ok makes sense, I'll make a better pkgbuild. Thanks

**Comment by rmarquis** [comment]
The issue is more on the side of Mozilla here. There is no way a PKGBUILD can be done better here, as once the source are downloaded locally the PKGBUILD will use these to make the package. Can't rely on the pkgver, can't rely on the md5sum either since it is skipped. Makepkg can only fails is retrieving the new version, unless you remove the downloaded source and old built packages. The `-Sc` option might help here, but I'll not implement any workaround because Mozilla is stupid.

**Comment by sammoth** [comment]
Mozilla are providing a build id for each build in a json file in the same folder which should be unique and is basically a date stamp. I've changed the pkgbuild to get the pkgver from that and also rename the source file on download using that build id. This seems like it works ok though it would mean that the package directory would get filled up with source archives over time.

**Comment by rmarquis** [comment]
Sounds like a neat solution. As for the filling up, have a look at #461. This is not implemented yet but will provide just what you need here.

**Comment by rmarquis** [comment]
I fixed an installation issue in 986d3ead6056ebe4a3b197ed70976b78c2744cca. The problem was that nightly packages relaying on dynamically updated version through `pkgver()` weren't treated as other regular VCS packages, and the installation failed due to mismatching version in the package string.
