### ISSUE TITLE
noconfirm doesn't work

### ISSUE THREAD

**Issue by BigfootN** [rmarquis/pacaur#494]
Hello,

When launching pacaur for installing a package with `pacaur -S --noconfirm <package>` I still get this type of question: `View <package> PKGBUILD?  [Y/n]`.

The option works with official packages but not with aur packages.

Thank you very much for any response :)

**Comment by rmarquis** [comment]
This is not a bug. Read the man page.

**Comment by BigfootN** [comment]
Thank your very much for your answer and sorry for not having read more carefully the manual.
