### ISSUE TITLE
Use local .SRCINFO for dependency resolution

### ISSUE THREAD

**Issue by blueyed** [rmarquis/pacaur#496]
I've noticed that a local .SRCINFO (which might have been fixed/altered) is not considered when resolving dependencies: only the JSON from the AUR seems to be used for that.

I think the `.SRCINFO` should be taken into account, and maybe even used only for this?!

See also https://github.com/rmarquis/pacaur/blob/f8cad8667deaeb3280620fd811f823af7307507b/pacaur#L925, where `.SRCINFO` is used for `makedepends` handling.

**Comment by rmarquis** [comment]
No. Dependency resolution is done before any PKGBUILD/.SRCINFO is downloaded. There is no point in changing this, as locally modified .SRCINFO are out of scope of the project.

In fact, I really dislike the way pacaur parses the .SRCINFO file at all, but it's necessary for a specific edge case (see #432 and relevant commit b851f2820b1761a65567f42d2af3808c15c3189c). Maybe I could check makedepends while processing the dependency tree early on instead...

**Comment by blueyed** [comment]
> locally modified .SRCINFO are out of scope of the project

Fair point.
Feel free to close it then.

**Comment by rmarquis** [comment]
Also, note that there are [ongoing discussions](https://lists.archlinux.org/pipermail/aur-dev/2016-April/004034.html) on the aur-dev ML about potential features, including full dependency trees solving for AUR packages. We might be able to offload this computation directly server side.

I'll review your pull requests in details shortly. Lot of good stuff from your side, thx!
