### ISSUE TITLE
Option to keep existing clonedir as is / git-pull --rebase

### ISSUE THREAD

**Issue by blueyed** [rmarquis/pacaur#500]
While you can use `-e` to edit build files, it does not seem to be possible to just keep existing ones.

There could be an option that would make `DownloadPkgs` keep existing clonedirs?

Additionally/alternatively I could imagine using `git pull --rebase` instead of the `git reset --hard HEAD + git pull`, which would take care of that automatically.

**Comment by rmarquis** [comment]
This seems to be related to your PR #495. I probably should clarify right now that pacaur has never been designed to handle modified PKGBUILDs, and this is still something I am unwilling to do. Stuff like customizepkg or personal modification that won't make it back to the upstream PKGBUILD should be handled manually with cower or other tools. Unless I get a steady flow of money to encourage me to maintain it on the long term, but I doubt that would ever happen.

If you really wish this feature, I'd suggest you to maintain your own fork here. For the same reason,  I believe your commit f8cad8667deaeb3280620fd811f823af7307507b in PR #495 is also out of scope of the initial objective of pacaur. Commit f8cad8667deaeb3280620fd811f823af7307507b seems valid though, and cleaner than the timestamp method.
