### ISSUE TITLE
"--ignore" and "IgnoreGroup" ignored

### ISSUE THREAD

**Issue by simonbcn** [rmarquis/pacaur#501]
`pacaur v4.6.4`

I have several packages installed from a `PKGBUILD` modified by me and I have added these packages to a group (_modified_) to avoid upgrade from AUR/PACMAN with the parameter `IgnoreGroup = modified` in `/etc/pacman.conf` but pacaur doesn't respect it.
One of those packages (**whatsie**) has an update in AUR database that it has a annoying bug, because this I wan't upgrade it but `pacaur` does:
```
$ pacaur -u
:: Starting AUR upgrade...
:: resolving dependencies...
:: looking for inter-conflicts...
:: gtk-theme-arc-git latest revision -- fetching

AUR Packages  (5): filebot-4.7-1  google-chrome-50.0.2661.94-1  gtk-theme-arc-git-latest  ultra-flat-icons-1.3.4-6  whatsie-2.0.14-17  

:: Proceed with installation? [Y/n] 
```
That package is in _modified_ group:
```
$ pacman -Qs whatsie  
local/whatsie 2.0.13-1 (modified)
    A simple & beautiful desktop client for WhatsApp Web.
```

`--ignore modified` option doesn't work:
```
$ pacaur -u --ignore modified  
:: Starting AUR upgrade...
:: resolving dependencies...
:: looking for inter-conflicts...
:: gtk-theme-arc-git latest revision -- fetching

AUR Packages  (5): filebot-4.7-1  google-chrome-50.0.2661.94-1  gtk-theme-arc-git-latest  ultra-flat-icons-1.3.4-6  whatsie-2.0.14-17  

:: Proceed with installation? [Y/n] 
```

**Comment by rmarquis** [comment]
This is out of scope, pacaur has never been intended to manage packages modified by the user. See also #388.

**Comment by simonbcn** [comment]
> pacaur has never been intended to manage packages modified by the user. 

That's what I want. 

> That's because AUR packages don't have groups. 

The groups in AUR packages is unnecessary. But installed packages have groups:
```
$ pacman -Qs whatsie  
local/whatsie 2.0.13-1 (modified)
    A simple & beautiful desktop client for WhatsApp Web.
```

**Comment by rmarquis** [comment]
> That's what I want.

The you are out of luck. Either you'll need to fork, or you'll need to sponsor the feature. In the man page, you'll find a way to send me money. Loooot of money.
