### ISSUE TITLE
Rebuild aur packages only when there are new changes

### ISSUE THREAD

**Issue by podhorsky-ksj** [rmarquis/pacaur#503]
Hello, 
I want to ask, if there is such combination of parameters of pacaur that aur package is rebuild only when is needed? (when there is some new changes, commits in repository)

I tried the combination `pacaur -Syu --noconfirm --noedit --devel --needed` but it's not rebuilt the package, where there is new change in repository.

And without `--needed` parameter `pacaur -Syu --noconfirm --noedit --devel`, all aur packages are rebuilt

**Comment by rmarquis** [comment]
If PKGBUILDs are correctly written, then `--devel --needed` is what you re looking for.
