### ISSUE TITLE
JSON request results in '414 Request-URI Too Large' error when checking for updates

### ISSUE THREAD

**Issue by coppolalab** [rmarquis/pacaur#504]
I seem to be encountering the same issue described #209 when I use pacaur to check for updates in the AUR.  I currently have ~1200 AUR packages installed, and the update check always fails with a `Could not connect to the AUR` error.  However, checking with cower or yaourt works as expected.  I followed the directions on troubleshooting by saving the debug output of pacaur to a file.  When I try to run the `curl` request generated by pacaur in the debug output, I get the same 414 error described in #209. 

In the pacaur source, I can see that there is a check if the URI request is more than 8125 characters.  For requests longer than that, it splits the request in half.  However, this imposes a restriction of 16250 characters for the length of the URI because a larger request will still  exceed the length restriction.  In my case the, the total URI request is about 21000 characters, so splitting in half isn't sufficient to meet the length restriction.  

Obviously in my situation dividing the request by 3 would be sufficient to overcome the problem.  A more ideal solution described by @rmarquis in #238 was to divide the length of the request by the length limit and figure out dynamically how many pieces it should be split into.  Is there a plan to ever implement this?  I realize that very few users try to manage this many AUR packages, so I understand why this may not be priority at the moment.

**Comment by rmarquis** [comment]
Hu, 1200 AUR packages? Ever thought about approaching the Guinness World Records organization?
And yes, this is very very low priority, but patches are welcome.

Preferred way to solve this would be to implement [https://bugs.archlinux.org/task/49089 FS#49089] upstream.

**Comment by mistachie777** [comment]
This is the OP under a different account (I forgot to sign out of my group account).  I tend to like to experiment with packages, and somehow I ended up with that many installed ;)  Anyway, I will look at trying to implement  the "dynamic" URI splitting workaround in pacaur.  I didn't realize that the AUR API only supported GET requests, but I agree completely that the long term solution is for them to support POST.  Unfortunately I'm not a web developer so I wouldn't begin to know how to implement it!

**Comment by rmarquis** [comment]
Done in ff827ea95c057ac893a7f8338bb637c443eae551.
