### ISSUE TITLE
When one AUR package upgrade fails, then all the AUR package upgrades fail.

### ISSUE THREAD

**Issue by thx1111** [rmarquis/pacaur#506]
pacaur 4.6.4-1

Arguably, more a feature request than a bug:

$ pacaur -Syu
...
:: Starting AUR upgrade...
...
:: resolving dependencies...
:: looking for inter-conflicts...
:: python3-memoizedb-2016.4.24.1-1 has been flagged out of date on 2016-05-12

AUR Packages  (6):

Name                       Old Version     New Version   

aur/chromium-pepper-flash  1:21.0.0.216-1  1:21.0.0.242-1               
aur/gcc-gcj                5.3.0-7         6.1.1-2                      
aur/opera-beta             37.0.2178.27-1  37.0.2178.31-1               
aur/opera-developer        38.0.2213.0-1   39.0.2226.0-1                
aur/pdftk                  2.02-7          2.02-9                       
aur/python3-memoizedb      2016.4.6-1      2016.4.24.1-1                

:: Proceed with installation? [Y/n] 

:: Retrieving package(s)...
:: chromium-pepper-flash build files are up-to-date -- skipping
:: gcc-gcj build files are up-to-date -- skipping
:: opera-beta build files are up-to-date -- skipping
:: opera-developer build files are up-to-date -- skipping
:: pdftk build files are up-to-date -- skipping
:: python3-memoizedb build files are up-to-date -- skipping
:: Checking python3-memoizedb integrity...
==> Making package: python3-memoizedb 2016.4.24.1-1 (Thu May 12 09:31:06 MDT 2016)
==> Retrieving sources...
  -> Downloading python3-memoizedb-2016.4.24.1.tar.xz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading http://xyne.archlinux.ca/projects/python3-memoizedb/src/python3-memoizedb-2016.4.24.1.tar.xz
    Aborting...
:: Checking pdftk integrity...
...
:: failed to verify python3-memoizedb integrity

So now, none of the other AUR packages are actually upgraded.  And pacaur does not explicitly say so, despite a lot of output about downloading package files.  That is not good user feedback, where instead, pacaur could also have said something like "Packages <list> have not been upgraded."

In this case, the python3-memoizedb package must be addressed first, manually.  We can now run

$ pacaur -Su --ignore python3-memoizedb

to upgrade the other packages.  But, is that the best approach?  Or, should pacaur automatically ignore the failed package, and continue installing the other AUR packages?

It seems to me that automatically continuing with install of the other AUR packages is a more graceful failure response.  Or, there could be a "--continue" option, to automatically ignore a package build failure.  What do you think?

**Comment by rmarquis** [comment]
Working as designed, I'm not going to change anything here.

**Comment by blueyed** [comment]
Came here for the same issue.

```
:: Checking telegram-desktop-bin integrity...
==> Making package: telegram-desktop-bin 1.0.0-2 (Tue Jan 17 12:18:41 CET 2017)
==> Retrieving sources...
  -> Found telegram-desktop-bin.desktop
  -> Found tg.protocol
  -> Found icon16.png
  -> Found icon32.png
  -> Found icon48.png
  -> Found icon64.png
  -> Found icon128.png
  -> Found icon256.png
  -> Found icon512.png
  -> Found tsetup.1.0.0.tar.xz
==> Validating source files with sha256sums...
    telegram-desktop-bin.desktop ... Passed
    tg.protocol ... Passed
    icon16.png ... FAILED
    icon32.png ... FAILED
    icon48.png ... FAILED
    icon64.png ... FAILED
    icon128.png ... FAILED
    icon256.png ... FAILED
    icon512.png ... FAILED
==> ERROR: One or more files did not pass the validity check!
…
Other updates
…
:: failed to verify telegram-desktop-bin integrity
```
```
> It seems to me that automatically continuing with install of the other AUR packages is a more graceful failure response. Or, there could be a "--continue" option, to automatically ignore a package build failure. What do you think?

I think it should ask interactively by default to continue.

But when aborting like it currently does, this should be done earlier already maybe.

I also got the impression that other packages would have been updated.

**Comment by rmarquis** [comment]
I avoid to do it right away in case more than a package integrity fails. The user doesn't loose time since you need all the other files to be downloaded anyway.

Maybe other packages would have been updated, but I'd still need to ensure that all the packages that rely on that failing dependency don't go through. For sake of sanity and simplicity, pacaur aborts and let the user fix or ignore the failing package. Pacman behavior is similar.

**Comment by blueyed** [comment]
Fair point.

Maybe then the error message in that case should be improved?!
It should clearly state that no (AUR) packages have been updated (it aborted), and then also give a hint about using `--ignore`?!

**Comment by rmarquis** [comment]
Isn't it obvious already? In case of failure, the user is expected to read the output... and of course he should see that no packages have been updated.

**Comment by thx1111** [comment]
> For sake of sanity and simplicity, pacaur aborts and let the user fix or ignore the failing package. Pacman behavior is similar.

But then, I'd suggest that, instead, this behavior is just "broken", and ought to be fixed some day.  After all, the purpose of computers is to *automate* mundane activities, and not to simply create an new kind of unnecessary "busy work" for people.  I do not know of any kind of "sanity" that could be invoked by forcing the administrator to intervene, except, perhaps, the sanity of the software developer, who might have other priorities. ;)  The process is certainly not "simple" for the end user.

Regardless, whether resolved automatically or manually, the error message should be more conspicuous and informative.

**Comment by thx1111** [comment]
> Isn't it obvious already?

Speaking for myself - usually "it just works", "fire and forget", and I tend *not* to read all the "boilerplate" - up until I recognize that nagging feeling that something "is not right", and I *have* to read everything.  It could be easier.  I don't want to have to prove that I'm a "rocket scientist" every time I upgrade.  Sometimes it's nice to have a little "hand holding".

**Comment by rmarquis** [comment]
Just a reminder: pacaur is targeted at users that know how to do thing manually with makepkg. The above is really the same behavior as makpekg. Fails the integrity check? Then stop and do not continue compiling. 

I absolutely don't care if users don't want to learn the basis - I won't dumb down the code for the sake of pleasing the lowest common denominator. If people want hand holding and not doing their homework, then they can fork and maintain the stuff by themselves. I'll also happily accept extra large sums of money in exchange of a script that provide that service. This is not worth my free time.

(to be clear: not aiming at someone at particular here, but yes, many users shouldn't be using pacaur in the first place).

**Comment by ArchangeGabriel** [comment]
@thx1111 ArchLinux *requires* you to look at update logs. If you don’t, you’re going into troubles on your own. If you don’t like that fact, maybe this is not the most suitable distro for you. ;) pacaur should not be doing anything differing from this official stance, especially when the AUR requires even more attention than repos (after all, you’re supposed to check each PKGBUILD diff).
