### ISSUE TITLE
arguments with leading dash

### ISSUE THREAD

**Issue by abouvier** [rmarquis/pacaur#508]
pacaur can't handle arguments with a leading dash. It seems that the double dash option is not implemented.

I understand:
> $ pacman -Ss -nox
> error: invalid option '-n'

Using double dash:
> $ pacman -Ss -- -nox
> community/boinc-nox 7.6.32-1
>     Berkeley Open Infrastructure for Network Computing for desktop without Xorg dependencies
> community/emacs-nox 24.5-4 [installed]
>     The extensible, customizable, self-documenting real-time display editor, without X11 support
> community/erlang 18.3.3-1
>     General-purpose concurrent functional programming language developed by Ericsson
> community/erlang-nox 18.3.3-1
>     General-purpose concurrent functional programming language developed by Ericsson (headless version)
> community/qbittorrent-nox 3.3.3-2
>     An advanced BitTorrent client programmed in C++, based on Qt toolkit and libtorrent-rasterbar, w/o gui
> community/virtualbox-guest-utils-nox 5.0.20-1
>     VirtualBox Guest userspace utilities without X support

Hmm, what?
> $ pacaur -Ss -nox
> :: no targets specified (use -h for help)

Oops :p
> $ pacaur -Ss -- -nox
> error: invalid option '-n'
> cower: invalid option -- 'n'

Hallelujah!
> $ cower -s -- -nox
> aur/coq-nox 8.5pl1-1 (3, 0.00)
>     Formal proof management system. Headless version, without CoqIDE.
> aur/cppcheck-nox 1.72-1 <!> (3, 0.76)
>     A tool for static C/C++ code analysis without the GUI
> aur/erlang-nox-r17 17.5-1 (1, 0.01)
>     General-purpose concurrent functional programming language developed by Ericsson (headless version)
> aur/gst-plugins-bad-rpi-nox 1.6.2-1 (0, 0.00)
>     GStreamer Multimedia Framework Bad Plugins with compilation options optimized for RaspberryPi so that
>     glimagesink works without Xorg
> aur/proofgeneral-nox 4.2-2 (2, 0.01)
>     Generic interface for proof assistants, built for emacs-nox
> aur/vim-nox master-0 (0, 0.00)
>     Vi Improved, console-only build with python2 support. Latest version from git.
> aur/vlc-nox 2.2.3-1 (2, 0.73)
>     A multi-platform MPEG, VCD/DVD, and DivX player (without X support)

**Comment by rmarquis** [comment]
Patches welcome.

**Comment by rmarquis** [comment]
Done in 659b6dbad657aabba48f863318523c2d43a2d7dd.
