### ISSUE TITLE
Fail more meaningfully when no targets specified with -R

### ISSUE THREAD

**Issue by d125q** [rmarquis/pacaur#511]
Currently, `pacaur -R` simply passes everything over to `pacman` and results in
```txt
error: you cannot perform this operation unless you are root.
```

It would be more meaningful if it instead failed with
```txt
error: no targets specified (use -h for help)
```
as `pacman` does.

**Comment by rmarquis** [comment]
Bring that to the pacman developers, this has nothing to do with pacaur.

**Comment by d125q** [comment]
But `sudo pacman -R` _does_ fail with
```txt
error: no targets specified (use -h for help)
```

**Comment by rmarquis** [comment]
Oh, I see. The wrong branch of the conditional test is passed to pacman here. Reopening.

**Comment by rmarquis** [comment]
Done in 5563b7a66623853316a0cce9890cd8815c5da1f0.
