### ISSUE TITLE
An extra choose providers pops up

### ISSUE THREAD

**Issue by olliemath** [rmarquis/pacaur#512]
A minor bug, but `pacuar -S python-geopy` pulls in the dependency `python-oauthlib`, which in turn requires `python-pyasn1`. I'm given the following option:
```
:: There are 2 providers available for pyasn1:
   0) python2-pyasn1 (extra) 
   1) python-pyasn1 (extra) 

Enter a number (default=0):
```

Clearly I was very worried because the default option seems to be a python2 package. A bit of digging shows that the two are in fact precisely the same binary in the repos. The correct behaviour which `pacman -S python-oauthlib`, `pacaur -S python-oauthlib` and even downloading the geopy PKGBUILD and using `makepkg -sri` give is to recognise that these are actually precisely the same packages and just install them without asking.

**Comment by rmarquis** [comment]
Thanks for the report. The `python2-pyasn1` and `python-pyasn1` packages are actually distinct packages (split), but something is definitely fishy here. The prompt shouldn't appear at all since the dependency chain is explicitly defined with the dependency set on `python-pyasn1` (`python-oauthlib` -> `python-cryptography` -> `python-pyasn1`).

**Comment by rmarquis** [comment]
Fixed in 35ffc401c0ac20575ef546af308ae6beb929e8b0. This was actually a bug that stayed under the radar for a very long time.

**Comment by olliemath** [comment]
To be fair, I don't think most users would notice - it's only because I just adopted the `python-geopy` package that I was very twitchy about packages the install pulled in.

**Comment by rmarquis** [comment]
Good catch then. Only the prompt was faulty, the correct dependency was always installed even if you chose the "wrong" choice beforehand.
