### ISSUE TITLE
Some sort of dependency resolution problem

### ISSUE THREAD

**Issue by ekce** [rmarquis/pacaur#514]
When trying to install [python2-s3transfer](https://aur.archlinux.org/packages/python2-s3transfer/) before [python2-botocore](https://aur.archlinux.org/packages/python2-botocore/) pacaur fails with the message
```
error: target not found: python2-botocore>=1.3.0
error: target not found: python2-botocore<2.0.0
==> ERROR: 'pacman' failed to install missing dependencies.
:: failed to build python2-s3transfer package(s)
```
Altering the way that the dependencies are written in the PKGBUILD does not seem to affect the end result.

Yaourt is able to resolve the dependency correctly.

**Comment by rmarquis** [comment]
Missing .SRCINFO upstream. Ask the maintainer to do its job properly.

**Comment by ekce** [comment]
Thank you, I will notify the author.
