### ISSUE TITLE
-Fsy <something> leads to "error: you cannot perform this operation unless you are root."

### ISSUE THREAD

**Issue by du5tball** [rmarquis/pacaur#516]
When I try `$ pacaur -Fys vim`, I receive the following message: `error: you cannot perform this operation unless you are root.` -Fs and -Fy by themselves work perfectly fine.

**Comment by rmarquis** [comment]
Thanks for the report. Fixed in 632ed8e99b5de0b3cd77d8ab1773b529d6d39ffa.
