### ISSUE TITLE
pacaur 4.6.4-1 - out-of-date .cache/pacaur/ source and erroneous .SRCINFO - install fails

### ISSUE THREAD

**Issue by thx1111** [rmarquis/pacaur#518]
Sorry - I really don't get why pacaur is creating a ~/.cache/pacuar/...  which just seems to be filled with a lot of stuff that was suppose to be in /etc/makepkg.conf "BUILDDIR", and then deleted afterward.

Well, it seems to be causing an additional problem, besides the seeming "bloat", by using an out-of-date cached file instead of the current file.  In particular, when upgrading firefox-aurora, Nightly build, with a clean BUILDDIR firefox-aurora directory, there is:

/var/build/firefox-aurora/src/
lrwxrwxrwx 1 james james   82 Jun  3 11:43 firefox-48.0a2.en-US.linux-x86_64.tar.bz2 -> /home/james/.cache/pacaur/firefox-aurora/firefox-48.0a2.en-US.linux-x86_64.tar.bz2

where /home/james/.cache/pacaur/firefox-aurora/firefox-48.0a2.en-US.linux-x86_64.tar.bz2 is the old and out-of-date file.  The install fails because the sha512sum does not match the current file - thankfully.

Even deleting both the ~/.cache/pacuar/firefox-aurora and the {BUILDDIR}/firefox-aurora, pacuar ends with:
:: firefox-aurora package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD.

where ~/.cache/pacaur/firefox-aurora/.SRCINFO has an empty "sha512sums =" for the source, even though "makepkg --printsrcinfo" prints the correct "sha512sums =" from the PKGBUILD.

Would these issues be from pacaur faults?  Or firefox-aurora PKGBUILD faults?

And, what am I not understanding about the need for, or purpose of, ~/.cache/pacaur?

**Comment by rmarquis** [comment]
See #491. Ensure the source is deleted in SRCDEST if defined too.

> And, what am I not understanding about the need for, or purpose of, ~/.cache/pacaur?

There is a hint in the man page.

**Comment by thx1111** [comment]
Am I understanding correctly, where #491 says "I've changed the pkgbuild to get the pkgver from that and also rename the source file on download using that build id.", that in general, the PKGBUILD *must* ensure that the source file always gets renamed appropriately?

And then, the purpose of ~/.cache/pacaur/_package_/, where the man page has
build files comparison
           To allow build files comparison...
it is just that, to act as a "snapshot" of previous installs, to support "diff" and such?

But then also, what about the resulting ~/.cache/pacaur/firefox-aurora/.SRCINFO, where "makepkg --printsrcinfo" output seems correct, but the saved .SRCINFO has missing bits?  Isn't that from pacaur?  I see that "pacman -U _saved_package_" does not complain.

**Comment by rmarquis** [comment]
> Am I understanding correctly [...] that in general, the PKGBUILD must ensure that the source file always gets renamed appropriately?

If you want to ensure correct automation, yes.

> it is just that, to act as a "snapshot" of previous installs, to support "diff" and such?

Yes.

> Isn't that from pacaur? 

The saved .SRCINFO comes directly from the AUR, it is not created by pacaur.
