### ISSUE TITLE
Rework --cachedir with -Sc option

### ISSUE THREAD

**Issue by raingloom** [rmarquis/pacaur#519]
I was trying to use the first long enough to realize it is not where packages will be downloaded to with -Sw.

Does --cachedir influence PKGDEST? I get that PKGDEST is for locally built packages only.

**Comment by rmarquis** [comment]
Actually, no. I don't think makepkg takes `--cachedir` into account. This might however make sense to support it as an override of PKGDEST for AUR packages. I'll check this out, thanks for the report.

**Comment by rmarquis** [comment]
For the records:

```
CacheDir = path/to/cache/dir
           Overrides the default location of the package cache directory. A typical default is /var/cache/pacman/pkg/. Multiple cache directories can be specified, and they are tried in the order they are
           listed in the config file. If a file is not found in any cache directory, it will be downloaded to the first cache directory with write access.  NOTE: this is an absolute path, the root path is
           not automatically prepended.
```

```
--cachedir <dir>
           Specify an alternative package cache location (a typical default is /var/cache/pacman/pkg). Multiple cache directories can be specified, and they are tried in the order they are passed to pacman.
           NOTE: This is an absolute path, and the root path is not automatically prepended.
```

And see this [relevant post](https://bbs.archlinux.org/viewtopic.php?pid=1616148#p1616148) in the Arch forums.

I'm still not sure if and how `--cachedir` should influence `PKGDEST`, but setting an additional path in `CacheDir` might actually be a much better idea than extending `-Sc` in pacaur code.

**Comment by rmarquis** [comment]
The -Sc, -Scc functions now take CacheDir into account (b61c3edcb360e11134f9a840e0ff268bda371ba9).

What should be done:
* remove the other hardcoded /var/cache/pacman/pkg/ in Prompt()
* `--cachedir` should add the added cache in the CacheDir array (and also be passed to pacman)

pacconf would be great to use here, but I don't want to add yet another AUR dep. Maybe later if pacutils gets merged with pacman tools.

Still can't make my mind about the relationship with `PKGDEST`...

**Comment by rmarquis** [comment]
`PKGDEST` should stay independent from `--cachedir`. This isn't even a pacaur option, but an option from makepkg. No clarification is even needed in the pacaur man page.

**Comment by rmarquis** [comment]
This has been done in #569, which includes the removal of the `CacheDir` trick.
Closing now. The inclusion of pacconf improvement is tracked in #433.
