### ISSUE TITLE
`pacaur -Ss sagemath -r` exits with status 1

### ISSUE THREAD

**Issue by d125q** [rmarquis/pacaur#526]
Consider the following search queries:
```sh
pacaur -Ss sagemath -r
pacman -Ss sagemath
```

They both yield the same results, however, `pacaur` exits with status 1, while pacman exits with status 0.  Is this intentional?  I believe that `pacaur` should exit with status 1 if and only if the search didn't match anything.

**Comment by rmarquis** [comment]
Not intentional. Thanks for the report.

**Comment by blueyed** [comment]
Just discovered this myself.
Seems to happen only where there are no matching AUR packages.

**Comment by d125q** [comment]
@blueyed: I thought the same; however, there _are_ matching AUR packages, try `pacaur -Ss sagemath -a`.

**Comment by blueyed** [comment]
Yes, but with `-r` you are skipping this: so the exit code is 1 in case AUR was not searched or nothing was found there.  I typically only use `pacaur -Ss`.

**Comment by rafamanzo** [comment]
The same happens for the following:

`pacman -Qu` exits with status `1`
`pacaur -Qu` exits with status `0`

Please let me know if you'd like me to report this as a separate issue.

**Comment by rmarquis** [comment]
Thanks for the report.

**Comment by rmarquis** [comment]
Fixed in 78f880505aab33be27c0e8f65fc3523ce333cbef.
