### ISSUE TITLE
Skip --quit-if-one-screen of less with git-log in displaybuildfiles=diff

### ISSUE THREAD

**Issue by blueyed** [rmarquis/pacaur#527]
I would like to display the `--quit-if-one-screen` feature of `less` with the `git log` call for `displaybuildfiles=diff`: this way the log output won't just scroll by, but has to be "confirmed" using `q`.

For this I could imagine passing in `--paginate` (which makes git skip the `pager.log` command), and setting `PAGER` for the `git-log` call.  But skipping `pager.log` would disable the setup/redirect through e.g. diff-so-fancy.

My settings:

`core.pager`:

    pager = less -S --no-init --quit-if-one-screen 

`pager.log`:

    log = ~/.dotfiles/lib/diff-so-fancy/diff-so-fancy | $(git config core.pager)

The following works for my setup to disable the feature for `git-log` in general, but it's not what I want normally, e.g. with `git log -1`:

    log = ~/.dotfiles/lib/diff-so-fancy/diff-so-fancy | $(git config core.pager | sed 's/--quit-if-one-screen//')

What do you think?

**Comment by blueyed** [comment]
An option specific to my setup would be to detect if `pacaur` called `git-log` and to remove the `--quit-if-one-screen` only in that case.

**Comment by rmarquis** [comment]
This sounds like a bloated idea. Isn't there any way to rely on the PAGER env variable only?

**Comment by rmarquis** [comment]
I am honestly not interested in adding another specific variable just for the purpose of using diff-so-fancy - I'd actually prefer to remove as many as possible.

Feel free to maintain your personal fork though. I don't expect much activity on the pacaur side until pacman features force me to do so.
