### ISSUE TITLE
pacaur -Scc inconsistency in input

### ISSUE THREAD

**Issue by nplatis** [rmarquis/pacaur#528]
When issuing `pacaur -Scc`, I get three prompts: The first two are the ones from the respective `pacman` command, the third one is about removing files from AUR cache.

Now, the first two prompts need me to press 'y' or 'n' and then 'Enter' to answer, but for the last one just pressing 'y' or 'n' sets the answer.

I believe this last prompt should be changed to wait for 'Enter' as well, for two reasons:

1. consistency with the previous two
2. possibility to change your mind!

**Comment by rmarquis** [comment]
Agree, something should be done here,

**Comment by nplatis** [comment]
I just notice that the same holds when issuing `pacaur -Syu`: the prompt for pacman repostories requires pressing 'Enter' after 'y' or 'n' whereas the prompt for AUR packages does not.

I don't know if it is something centralized, so I thought I should report this case as well.

**Comment by rmarquis** [comment]
> I don't know if it is something centralized, so I thought I should report this case as well.

Note the _speedy_ prompt is intentional (see #371), and I don't think it is really an issue when using `-Syu` with the repository update part handled by pacman. With `-Scc`, however, that issue is annoying because both kind of prompt happen after one another.

**Comment by rmarquis** [comment]
Done in 5d5c502c373600c5755ebe2d7a1a2128b7663f35, using non speedy pacman style.
