### ISSUE TITLE
pacaur and typescript

### ISSUE THREAD

**Issue by tensor5** [rmarquis/pacaur#533]
TypeScript 2.0.0 ignores files in paths with a hidden component, like `~/.cache/pacaur`. This is not really an issue with pacaur, but rather a poor implementation on TypeScript side of [this feature request]( https://github.com/Microsoft/TypeScript/issues/6861).

I though that I should report it here because it created troubles to some people trying to install [this AUR package](https://aur.archlinux.org/packages/black-screen/) with pacaur (see the comments on the package page).

**Comment by rmarquis** [comment]
The `.cache` directory is pretty standard on linux (`XDG_CACHE_HOME`), and a natural alternative to `/tmp` that fills up and that is thus problematic.

So... is there anything that should be done on the pacaur side here? Looks like this should be fixed upstream.

**Comment by tensor5** [comment]
I reported it upstream, and it seems they fixed it now (https://github.com/Microsoft/TypeScript/issues/9899). It was obviously a typescript bug, not pacaur. Since it took me some time to figure out, I thought I should report it here too, in case other people have the same problem.
No need to do anything, thanks.
