### ISSUE TITLE
Resuming incomplete downloads on servers without resume support

### ISSUE THREAD

**Issue by qguv** [rmarquis/pacaur#537]
When pacaur is directed to download a file that was previously stopped prematurely, curl tries to resume the download from a particular byte position. If the download server does not support this, pacaur will fail ungracefully. It becomes necessary to manually remove the affected package's cache in `$HOME/.cache/pacaur/`.

A solution would be to detect such an error by checking whether curl exited with '33' (HTTP range error, see man 1 curl, section EXIT CODES).

Here's what the bug looks like:

    :: Checking nwjs-bin integrity...
    ==> Making package: nwjs-bin 0.16.1-1 (Thu Aug 18 00:38:19 EDT 2016)
    ==> Retrieving sources...
      -> Downloading nwjs-v0.16.1-linux-x64.tar.gz...
    ** Resuming transfer from byte position 8736768
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0 47.1M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
    ==> ERROR: Failure while downloading http://dl.nwjs.io/v0.16.1/nwjs-v0.16.1-linux-x64.tar.gz
        Aborting...

**Comment by rmarquis** [comment]
It isn't pacaur that download files, but makepkg. I don't think pacaur should check specific error codes and act on them, rather, the user should be completely in charge.

However, this looks like this could be handled in #461.
