### ISSUE TITLE
Allow --ignore "regex pattern"

### ISSUE THREAD

**Issue by benutzer193** [rmarquis/pacaur#538]
I always prefix my local packages with my initials to avoid conflicts with repo or AUR packages and ignore these packages when updating with pacaur.

For me it would be really convenient if I could just add the prefix as regex ignore pattern.
I don't know if I am the only one interested in this feature, but perhaps you also like the idea and as you already implemented it for the --search option I hope it is not too much work adding it for the --ignore option.

**Comment by rmarquis** [comment]
I never implemented regex for search, since this is done by cower, not pacaur.
That feature isn't worth the hassle.

**Comment by benutzer193** [comment]
Okay thanks for the explanation!
