### ISSUE TITLE
Missleading integrity error

### ISSUE THREAD

**Issue by NicoHood** [rmarquis/pacaur#550]
If a package is not supported for your platform, pacaur prints an integrity error, which is wrong. This was tested on an ARM installation, however this could also happen to x64 exclusive software for example.

```
[alarm@alarmpi pacaur]$ pacaur -S mkinitcpio-tinyssh
:: Package(s) mkinitcpio-tinyssh not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (3) mkinitcpio-tinyssh-0.0.3-1  tinyssh-20160812-1  ucspi-tcp-0.88-6  

:: Proceed with installation? [Y/n] y
:: Retrieving package(s)...

Cloning into 'mkinitcpio-tinyssh'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Cloning into 'tinyssh'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 0), reused 1 (delta 0)
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.
Cloning into 'ucspi-tcp'...
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 0), reused 6 (delta 0)
Unpacking objects: 100% (6/6), done.
Checking connectivity... done.
:: View mkinitcpio-tinyssh PKGBUILD? [Y/n] 
:: mkinitcpio-tinyssh PKGBUILD viewed
:: View mkinitcpio-tinyssh.install script? [Y/n] y
:: mkinitcpio-tinyssh.install script viewed
:: View tinyssh PKGBUILD? [Y/n] n
:: View tinyssh.install script? [Y/n] n
:: View ucspi-tcp PKGBUILD? [Y/n] n
:: Checking ucspi-tcp integrity...
==> ERROR: ucspi-tcp is not available for the 'armv7h' architecture.
:: Checking tinyssh integrity...
==> ERROR: tinyssh is not available for the 'armv7h' architecture.
:: Checking mkinitcpio-tinyssh integrity...
==> Making package: mkinitcpio-tinyssh 0.0.3-1 (Sat Sep 10 06:42:20 UTC 2016)
==> Retrieving sources...
  -> Downloading mkinitcpio-tinyssh-0.0.3.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137    0   137    0     0    227      0 --:--:-- --:--:-- --:--:--   228
100  2385    0  2385    0     0   1948      0 --:--:--  0:00:01 --:--:--  9937
==> Validating source files with sha512sums...
    mkinitcpio-tinyssh-0.0.3.tar.gz ... Passed
:: failed to verify ucspi-tcp integrity
:: failed to verify tinyssh integrity
```

**Comment by rmarquis** [comment]
Pacaur is solely developed for the official Arch variants. This does not include ARM, but patches welcome.

**Comment by NicoHood** [comment]
As I already said, this was only tested on arm, but its very likely that it will also happen with an x64 exclusive package. So please reopen this issue, it is still valid for the normal arch. It was just simpler for me to reproduce this way.

**Comment by rmarquis** [comment]
No, it's not likely, unless the x86_64 arch is missing from the PKGBUILD/.SRCINFO file. In which case the PKGBUILD should be fixed.

The issue here is that armv7h is unsupported, as the makepkg output states.

**Comment by NicoHood** [comment]
And what if you have an x32 or x64 only application that will **not** work on the other architecture? It is intended that the installation will fail (as it does right now too), however the error message below is wrong. And that is the point.

As a sideeffect I want to ignore those errors, but that has nothing to do with the actual issue. Sorry for not clarifying this enough.

The error must be somewhere around here:
https://github.com/rmarquis/pacaur/blob/master/pacaur#L936-L951

Wouldn't it also make sense to abort on the first invalid checksum error? Right now it will download all sources and then finally fail. You should know best if it makes sense to abort after the first error.

**Comment by rmarquis** [comment]
Short answer:

> but patches welcome
> This means that absolutely no support is provided, unless you are ready to pay for it.

Both works for me.

Long answer: I absolutely don't care about the dying 32 bit arch, and if the software is open source then a 64 bit version can be provided. I am yet to see such a package, and I also absolutely don't care about arm.

> Wouldn't it also make sense to abort on the first invalid checksum error?

No, for the same reason pacaur display all deps not found rather than aborting after the first error.

**Comment by NicoHood** [comment]
Okay, alright. Is a different error message also not an option for you? You might want to put it in other words, but basically this would give the best hint:
`failed to verify ${colorW}$i${reset} integrity or is incompatible with your arch`
