### ISSUE TITLE
Pacaur doesn't handle mixed-mode updates

### ISSUE THREAD

**Issue by marmistrz** [rmarquis/pacaur#551]
A real life example. `qtcreator` (community) gets upgraded from `4.0.0` to `4.1.0`. So is `qtcreator-cppcheck-plugin`, which depends on the same version of `qtcreator`.

Since the upgrade process is two-step: repos first, then AUR, the upgrade cannot proceed, because it'd break the dependencies of `qtcreator-cppcheck-plugin` would be broken.

**Comment by rmarquis** [comment]
Mixed mode update should _never_ be allowed. Talk to the maintainer and see if this can somehow be fixed upstream. If it can't, then you'll have to manually handle the update.

**Comment by marmistrz** [comment]
But what's wrong with it?

**Comment by rmarquis** [comment]
Pacaur handles update on a complete updated system. Allowing partial update, or mixing pacman and AUR update together is a very bad idea and a can of worm I'll not open. I am not even sure it is possible to bypass the pacman update operation.

If the maintainer insist to require a hard versioned dependency, that is his choice - but most of the time this is completely unnecessary and doesn't make sense on a rolling distrib.

**Comment by marmistrz** [comment]
Any example of what bad could happen?

In this case the plug-in has to be compiled against the same version of the IDE it's used in and an official binary is used.

**Comment by rmarquis** [comment]
> Any example of what bad could happen?

Do you mean if the hard dependency is removed in the PKGBUILD, or if I try to mix both official and AUR packages installation together?

Former is a simple annoyance for the user, that will recompile the plugin once the main package is updated. The latter is myself throwing the entire pacaur code in the toilet and never looking at it again.
