### ISSUE TITLE
In package upgrade prompt show previous version in addition to new version of each package to be upgraded

### ISSUE THREAD

**Issue by ohjames** [rmarquis/pacaur#553]
It's very useful to be able to see the previous version, whenever I upgrade I want to know if a package is going from `3.6.1` to `3.6.2` or `3` to `5`. In the latter case I will use a search engine to look for potential issues I may be facing with an upgrade before deciding whether to progress with the update. With the current output I only see the new version and in many cases won't remember the previous version.

**Comment by rmarquis** [comment]
Already implemented. Please read the man page.
