### ISSUE TITLE
Doesn't "exit 1" if error occurs in pacman

### ISSUE THREAD

**Issue by gabrielsimoes** [rmarquis/pacaur#554]
If I run `pacaur -S archpkg-v2 aurpkg --noconfirm`, having `archpkg-v1` installed, where `archpkg-v1` and `archpkg-v2` are packages from repositories and `aurpkg` is a package from aur, the following occurs: pacaur ignores the conflict error, and proceeds to install `aurpkg`, not returning "exit 1".

Is this the desired behaviour?

**Comment by rmarquis** [comment]
Yes, since the repo and AUR package installation are completely separate in this case.

**Comment by gabrielsimoes** [comment]
In my situation, I'm writing a script which installs a list of packages, both from repositories and the AUR. The script should exit if an error occurs in the installation. However, the current pacaur behaviour tells the script the installation ran fine. If you think this is the desired behaviour, we can then close this issue. If so, are you aware of any workarounds?

**Comment by rmarquis** [comment]
Pacaur isn't designed to be run unattended with --noconfirm.
I'd suggest you to modify the code [here](https://github.com/rmarquis/pacaur/blob/master/pacaur#L1592) to catch the error and do an early exit.
