### ISSUE TITLE
pacaur prompts expect answers in locale language but the prompt does not reflect this!

### ISSUE THREAD

**Issue by WildPenquin** [rmarquis/pacaur#555]
Hi,

Pacaur asks things from me (and this is fine). But the prompt asks in English (with Y/n or y/N) but expects me to answer in Finnish with k/e (short for kyllä=yes and ei=no)! 

Needless to say this can be confusing.

This may have something to do with the fact that my system locale is fi_FI.UTF-8 (and I wish it to remain that way).

**Comment by rmarquis** [comment]
See #436. Closing here as duplicate.
