### ISSUE TITLE
Add pacaur -c to remove packages folder

### ISSUE THREAD

**Issue by terencode** [rmarquis/pacaur#559]
Hello, 
It would be useful to have a new argument like maybe pacaur -c  <package> to be able to remove a package 's folder from pacaur's own cache and also having the option to do it on one being uninstalled.

**Comment by rmarquis** [comment]
Yes, older versions (when still using the old downloaded tarball instead of the git retrieve) were basically doing that. I removed that automation as to not mess with the git diff feature, but there might be a way to readd this cleanly.

**Comment by terencode** [comment]
Ok I didn't know that, I'll look forward to it. 
Thanks.

**Comment by Feirlane** [comment]
I've been using [this](https://github.com/Feirlane/pacaur/commit/b435815f65f49ecb008d1d5645b73946053e9087) for a while.
It removes the files created during build/packaging, keeping only the original files downloaded from the AUR tracked by git.
I can make a pull request if it is welcomed.

**Comment by rmarquis** [comment]
@Feirlane Thanks. This is a good fix for solving #461, but it does not actually solve this ticket. What we need here is a way to remove entire git folder that aren't installed anymore, taking split package into account too.

I am also unsure how to properly implement the two nicely together. Probably as an extension of the `-Scc` command.

**Comment by Feirlane** [comment]
Yeah, I really was thinking more of #461 when I made my comment. 

Maybe git clean should be run automatically after a successful build, and also extend -Scc to delete the git folders of uninstalled packages as two separate features?

**Comment by terencode** [comment]
I would agree.

**Comment by rmarquis** [comment]
Implemented in f92f9bee83bdc7265e3554c811b5aab940ae71b8, as an extension of `-Sc` and `-Scc` to remove uninstalled and all clones, respectively.

As for #461, I am unsure about automatic cleaning after a successful build. This isn't what makepkg does, and users that haven't configured `PKGDEST` or `SRCDEST` expect the source and build files to be there.

Closing this issue, please comment of #461 if needed.
