### ISSUE TITLE
Allow installing packages as root

### ISSUE THREAD

**Issue by JelteF** [rmarquis/pacaur#561]
I've just installed pacaur, and the first thing I noticed was that I had to call the program using my own user instead of using root. I appreciate it works with my normal user, but why is there no support for installing using root. 

I imagine that it is because you do not want to run the PKGBUILD scripts as root, but this can easily be done when started as root by changing to a special `pacaur` user. If this user is created with very little privileges (e.g. only access to /tmp), then this should be even more secure then when run from a regular user.

**Comment by rmarquis** [comment]
Seriously, this again? No.
