### ISSUE TITLE
.SRCINFO problem while installing sic

### ISSUE THREAD

**Issue by wheatdog** [rmarquis/pacaur#562]
```
:: sic package(s) failed to install. Check .SRCINFO for mismatching data with PKGBUILD.
```

However, I think that .SRCINFO matches the PKGBUILD. Even if I use ```mksrcinfo``` to generate new .SRCINFO, it still complains the same issue. I tried ```yaourt```, and it can install ```sic```.

**Comment by rmarquis** [comment]
The .SRCINFO is indeed mismatching.
Yaourt does not rely on the RPC.

**Comment by v1kn** [comment]
I am getting the same error while trying to install `pacli`. 
 May I ask why the issue is closed and labeled as invalid? Does it mean the error is due to packaging in the AUR and not fixable through `pacaur`?

**Comment by rmarquis** [comment]
> Does it mean the error is due to packaging in the AUR and not fixable through pacaur?

Obviously.
