### ISSUE TITLE
pacaur -Scc should offer to clear pacaur cache

### ISSUE THREAD

**Issue by rightaway** [rmarquis/pacaur#566]
`pacaur -Scc` should offer to clear out `~/.cache/pacaur`, just like the equivalent pacman command does for its cache.

**Comment by rmarquis** [comment]
Closing as duplicate.

**Comment by rightaway** [comment]
Which issue does it duplicate? I did a search before creating it and again now but haven't found anything.

**Comment by rmarquis** [comment]
#559 right below.
