### ISSUE TITLE
need workaround for removal of pacman contrib

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#569]
The pacman-contrib utils are getting [removed](https://lists.archlinux.org/pipermail/pacman-dev/2016-October/021533.html) and won't be part of the pacman package anymore.

Pacaur makes use of paccache (see #34 and #479), so it might be wise to get back to inhouse code.

I'm a bit surprised by the removal of the tools upstream, as pacdiff is the defacto standard tool to merge pac files.

**Comment by ChuckDaniels87** [comment]
Are they releasing another separate package with those utils?

**Comment by rmarquis** [comment]
Probably.

**Comment by rmarquis** [comment]
Alternatively, simply remove the actual code and enforce usage of an additional `CacheDir` entry. Code for better compatibility had been added in b61c3edcb360e11134f9a840e0ff268bda371ba9, but current code effectively duplicates a setting already provided by pacman.

**Comment by AladW** [comment]
pacaur also uses pactree to resolve dependencies. Might be a good excuse to get rid of that inefficient code …

**Comment by rmarquis** [comment]
> pacaur also uses pactree to resolve dependencies. Might be a good excuse to get rid of that inefficient code

This is OT, but at this point I'd be more interested in getting rid of the existing AUR dependency rather than adding a new one. The next step would be to not rely on pacman directly. To be honest, I wouldn't be surprised if the next-gen popular helper will be an easy-to-use interface that leverages all the work achieved by pacutils and aurutils.

**Comment by AladW** [comment]
Having a helper that needs manual setup and reading comprehension is the ideal defense against help vampires, so I'm personally not interested in changing that; but if anyone else is interested, I'm happy to help them out.

Back to pactree -- someone will probably add pacman-contrib to community (I guess that with 24 votes, pacutils would be another candidate), but now that pacaur uses tsort and less curl calls, improving the dependency code would be another (major) step towards performance.

The main step here would be to run `expac` a single time, instead looping over every entry from `pactree`. I used to do something similar at first and fixing it made resolving providers for plasma-desktop-git go from 1+ min to 2 seconds.

pacaur does some more complex things with providers than I do, so I'm not sure on a specific patch. Tabulated output might help though: https://github.com/AladW/aurutils/blob/master/bin/aursift#L64

**Comment by rmarquis** [comment]
Note that pactree is not a pacman contrib file. It's not concerned by the removal patch. But yes, that part might be the biggest bottleneck left in the dependency solver code. I am unsure how to replace it efficiently, but patching patree to work on multiple targets (as expac does) is a possibility.

**Comment by AladW** [comment]
Oh - in that case it might be better to discuss this in a separate issue

**Comment by rmarquis** [comment]
I opened a new issue.

**Comment by rmarquis** [comment]
Removed in 78d9b826f3f9a3ca655d3ebf1e95f46949f1c03c in favour of the `CaheDir` pacman option.
