### ISSUE TITLE
Move /tmp/pacaurtmp-<user> to /run/usr/<userid>?

### ISSUE THREAD

**Issue by ChuckDaniels87** [rmarquis/pacaur#572]
This is just a wild question because I only got a vague idea of this issue. I've found some information that suggesting that is better to create temporal files in `/run/usr` than use `/tmp`. You can check [this answer in StackExchange](http://unix.stackexchange.com/a/162911/152578).

I'm not sure, however, if this directory is also used by init systems different from `systemd`. 

_Edit: I forgot to add the link_

**Comment by rmarquis** [comment]
I'm afraid your Stack Exchange link is missing ;)
The only temp files created are lock files and the temp file used for the info display. By default, `/tmp` is mounted in memory thus very fast, but pacman creates its lock file in `/var/lib/pacman/`.

**Comment by ChuckDaniels87** [comment]
The directory `/run/usr` is also mounted in memory. There is a mount point for each active user:
```
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
tmpfs on /run/user/120 type tmpfs (rw,nosuid,nodev,relatime,size=3277548k,mode=700,uid=120,gid=120)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3277548k,mode=700,uid=1000,gid=100)
```

**Comment by rmarquis** [comment]
In that case, it makes sense to use `/run/usr` for the temp info display file. I am not sure about the lock files though. In case of a multi user system, each pacaur session should be able to check if there is a build occurring.

Granted, this is unlikely (many users with compile/install rights installing at the same time), and is also an existing issue with the current code. I am really not sure where these lock files should be put... maybe moved up to `/tmp` from `/tmp/pacaurtmp-$USER`.

**Comment by ChuckDaniels87** [comment]
Why building a package should be locked system wide? It makes sense to me to only block installation of the package.

**Comment by rmarquis** [comment]
See #300. In a nutshell, mostly for simplicity. Makepkg might call pacman to install packages between builds, and I don't think it is worth it to make pacaur hangs while waiting for the lock to be released.

**Comment by ChuckDaniels87** [comment]
I think there is a good reason then. Actually, the lock could work only on functions that could make a call to `makepkg` or `pacman`. It got no sense to block the whole application because someone is compiling. Other users should be able to query information for example.

To make the lock system-wide just put the file in [`/run/lock`](http://askubuntu.com/a/169526).

**Comment by rmarquis** [comment]
This is already the case. The lock only prevents building. Search, info and check update still work as expected. Even downloading source files with makepkg and the integrity check is working.

Thanks, I'll move the files to /run/lock.

**Comment by rmarquis** [comment]
Done in 5591c6d59f7a8827cc5ce3f1ebc36fe58463a650.
