### ISSUE TITLE
inspect all build files simultaneously with vifm

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#573]
Inspect the possibility of using of `vifm` (or similar tools) as an alternative to standard editors to speed up PKGBUILDs review.

This is implemented in aurutils by @AladW.

**Comment by ChuckDaniels87** [comment]
How does he use it? I've looked his code but it is not clear for me. The file manager `ranger` could also be useful depending on your idea about this feature.

**Comment by AladW** [comment]
Not sure what's not clear exactly but it just uses `find` to get a list of build directories and the files they contain, then passes that to vifm on stdin. The reason for vifm is that it's the only curses file manager that supports stdin. You can do something similar with ranger or mc, but you'd either have create symlinks to all current build files in some temporary directory, or be cluttered with files unrelated to the current operation in AURDEST.

**Comment by rmarquis** [comment]
After having a closer look, I'm kinda skeptical about this feature. On one hand, it's incompatible with the diff viewing feature, on the other hand it's only useful for the vifm utility. I'm still interested in speeding up the review process, but I don't see vifm very relevant here.

Closing as wontfix.

**Comment by AladW** [comment]
FWIW, you can view diffs in vifm by saving them in a temporary folder (at least that's what I do). I can't think of a much better way to not prompt 100 times, but ping me if you do. ;P

**Comment by rmarquis** [comment]
> FWIW, you can view diffs in vifm by saving them in a temporary folder (at least that's what I do).

This sounds ugly to me. The reason I waited AUR 4 before implement the diff feature was exactly for avoiding temp dir and using git directly.

> I can't think of a much better way to not prompt 100 times, but ping me if you do. ;P

Hopefully doesn't happen that often in practice. I can only think of [git submodule](http://stackoverflow.com/questions/10757091/git-list-of-all-changed-files-including-those-in-submodules) as an alternative but that also sounds overengineered.
