### ISSUE TITLE
improve ZSH completion file

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#574]
The current zsh completion file does autocomplete package names, but pressing tab repeatedly doesn't select anything.

Reported in [bbs](https://bbs.archlinux.org/viewtopic.php?pid=1658623#p1658623).

**Comment by ChuckDaniels87** [comment]
It does work for me but you got to press three times TAB. I think this is not the standard behaviour of ZSH completions. I could try to fix this since I use ZSH on my daily basis.

**Comment by ChuckDaniels87** [comment]
I've been testing the completion and it is working with the exactly the same behaviour as `pacman` zsh-completion. What was the actual issue here?

**Comment by rmarquis** [comment]
See bbs, looks like a real bug to me.

**Comment by ChuckDaniels87** [comment]
I can confirm it. The `-Su` option seems to break the completion selection.

**Comment by ChuckDaniels87** [comment]
I've got some question of completion and `pacaur` in general:
* Why are two colliding options `-r, --repo` and `-r, --root` between `pacman` and `pacaur`?
* Why `-y` is `--sync` in `pacaur` but `--refresh` in `pacman`? `--sync` in `pacman` is supposed to be `-S` option.
* 

I've noticed that `-Ss` option doesn't select anything either, but this is the behaviour also in `pacman`. I'll keep digging in the ZSH completion code. It seem it has been taken from pacman ZSH completion but some stuff seems to be missing.

**Comment by rmarquis** [comment]
Pacaur provides 2 sets of commands. See man page.

**Comment by ChuckDaniels87** [comment]
Ok, I'll fix that in the ZSH completion then since `--root` is also using `-r`. I'll PR a fix for the issue in bbs and this `--root` issue. 

Additionally, I've noticed that there is a lot of room for improvement in the ZSH completion.

**Comment by rmarquis** [comment]
Thanks! I'll close this issue, feel free to send additional improvement if needed.
