### ISSUE TITLE
replace pactree code by more efficient code

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#575]
The repository dependencies are computed with `pactree` in a loop, which is very inefficient speed wise.

>  now that pacaur uses tsort and less curl calls, improving the dependency code would be another (major) step towards performance.
> The main step here would be to run `expac` a single time, instead of looping over every entry from `pactree`. I used to do something similar at first and fixing it made resolving providers for plasma-desktop-git go from 1+ min to 2 seconds.
> 
> pacaur does some more complex things with providers than I do, so I'm not sure on a specific patch. Tabulated output might help though: [aursift#L64](https://github.com/AladW/aurutils/blob/master/bin/aursift#L64)

That part might be the biggest bottleneck left in the dependency solver code. I am unsure how to replace it efficiently, but patching pactree to work on multiple targets (as expac does) is a possibility.

Edit: Fox the context, pacaur computes all the binaries dependencies to retrieve providers, and display all these deps on the main prompt.  Binary dependency installation is entirely handled by makepkg.

(discussion moved from #569)

**Comment by ChuckDaniels87** [comment]
I don't know if it is feasible but you can do only one call to `expac` (using multiple arguments) with all the info retrieved from `pactree`. Then, you can use a efficient tool like `comm` or something like that.

**Comment by rmarquis** [comment]
Don't think that's possible. `pactree` is recursive but can't handle multiple targets at once, `expac` can handle multiple targets but isn't recursive.

**Comment by rmarquis** [comment]
Easiest, cleanest way to fix this is to patch upstream

**Comment by rmarquis** [comment]
Well, pactree has been moved to pacman-contrib since then. See [pacman-dev](https://lists.archlinux.org/pipermail/pacman-dev/2016-October/021623.html) ML.

**Comment by rmarquis** [comment]
Done in c6b7fdb98de063326f6e659f8691197893e4d5a8 while fixing #722.

As a nice bonus, the multi targets feature of expac allows the code to be much faster with many binary deps:

Before:
```
$ time pacaur -S aura
:: Package aura not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (3)                                    Old Version  New Version

aur/aura                                                          1.3.9-2                   
aur/haskell-aur                                                   6.0.0.1-1                 
aur/haskell-servant-client                                        0.11-1                    

Repo Packages (86)                                   Old Version  New Version  Download Size

community/ghc                                                     8.0.2-2          40.59 MiB
...

Repo Download Size:    55.45 MiB
Repo Installed Size:  578.34 MiB

:: Proceed with installation? [Y/n]

real    0m23.381s
user    0m22.107s
sys     0m1.956s
```

Now:

```
$ time pacaur -S aura
:: Package aura not found in repositories, trying AUR...
:: resolving dependencies...
n:: looking for inter-conflicts...

AUR Packages  (3)                                    Old Version  New Version

aur/aura                                                          1.3.9-2                   
aur/haskell-aur                                                   6.0.0.1-1                 
aur/haskell-servant-client                                        0.11-1                    

Repo Packages (86)                                   Old Version  New Version  Download Size

community/ghc                                                     8.0.2-2          40.59 MiB
...

Repo Download Size:    55.45 MiB
Repo Installed Size:  578.34 MiB

:: Proceed with installation? [Y/n]

real    0m8.793s
user    0m7.950s
sys     0m1.183s
```
