### ISSUE TITLE
replace -Qua and -Qur with -Qun and -Qum

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#582]
Following discussion in #580.

Query local packages as the AUR doesn't make sense. Pacaur is built upon pacman/makpekg, not the other way around. True, there is -Qu which checks update against the sync database, so -Qua was added. But if there is something to fix here, that would be to change it to -Qum.

[...] I should replace `-Qur` by `-Qun` (for `--native`) and `-Qua` by `-Qum` (for `--foreign`). The `-Qu` shortcut will still display both, as it is the case as of now.

**Comment by rmarquis** [comment]
See also #584 as the same issue applies here.

**Comment by rmarquis** [comment]
Done in 7b1eb8b92fd7035028dcd596c7acca81dd467e8e.

**Comment by ChuckDaniels87** [comment]
Could these commands receive any argument? I am updating the ZSH completion file.
