### ISSUE TITLE
pacaur somehow exitting chroot/stopping script?

### ISSUE THREAD

**Issue by lilmike** [rmarquis/pacaur#585]
Hi,
I'm trying to debug a script my friend made, kind of like arch ultimate installer, except specifically aimed at the blind using talking arch (https://talkingarch.tk). The first time pacaur is run in the chroot to install needed aur packages like the following:

pacaur -S --needed --noconfirm x y z

or even this:

pacaur -S --needed --noconfirm x
pacaur -S --needed --noconfirm y
pacaur -S --needed --noconfirm z

It makes the script somehow fail, and stop processing the rest of the script. There is no set -e in the bash script, and you can see the current incarnation (the one that exits prematurely) here: https://stormdragon.tk/scripts/vm.sh

Any ideas?
Thanks,
-Michael.
P.S. If it matters (which I don't think it does, but just in case) sudo does not require a password in the script's run.
P.P.S. Pacaur did not used to exhibit this script-killing behavior, I'm honestly not sure when it started doing this but my guess is 6 months ago or so.

**Comment by rmarquis** [comment]
Can't say without debug output. See [Bug-reports](https://github.com/rmarquis/pacaur/wiki/Bug-reports).

**Comment by lilmike** [comment]
Hi,
This is a log with bash -x pacaur -S --needed --noconfirm aurvote &> pacaur.txt

It finished fine, and installed aurvote, but the pacaur commands after were not ran (there were like 9 of them). Oddly, only one more command was run, a sed statement which should have been run waaaaaay after the pacaur commands ended, and actually I think it was the first command after the chroot ended. This seems to me that pacaur is ending the chroot somehow. Log attached.
Thanks,
-Michael.
[pacaur.txt](https://github.com/rmarquis/pacaur/files/536022/pacaur.txt)

**Comment by rmarquis** [comment]
The issue happens [here](https://github.com/rmarquis/pacaur/blob/910116b97dd839e8b12e8b317980e52e5b5abf39/pacaur#L1099), but this code is now deprecated. Please test pacaur-git, my guess is that this issue is already solved in master.

**Comment by rmarquis** [comment]
No response, closing.
