### ISSUE TITLE
Cannot install terminator-gtk3-bzr

### ISSUE THREAD

**Issue by protist** [rmarquis/pacaur#586]
I can't install `terminator-gtk3-bzr` using pacaur 4.6.10-1. I get the following error.

    $ pacaur -S terminator-gtk3-bzr
    ...
    ==> Retrieving sources...
      -> Pulling lp:terminator/gtk3...
    bzr: ERROR: Not a branch: "/home/protist/.cache/pacaur/terminator-gtk3-bzr/terminator-gtk3-bzr/.bzr/branch/": location is a repository.
    ==> WARNING: Failure while pulling lp:terminator/gtk3
    ...

Using `makepkg` manually works fine.

**Comment by rmarquis** [comment]
Works for me. See [Bug-reports](https://github.com/rmarquis/pacaur/wiki/Bug-reports).

**Comment by protist** [comment]
Oh… I deleted the cache at `/home/protist/.cache/pacaur/terminator-gtk3-bzr` and tried gain. This time it worked fine. I don't quite understand how the cache could have been corrupted. Actually, I think I might have run into a similar, slightly cryptic problem before with pacaur. Thanks for the response anyway, and apologies for the noise.
