### ISSUE TITLE
pkgver() only evaluated for vcs packages

### ISSUE THREAD

**Issue by xelra** [rmarquis/pacaur#592]
I've noticed that pacaur doesn't evaluate pkgver() functions before install for non-vcs packages. So it won't report the proper version. This is especially propblematic for updates, because it thinks that the already installed version is newer.
The pkgver() will only be evaluated later and show the right version.

**Comment by rmarquis** [comment]
You comment does not make sense. A non-VCS package has either a correct version or it has not.
Likely, the PKGBUILD is not written correctly or its metadata has not been updated correctly.

**Comment by xelra** [comment]
I've read the wiki and the PKGBUILD man and everything related over and over. Nowhere does it state that `pkgver()` functions are exclusive to VCS packages.

As far as I can tell it is legit to automatically bump the version and source file with a `pkgver()` in your `PKGBUILD` even if it isn't VCS.

**Comment by rmarquis** [comment]
Then you are missing common sense. In the [wiki](https://wiki.archlinux.org/index.php/PKGBUILD#pkgver), the pkgver() is explicitly detailed as a [VCS package guidelines](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function) directive. And really, common sense.

**Comment by xelra** [comment]
`makepkg` accepts pkgver() functions also for non-vcs packages. The [man](https://www.archlinux.org/pacman/PKGBUILD.5.html) states vcs as optional:

> The pkgver variable can be automatically updated by providing a pkgver() function in the PKGBUILD that outputs the new package version. This is run after downloading and extracting the sources so it can use those files in determining the new pkgver. This is most useful when used with sources from version control systems (see below).

On [the creating packages wiki page](https://wiki.archlinux.org/index.php/creating_packages#pkgver.28.29) it states:

> Beginning with pacman 4.1, you can update the pkgver variable during a makepkg. pkgver() is run right after the sources are fetched and extracted.
This is particularly useful if you are making git/svn/hg/etc. packages, where the build process may remain the same, but the source could be updated every day, even every hour. [...]

Also here it doesn't say anything about vcs being mandatory. It only recommends that it is particularly useful for vcs packages.

I don't see any reason why a package should need manual intervention for every version, if the `PKGBUILD` never changes, only because it isn't one of the official vcs types.

If I download the package, `makepkg` behaves exactly as expected. The only thing that doesn't support this are the helpers.

**Comment by rmarquis** [comment]
Look, I'm not interested in supporting user cases that are far fetched when a simpler, cleaner way to achieve the same result exists and is widely used everywhere else.
