### ISSUE TITLE
Clean $AURDEST cache of uninstalled packages

### ISSUE THREAD

**Issue by Markus00000** [rmarquis/pacaur#593]
###### Description

Pacaur could allow cleaning `$AURDEST` of uninstalled packages. The man page only mentions how `-Sc` and `-Scc` apply to `$PKGDEST` and `$SRCDEST`.

I am using this script to clean the caches of uninstalled packages:

    #!/bin/bash
    
    cd ~/.cache/pacaur/ || exit
    
    for pkg in *; do
        pacman -Qi "$pkg" &> /dev/null || (rm -rf "$pkg" && echo "Pacaur cache removed for $pkg")
    done

Obviously the cache directory would have to be selected properly in case it’s somewhere else.

**Comment by rmarquis** [comment]
Already implemented.
