### ISSUE TITLE
Source pacaur configuration before setting up environment variables

### ISSUE THREAD

**Issue by Edenhofer** [rmarquis/pacaur#595]
I would suggest setting up `clonedir` and `pacmanbin` after sourcing the pacaur configuration ([line 63](https://github.com/rmarquis/pacaur/blob/master/pacaur#L63)). This would enable users to specify preferences in the configuration file instead writing bash aliases.

**Comment by rmarquis** [comment]
This is already possible by defining `clonedir` and `pacmanbin` in the config directory. What did I miss here?

**Comment by Edenhofer** [comment]
Please disregard this stupid bug report. Apparently I forgot how bash works. Sorry!
