### ISSUE TITLE
Edits to PKGBUILD are ignored afterwards

### ISSUE THREAD

**Issue by stevenroose** [rmarquis/pacaur#601]
###### Version

`pacaur -v`

```
pacaur 4.6.10
```

###### Description

The edits I make to PKGBUILD are ignored. I correctly save them with `:wq`.

###### Debug output

`bash -x pacaur -S -e devilspie2`

https://gist.github.com/stevenroose/db24e93494633fd4a5cda69776a6222e

I replace the signature with `SKIP`.

**Comment by rmarquis** [comment]
You can't 'skip' signature.

**Comment by stevenroose** [comment]
@rmarquis I also tried removing the signatures line..

**Comment by rmarquis** [comment]
Please try with makepkg before ruling this issue out as a pacaur bug.

Also, the GPG signature is fine. It is you that hasn't configured your system correctly.
