### ISSUE TITLE
No prompt for authentication when using fprintd for sudo

### ISSUE THREAD

**Issue by ilario** [rmarquis/pacaur#604]
###### Version

```
$ pacaur -v
pacaur 4.6.10
```

###### Description

If `fprintd` is used for sudo authentication via fingerprint reader, in pacaur the expected "Swipe your finger across the fingerprint reader" doesn't appear. The terminal after downloading the source just stays silent waiting for the finger to be swiped.

###### Example
```
pacaur -S ttf-ms-fonts
:: Package(s) ttf-ms-fonts not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1) ttf-ms-fonts-2.0-10  

:: Proceed with installation? [Y/n] 

:: Retrieving package(s)...
:: ttf-ms-fonts build files are up-to-date -- skipping
```

and no text for indicating that sudo is expecting a fingerprint is prompted.

**Comment by rmarquis** [comment]
I have no idea how fingerprint readers work with sudo, nor do I have a mean to test this functionality. You'll have to provide a patch here.

**Comment by ilario** [comment]
Ok, I will try...

**Comment by ilario** [comment]
So, the problem is that the string asking to swipe the finger from fprintd is in STDOUT which is redirected to /dev/null in pacaur in [this line](https://github.com/rmarquis/pacaur/blob/master/pacaur#L998):
```
if sudo $pacmanbin -V > /dev/null; then
```
From my understanding this line is used for getting the sudo rights.
The same can be obtained with the following:
```
if sudo -v; then
```
If there's a need for checking the existence of pacman executable also, the line can be this one:
```
if $pacmanbin -V > /dev/null && sudo -v; then
```
Let me know and I can make a pull request.

**Comment by rmarquis** [comment]
Yes please, a patch is warmly welcome here. See issue #418 for the reason of the change done in commit b811d43e2f9f62f1646c42be2f38a5661c9a29e7.

**Comment by rmarquis** [comment]
@ilario: Any news on this?

**Comment by ilario** [comment]
No, do you have some hint about how to solve?

**Comment by rmarquis** [comment]
You have to ensure that your patch works for you and doesn't break with any of the following sudo configuration (see #418):

* %wheel ALL=(ALL) ALL
* %wheel ALL=(ALL) NOPASSWD: ALL
* %wheel ALL=(ALL) NOPASSWD: /usr/bin/pacman

**Comment by ilario** [comment]
Yep, that's the problem...

**Comment by ilario** [comment]
I noticed the `-n` option in sudo, this allows to solve :)
