### ISSUE TITLE
Pass flags to makepkg

### ISSUE THREAD

**Issue by mabbamOG** [rmarquis/pacaur#610]
###### Version

`pacaur -v`

```
pacaur 4.6.10
```

###### Description

On archlinux-arm, if a package is not in the repos, it needs to be recompiled.
It's only natural to compile from the AUR, but often arm is not a supported architecture, that's why we take our chances and use makepkg -A.
Pacaur is helpful in many ways, especially when pulling in many AUR dependencies, but i cannot find a way to force the -A flag for makepkg.

###### Output

`pacaur -S <whatever>`

```
architecture not supported something..
```

**Comment by rmarquis** [comment]
I'm not supporting any unofficial architecture. A patch/fork is in order.

**Comment by mabbamOG** [comment]
what? you already use makepkg, all i'd like is to be able to pass the official -A flag to the program you already support. there's not much to patch..

**Comment by rmarquis** [comment]
Out of scope of this project. Absolutely no support is provided, unless you are ready to pay for it.

**Comment by mabbamOG** [comment]
This project is about the aur, and it uses makepkg like it should. This is a makepkg flag, there is no support to be needed, the flag speaks for itself.

I believe arm users could benefit from the "recursive install" capabilities of pacaur, but this isn't only about arm, it's basically about packages that are wrongly configured... the flag is there for a reason after all, it shouldn't be a tragedy for pacaur to expose it.

**Comment by ImNtReal** [comment]
Try `makeopts="-A" pacaur -S `

**Comment by mabbamOG** [comment]
yep :)
