### ISSUE TITLE
Prompt to continue build after viewing PKGBUILD

### ISSUE THREAD

**Issue by zyklotomic** [rmarquis/pacaur#611]
```Unpacking objects: 100% (4/4), done.
:: View vim-pathogen PKGBUILD? [Y/n] 
:: vim-pathogen PKGBUILD viewed
:: Checking vim-pathogen integrity...
```
pacaur doesn't prompt whether I want to continue with the build after reading the PKGBUILD. It continues with the build process as soon as you view the PKGBUILD. 

Shouldn't the default behavior be prompting you as to whether to continue with the installation  since the PKGBUILD could be bad? 

What I think should actually happen
```
Unpacking objects: 100% (4/4), done.
:: View vim-pathogen PKGBUILD? [Y/n] 
:: Continue? [Y/n]
:: vim-pathogen PKGBUILD viewed
:: Checking vim-pathogen integrity...
```

Am I missing something? I mean, yes you can `^C` but I think this should be default behavior? Not sure how everyone else thinks about this.

**Comment by rmarquis** [comment]
See #472.
