### ISSUE TITLE
Pacaur doesn't let me edit pkgbuild due to missing dependency

### ISSUE THREAD

**Issue by Hund** [rmarquis/pacaur#614]
I tried to install a package with Pacaur, but it failed due to missing dependency (version mismatch), so I added the `--edit` flag so I could change the version number myself, but it don't let me get that far due missing dependency.

The package I want to install has a lot of decencies and I really don't want to download them manually and build them all by myself one at the time.

I don't think Pacaur should check for decencies before the `--edit` flag.

**Comment by rmarquis** [comment]
Unlike most other helpers, pacaur uses the RPC to solve the dependencies instead of parsing PKGBUILDs. This is done *before* the PKGUILDs are even downloaded. You should report the issue upstream, and in the meantime you can tinker with cower to manually fix the issue.
