### ISSUE TITLE
Does not update version number for packages with pkgver() function

### ISSUE THREAD

**Issue by samcv** [rmarquis/pacaur#618]
###### Version

``` Pacman v5.0.1 - libalpm v10.0.1```

Package atom-editor-beta-bin has a pkgver() function. Building using makepkg correctly updates the version number based on the pkgver function, but pacaur does not.

**Comment by rmarquis** [comment]
Seems you fixed the issue in the last update. Cannot reproduce for now, so cannot debug. Please reopen when the issue arise again.

**Comment by samcv** [comment]
Is there a way for pacaur to install a package from local files instead of the AUR? If so I can provide files to reproduce the problem.

**Comment by rmarquis** [comment]
It relies on the RPC, so no.

**Comment by samcv** [comment]
Upstream has updated the file @rmarquis if you can check now. Installing it downloads 1.14.0.beta1, but it installs as version 1.14.0.beta0-1

**Comment by rmarquis** [comment]
The metadata of the RPC indicates `1.14.0.beta0-1`... But I see what you did here. You're avoiding to update the PKGBUILD yourself by allowing new installation to be correct, but you're never changing the PKGBUILD/.SRCINFO files. How do you expect users to receive notification of new version?

This breaks *all* helpers which will not be able to update the package automatically.

**Comment by samcv** [comment]
What about the packages that rely on git for versioning information? Those use a pkgver() function in the PKGBUILD to update the info and those seem to work fine

**Comment by samcv** [comment]
If there is a way I can designate that this package should be checked for version similarly to how the git ones are, let me know.

**Comment by rmarquis** [comment]
The VCS packages (-git, -svn, ..) rely on a special handling based on their naming scheme. Most if not all helpers that implement `--devel` check the package names. This is quite inefficient, so it should be passed explicitly.

Here, you should simply adjust the PKGBUILD manually when out of date, instead of breaking the workflow the AUR was designed for.

**Comment by samcv** [comment]
Okay I understand. Though I still think it is an issue that it does not update the package version number when installing the package. makepkg works fine and updates the version number. Could pacaur just check if it had a function called pkgver and if so call that to get the package version, which is what makepkg does?

**Comment by rmarquis** [comment]
> Though I still think it is an issue that it does not update the package version number when installing the package

Yes, but that is a known issue which cannot be fixed without patching `makpekg` with broken code, which I won't do. The issue doesn't normally arise, unless the metadata provided in the .SRCINFO file is obsolete, which is exactly what's happening here.

Overall, this is not a bug, and there is nothing to fix in pacaur.
