### ISSUE TITLE
[feature request] Allow diff of PKGBUILD and .install file to quickly verify these files

### ISSUE THREAD

**Issue by mindstormer12** [rmarquis/pacaur#621]
When pacaur prompts for asking whether or not you want to view PKGBUILD and .install file, if you choose yes (as you should to ensure these aren't doing anything malicious), then a feature to automatically `diff` it with the PKGBUILD and install file of the previous file to quickly see what has changed would be useful. Assuming you have already checked the previous PKGBUILD/.install file to confirm that it's safe, you only have to inspect the differences of the newer PKGBUILD and .install file to verify that these files are safe, as opposed to inspecting each and every PKGBUILD/.install file from top to bottom.

If this feature is not desired in pacaur, please propose a similar way to easily inspect these files. Do you use a script to do something similar that you may share?

**Comment by rmarquis** [comment]
Already implemented. Read man page.
