### ISSUE TITLE
Pacaur should remember which up-to-date build files have been modified by the user

### ISSUE THREAD

**Issue by guiniol** [rmarquis/pacaur#625]
I have a few devel packages for which I use slightly modified PKGBUILDs.
The first time I install them, pacaur proposes the modify the PKGBUILD, but for the subsequent updates, the build files stay the same (because they are devel packages) and so pacaur doesn't ask me if I want to modify them again. Since I modified the PKGBUILDs the first time, I was expecting pacaur to show them to me for modification again (or to store the modification).
Is it me using pacaur in ways it wasn't intended? Is there an option I missed? (I only started using it last week)

Cheers

**Comment by rmarquis** [comment]
> Is it me using pacaur in ways it wasn't intended?

Yes. There are lots of edge cases when modifying PKGBUILDs in an automated way, and this is a can of worms I don't really want to open. Pacaur is designed to be used with PKGBUILD in the state provided by the upstream maintainer.

See also #12, specifically the last couple of posts. I'm closing this issue now, but feel free to discuss that issue in #12.

**Comment by guiniol** [comment]
Thanks for the link to #12
