### ISSUE TITLE
Caching on failed to verify a package integrit

### ISSUE THREAD

**Issue by GZep** [rmarquis/pacaur#635]
I'm getting error on a package which one is already fixed, but pacaur cached wrong version.
```
failed to verify a %package_name% integrit
```
Pacaur should not cache broken packages.

manual fix is
```
$ rm -rf ~/.cache/pacaur
```

```
$ pacaur --version
pacaur 4.6.10
```

**Comment by rmarquis** [comment]
The fix is manual intervention. Automatic removal of the cache is a bad idea, since you don't know if the file is corrupted, or if the PKGBUILD is faulty.

Latest code expended `-Scca` to remove all downloaded sources (if `SRCDEST` is defined) and all clone cache.

**Comment by GZep** [comment]
> Automatic removal of the package cache is a bad idea
I meant to say, is there a solution where a cache is do not need to be created.
> you don't know if the file is corrupted, or if the PKGBUILD is faulty
Okay, that makes sense.

Thanks.

**Comment by rmarquis** [comment]
No, using common sense and manual intervention or using `-Scc` is the way to go here.
