### ISSUE TITLE
What sudo rights are really needed ?

### ISSUE THREAD

**Issue by rfnx** [rmarquis/pacaur#639]
###### Version

```
pacaur 4.7.1
```

###### Description

Hello, since latest version (4.7.1), everytime pacaur builds something from AUR I have sudo errors in my logs : 

###### Output

```
command not allowed ; TTY=pts/1 ; PWD=/home/xxx/.cache/pacaur/mariadb-connector-c ; USER=root ; COMMAND=/usr/bin/touch /run/lock/pacaur.build.lck
```

```
command not allowed ; TTY=pts/1 ; PWD=/home/xxx/.cache/pacaur/mariadb-connector-c ; USER=root ; COMMAND=/usr/bin/rm /run/lock/pacaur.build.lck
```

In the pacaur documentation, it is said : "sudo should be configured accordingly to allow sudo access". But it is not clear what command we should allow. Before pacaur 4.7.1, I only allowed /usr/bin/pacman to run as root and everything was fine, but now I have these errors.

So my questions are : 
**Can we have a full list of command to allow in sudoers ?
Also, is there something I need to do manually because of these errors (like cleaning) ?**

Thanks for all your work !

**Comment by rfnx** [comment]
So is it a problem with my configuration or with pacaur ?

**Comment by rmarquis** [comment]
It's you that doesn't read error message...

I'll revert the lock file to its previous location, user complaints aren't worth it.

**Comment by rfnx** [comment]
What the hell is wrong with you, why are you so aggressive hahaha ? Take a chill pill and learn how to interact with people, please.

I read error messages, but because I didn't get them before I wanted to know if the behaviour was intended. Of course, in the meantime, I added the commands to sudoers and I have no error, but that seems weird and it is not documented.

As you said, maybe the choice of the new location was just bad ?

**Comment by rmarquis** [comment]
> What the hell is wrong with you, why are you so aggressive hahaha ? Take a chill pill and learn how to interact with people, please.

Multiply newbie behavior by hundred times, and maybe, maybe you might understand why I'm fed up with people asking *question* instead of using *common sense*. This isn't a forum.

**Comment by rfnx** [comment]
My questions were legit and I, basically, just asked for a clarification in the documentation about a new behaviour. What is wrong with this ? It is a legit issue.

I already know I can add touch and rm to sudoers, but my question was : is it normal ? Because when you use a program for a long time, changes like this, **about how sudo is used**, (and undocumented) seem weird.

Also, I worked for IT support so I know what it is, and clearly here the problem is not me, it is just your bad aggressive and stupid behaviour.

Regards.

**Comment by rmarquis** [comment]
You're joining the ignore list, I have no time to deal with stupid users.
