### ISSUE TITLE
Error messages on docker instance because of missing /run directory

### ISSUE THREAD

**Issue by nbars** [rmarquis/pacaur#650]
###### Version
```
[jenkins@3f48927aac4f ~]$ pacaur -v
pacaur 4.7.2
```

###### Description
Error messages on docker instance because of missing /run directory.
The build doesn't fail, but it would be nice if these messages wouldn't
be printed.

###### Output
e.g.
```
pacaur -S cutecom
```

```
...
touch: cannot touch '/run/user/1000/pacaur.build.lck': No such file or directory
...
rm: cannot remove '/run/user/1000/pacaur.build.lck': No such file or directory
```

**Comment by rmarquis** [comment]
This is already fixed in current master. The code now uses `${XDG_RUNTIME_DIR:-/tmp}` instead of hardcoded `/run/user`, so `/tmp` will be used as fallback. See fa98859f515c1202f702ba9504187e15ca307d98.
