### ISSUE TITLE
pacaur -Dk Claims it Needs Targets

### ISSUE THREAD

**Issue by DeedleFake** [rmarquis/pacaur#658]
###### Version

`pacaur -v`

```
pacaur 4.7.4
```

###### Description

Running `pacaur -Dk` or `pacuar -Dkk` fails with the output

    :: no targets specified (use -h for help)

**Comment by rmarquis** [comment]
Indeed, thx for the report.

**Comment by rmarquis** [comment]
Fixed in e7c6ab3a30e1298a469f2e1f884f274b1a248b27.
