### ISSUE TITLE
List installed AUR packages with '-a -Qs'

### ISSUE THREAD

**Issue by physkets** [rmarquis/pacaur#659]
###### Version

```
pacaur 4.7.5
```

###### Description

The options `-Qs` list all the installed packages. It would be nice if, in keeping with the usages of `-a` and `-r` in other contexts, they could also be used here, to list installed AUR and regular packages, respectively.

###### Output

`pacaur -a -Qs`

{this lists all currently installed packages}

###### Debug output

`bash -x pacaur -a -Qs`

```
{the list of installed packages}
+ exit
```

**Comment by rmarquis** [comment]
Use `-m` and `-n`, for `--foreign` and `--native` as done by pacman. You also do not need `-s`, just `-Qm` or `-Qn`.
