### ISSUE TITLE
[feature] Non-interactive mode for mass rebuild.

### ISSUE THREAD

**Issue by bartoszek** [rmarquis/pacaur#669]
I was going to rewrite my AUR testing script to make it `pacaur` one-liner.
I get to this:
`ok=(); fail=();cower -m bartus --format "%n\n"|while read pkg; do cmd="BUILDDIR=/tmp/pacaur pacaur --noedit -m $pkg && ok+=($pkg) || fail+=($pkg);" ; echo $cmd ; eval $cmd ; done ; echo pkg_ok=${ok[@]} ; echo pkg_fail=${fail[@]};`
Sadly didn't work as expected. First package build ok but second one gets it name truncate by one character. Which get 'eaten' by `read -r -n 1 answer` in _Proceed with download_ prompt.

And here is my wish: Can we skip prompts with switch similar to `--noedit` to allow unsupervised pacaur operation inside rebuild scripts. 

For now I use `yes|pacaur ...` to resolve the issue - but still think there could be a dedicated switch for that.

**Comment by rmarquis** [comment]
`--noedit --noconfirm`.
