### ISSUE TITLE
Package not updated when it should?

### ISSUE THREAD

**Issue by martinrotter** [rmarquis/pacaur#674]
##### Version
Latest from AUR. as of today (24. 3. 2017).

###### Description
1. Let's suppose I usually update "git" AUR packages with `pacaur -Syua --devel --needed`. Let's say I have package XYZ and new commits land in its Git repo.
2. I hit previous command, new commits get git-pulled and make runs, compilation is in progress.
3. I abort compilation when it is running, thus new version does not get installed.
4. I hit previous command again.

###### Expected result
The package should compile as newest version is not installed.

###### Actual result
Pacaur does not find new commits and does not install new version.

**Comment by rmarquis** [comment]
Cannot reproduce.

**Comment by martinrotter** [comment]
Will try asap.

**Comment by rmarquis** [comment]
No response, closing.
