### ISSUE TITLE
Segmentation fault      (core dumped) cower ${coweropts[@]} -- $@

### ISSUE THREAD

**Issue by gps1539** [rmarquis/pacaur#675]
###### Version

pacaur 4.7.6
```
/usr/bin/pacaur: line 1336: 20019 Segmentation fault      (core dumped) cower ${coweropts[@]} -- $@


###### Description

hitting a seg fault with the -Ss options

segfault maybe from cower

###### Output

pacaur -Ss foobar

/usr/bin/pacaur: line 1336: 20019 Segmentation fault      (core dumped) cower ${coweropts[@]} -- $@


###### Debug output

`bash -x pacaur <your command>`

```
 bash -x pacaur -Ss foobar
+ version=4.7.6
+ unset aur cleancache devel edit info installpkg foreign needed noconfirm nodeps noedit
+ unset operation pac pacQ pacS quiet rebuild refresh repo search selective upgrade
+ LC_COLLATE=C
+ TEXTDOMAIN=pacaur
+ TEXTDOMAINDIR=/usr/share/locale
+ [[ -n '' ]]
+ configdir=/etc/xdg/pacaur
+ userconfigdir=/home/grahams/.config/pacaur
+ userpacmandir=/home/grahams/.config/pacman
+ usercachedir=/home/grahams/.cache/pacaur
+ tmpdir=/run/user/1000
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -r '' ]]
+ source /etc/makepkg.conf
++ DLAGENTS=('ftp::/usr/bin/curl -fC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u' 'http::/usr/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u' 'https::/usr/bin/curl -fLC - --retry 3 --retry-delay 3 -o %o %u' 'rsync::/usr/bin/rsync --no-motd -z %u %o' 'scp::/usr/bin/scp -C %u %o')
++ VCSCLIENTS=('bzr::bzr' 'git::git' 'hg::mercurial' 'svn::subversion')
++ CARCH=x86_64
++ CHOST=x86_64-pc-linux-gnu
++ CPPFLAGS=-D_FORTIFY_SOURCE=2
++ CFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong'
++ CXXFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong'
++ LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro
++ DEBUG_CFLAGS='-g -fvar-tracking-assignments'
++ DEBUG_CXXFLAGS='-g -fvar-tracking-assignments'
++ BUILDENV=(!distcc color !ccache check !sign)
++ OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !optipng !upx !debug)
++ INTEGRITY_CHECK=(md5)
++ STRIP_BINARIES=--strip-all
++ STRIP_SHARED=--strip-unneeded
++ STRIP_STATIC=--strip-debug
++ MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
++ DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc})
++ PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
++ COMPRESSGZ=(gzip -c -f -n)
++ COMPRESSBZ2=(bzip2 -c -f)
++ COMPRESSXZ=(xz -c -z -)
++ COMPRESSLRZ=(lrzip -q)
++ COMPRESSLZO=(lzop -q)
++ COMPRESSZ=(compress -c -f)
++ PKGEXT=.pkg.tar.xz
++ SRCEXT=.src.tar.gz
+ [[ -r /home/grahams/.config/pacman/makepkg.conf ]]
+ [[ -r /home/grahams/.makepkg.conf ]]
+ PKGDEST=
+ SRCDEST=
+ SRCPKGDEST=
+ LOGDEST=
+ BUILDDIR=
+ PKGEXT=.pkg.tar.xz
+ SRCEXT=.src.tar.gz
+ GPGKEY=
+ PACKAGER=
+ CARCH=x86_64
+ editor=vi
+ displaybuildfiles=diff
+ fallback=true
+ silent=false
+ sortby=popularity
+ sortorder=descending
+ sudoloop=true
+ pacmanbin=pacman
+ clonedir=/home/grahams/.cache/pacaur
+ aururl=aur.archlinux.org
+ aurrpc='/rpc.php?type=info&v=5'
+ source /etc/xdg/pacaur/config
+ [[ -r /home/grahams/.config/pacaur/config ]]
+ [[ ! -d /home/grahams/.cache/pacaur ]]
+ declare -A jsoncache
+ trap Cancel INT
+ args=($@)
+ for i in "${args[@]}"
+ [[ -Ss =~ ^-[a-zA-Z0-9] ]]
+ opts+=($i)
+ for i in "${args[@]}"
+ [[ foobar =~ ^-[a-zA-Z0-9] ]]
+ count=0
+ [[ -n -Ss ]]
+ getopts sidmykufecqrahvxVDFQRSTUbglnoptw-: OPT
+ pacmanarg+=("-$OPT")
+ case "$OPT" in
+ pacS=1
+ operation=sync
+ [[ -Ss =~ w ]]
+ installpkg=true
+ [[ -Ss =~ g ]]
+ [[ -Ss =~ l ]]
+ [[ -Ss =~ p ]]
+ getopts sidmykufecqrahvxVDFQRSTUbglnoptw-: OPT
+ pacmanarg+=("-$OPT")
+ case "$OPT" in
+ [[ -n 1 ]]
+ operation=sync
+ search=true
+ coweropts+=("-s")
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n 1 ]]
+ continue
+ getopts sidmykufecqrahvxVDFQRSTUbglnoptw-: OPT
+ [[ -z foobar ]]
+ pkgs+=("${!OPTIND}")
+ shift 2
+ OPTIND=1
+ [[ -n '' ]]
++ grep '^Color' /etc/pacman.conf
+ [[ -n '' ]]
++ grep '^Color' /etc/pacman.conf
+ [[ -z '' ]]
+ [[ '' = \a\l\w\a\y\s ]]
+ [[ '' = \a\u\t\o ]]
+ [[ '' != \a\l\w\a\y\s ]]
+ [[ '' != \a\u\t\o ]]
+ makeopts+=("--nocolor")
+ pacmanarg=(${pacmanarg[@]/--/})
+ pacmanarg=(${pacmanarg[@]/-r/})
+ pacmanarg=(${pacmanarg[@]/-a/})
+ [[ sync = sync ]]
+ [[ ! -n true ]]
+ [[ -n 1 ]]
+ pacmanarg=(${pacmanarg[@]/-e/})
+ [[ -n 1 ]]
+ [[ -n true ]]
+ [[ -n '' ]]
+ [[ -n 1 ]]
+ [[ -n '' ]]
++ command -v vi
+ [[ ! -n /usr/bin/vi ]]
+ [[ ! -w /home/grahams/.cache/pacaur ]]
+ [[ -z foobar ]]
+ [[ -z foobar ]]
+ [[ -n '' ]]
+ case $operation in
+ [[ -n true ]]
+ [[ ! -n '' ]]
+ [[ -n '' ]]
+ pacman -S -s -- foobar
+ exitrepo=1
+ [[ ! -n '' ]]
+ [[ true = true ]]
+ SearchAur foobar
++ grep -E '\-\-[r]?sort'
+ [[ -z '' ]]
+ [[ descending = descending ]]
+ coweropts+=("--rsort=$sortby")
+ cower -s --rsort=popularity -- foobar
/usr/bin/pacaur: line 1336: 20138 Segmentation fault      (core dumped) cower ${coweropts[@]} -- $@
+ exitaur=139
+ [[ -n 1 ]]
+ [[ -n 139 ]]
+ [[ 1 -eq 0 ]]
+ [[ 139 -eq 0 ]]
+ exit 1

```

**Comment by rmarquis** [comment]
Redirect your request to cower tracker,
