### ISSUE TITLE
pacaur should validate gpg signatures itself

### ISSUE THREAD

**Issue by CyberShadow** [rmarquis/pacaur#680]
1. Create a private GPG store
2. For each key listed in packages' `validgpgkeys`, grab the key from some common keyservers and sign it
3. Pass `GNUPGHOME` in `makepkg`'s environment when building the package.

I've implemented this in aconfmgr: https://github.com/CyberShadow/aconfmgr/blob/c680de40d03a65127b1f045aa894c6dfd8d6fbc8/src/common.bash#L606-L654

Any reason not to do this?

The GPG key signatures are already obtained from a source that's as trustworthy as the package itself, so I don't think there's any security degradation.

I could argue that forcing users to add keys to their local GPG store just for the sake of building AUR packages is harmful, since it establishes a global trust relation between the signer when the user just wants to download/build some software. Since anyone can publish an AUR package, someone could create an otherwise-benign AUR package whose only purpose is to contaminate users' GPG stores. So, I think AUR helpers should perform GPG validation themselves when possible, using a private GPG store.

**Comment by rmarquis** [comment]
> The GPG key signatures are already obtained from a source that's as trustworthy as the package itself, so I don't think there's any security degradation.

If that is the case, then makepkg should validate the key by itself. Or alternatively, this above statement is wrong. It is not the signature signing that is important by itself, but the fact that you trust that specific key.

You can argue rightly that users might trust random keys, but this is not an obligation, just stupid users behaviour.

Validating keys is not the responsibility of a semi-automated script. What could be done instead is implementing some form of trust management (see bauerbill), but I do not plan to work on this any time soon.

**Comment by CyberShadow** [comment]
> Validating keys is not the responsibility of a semi-automated script.

Why is that? The key signatures are in the PKGBUILD, I don't see why we can't treat this any differently than a hash check.

**Comment by CyberShadow** [comment]
> It is not the signature signing that is important by itself, but the fact that you trust that specific key.

Not a problem if pacaur creates a temporary GPG store for each package. This does not establish any trust relationships, just checks the file validity.

**Comment by rmarquis** [comment]
You can already automate the verification part with makepkg + GnuPG (see wiki), but pacaur won't circumvent trust management.

**Comment by CyberShadow** [comment]
Right, I'm saying that it would be useful to automate importing the keys as well.

**Comment by CyberShadow** [comment]
@rmarquis So, did you close this because you don't want to implement this yourself or you're against the idea? If it's the former, a pull request should not be too hard.

I've thought about this some more, and I definitely think users shouldn't be forced to generate/import a PGP private key just to be able to install AUR packages using pacaur. As it is right now, pacaur can neither validate PGP signatures itself, nor tell makepkg to ignore them (https://github.com/rmarquis/pacaur/issues/151), so users are forced to pollute their personal GPG stores for keys they don't care about, and it's impossible to easily use pacaur fully automatically.

Unless I missed something, I think the last two arguments make for a strong case to consider support for this feature. A way to skip PGP check would be a lesser alternative, however I've seen AUR packages such as [this one](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emacs-lucid), where without the GPG check, the only validity check is via an old and weak hash function (MD5).

**Comment by rmarquis** [comment]
> What could be done instead is implementing some form of trust management (see bauerbill), but I do not plan to work on this any time soon.

I'm not planning to work on this because 1/ I don't need it, 2/ I don't want to implement it on my free time for free.

Not sure what I could add here. I do not consider this an "issue", for the same reason pacaur doesn't include a `--skipchecksums` flag. If users want more control, they simply should use the manual way.
If you believe that importing PGP keys into the user keyring is the issue, then you should discuss this with pacman developers.

**Comment by CyberShadow** [comment]
I don't think we're on the same page here.

> I'm not planning to work on this

I'm not 100% sure what you mean by trust management, but I am sure it's not what I suggested.

> I don't want to implement

Meaning, you'd reject a pull request as well?

> and maintain it

Please, it's like 10-20 lines of code.

> I do not consider this an "issue", for the same reason pacaur doesn't include a `--skipchecksums` flag.

I don't understand how that follows.

> If users want more control

This is definitely not about control, but the opposite - abstracting away the minutae. Again, I'm not sure I've made my message clear to you.

One of my biggest points of contention in this argument is that pacaur is *very close* to being a tool that's usable by other tools in an automated manner. There exist interesting use cases for fully automatic AUR helpers (aconfmgr being one), so it's a shame that pacaur decides that it doesn't care about this use case because of this relatively minor feature.

**Comment by rmarquis** [comment]
If you want to see what I mean by trust management, see bauerbill that I explicitly mentioned. I don't see a PR based on your above code being merged, as I do believe your solution is poorly thought as it circumvent the upstream design.

Also, yes, I'll reject any pull request of code that I am not willing to maintain on the long term, unless I am paid for it.

> One of my biggest points of contention in this argument is that pacaur is very close to being a tool that's usable by other tools in an automated manner

Pacaur fits my own workflow at 100%, and that is its original purpose. As I suggest in these cases, you're free to adjust the code in your own fork, or use other tools better designed for your own user case.

**Comment by CyberShadow** [comment]
Thanks for the clarification.

**Comment by CyberShadow** [comment]
Found a simple solution which does not require changes to pacaur:

1. Create a directory containing `gpg.conf`, which contains `keyserver-options auto-key-retrieve`.
2. Run `pacaur` with the `GNUPGHOME` environment variable pointing to that directory.

I think this solves the issues above (automation and not polluting user keyring).

**Comment by rmarquis** [comment]
Interesting, thanks for posting this solution!
