### ISSUE TITLE
IgnorePkg of included files are ignored

### ISSUE THREAD

**Issue by steadfasterX** [rmarquis/pacaur#681]
###### Version

```
pacaur 4.7.2
```

###### Description

IgnorePkg gets not fully honored when it is not in the default /etc/pacman.conf file.
You can specify config file includes e.g. for the options stanza:

```
[options]
Include = /etc/pacman.d/autoupdate.conf 
```

Content of  /etc/pacman.d/autoupdate.conf :

`IgnorePkg = relax-and-recover-git thunderbird backintime backintime-cli`

###### Output

`pacaur -k (or pacaur -Quk)`

```
-> it list all packages even those ignored in /etc/pacman-other.conf..
```

###### Debug output

`bash -x pacaur -k`

see here: [log as gist](https://gist.githubusercontent.com/steadfasterX/650bd91c89804cdec47057ca6faa1936/raw/d2dca52b233329334234b0879bea3d5b563becba/pacaur%2520-k%2520)

###### Solution / Code

The following line seems to be the reason for this:

https://github.com/rmarquis/pacaur/blob/master/pacaur#L1602

It only greps on the main config file.

It would be sufficient for me to just be able to choose another config file for parsing like yaourt and pacman offering with the "--config" parameter. If you could add this as a variable instead of the hard coded path to pacman.conf it would be enough in my case..

**Comment by rmarquis** [comment]
Duplicate. See #433.
