### ISSUE TITLE
Notify in case a package has moved to AUR and is being installed from there the first time

### ISSUE THREAD

**Issue by languitar** [rmarquis/pacaur#684]
###### Version

```
pacaur 4.7.6
```

###### Description

The official repositories do not have features to easily track removals of packages. For that reason it sometimes happens that suddenly a package which was in the official repositories before is then suddenly installed from AUR. It would be nice if there was a hint in case this situation first appears so that it is easy to rethink, whether that package is really still needed.

**Comment by rmarquis** [comment]
The required information isn't available anywhere, and I'm strongly opposed to add an external database to track it. I also consider checking `-Qm` output as regular maintenance. As such, this is a won't fix from my side.

Note there is such a warning where  a package is dropped (either official package not moved to AUR, or an AUR package dropped entirely).
