### ISSUE TITLE
AURDEST In userconfig file have no effect

### ISSUE THREAD

**Issue by s-sam** [rmarquis/pacaur#685]
AURDEST variable in user config file have no effect but putting clonedir in user config file have right effect. So readme/pacaur correction needed

look at pacaur file:

line 81:  clonedir="${AURDEST:-$usercachedir}"        # clone directory
line 89: [[ -r "$userconfigdir/config" ]] && source "$userconfigdir/config"

**Comment by rmarquis** [comment]
I do not understand your report. Could you reformulate?
