### ISSUE TITLE
Interface improvements

### ISSUE THREAD

**Issue by cirelli94** [rmarquis/pacaur#691]
When I just started using pacaur I don't catch immediately was the numbers along the package names was, so I think maybe even just a little explanation on the README should be wonderful!
aur/translate-shell 0.9.6.1-1 <!> **(50, 2,31)**

Maybe even explain that the **<!>** is for the package flagged out-of-date!

At the very end, it should be wonderful if we change one of the two comma among votes/popularity:
**(50; 2,31)**
**(50, 2.31)**

This two solutions are even just a bit more readable, don't you think so?
Thanks

**Comment by rmarquis** [comment]
Two things:
* this is cower output, not pacaur's. I'm not the one that can "fix" this.
* The comma format is dependent on your locale; my own output is `(50, 2.31)`.

What are your suggestions to improve the man page? You might want to ask cower 's maintainer to improve its documentation too.
