### ISSUE TITLE
Add IgnoreGroup support

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#693]
Unlike what I previously thought, some AUR packages have groups (f.e. [kodi-addon-pvr-hts](https://aur.archlinux.org/packages/kodi-addon-pvr-hts/) is part of `kodi-addons` group). This information is correctly displayed in the AUR interface, thus it should be handle by pacaur.

Add support for the related IgnoreGroup option.

To do:
- [x] patch cower to retrieve the `Groups` array from the RPC (done)
- [x] implement `Groups` display in the `--info` package info view (0c344dbb81166d736a756b7bebacb8935274a48a)
- [x] implement check for AUR targets that that are part of an `IgnoreGroup` (87c15c2b8b3f60a2df084bf54e7181c974a5a792)
- [x] implement check for AUR packages dependencies that that are part of an `IgnoreGroup` (c8f96c0afa112ee2740500b3c025a99ba2b2b7fc)
- [x] implement check for binary packages dependencies that are part of an `IgnoreGroup` (8c1dabb41a88a939ee7df55d199453a0fbd0107f)
- [x] check multi-group implementation (package that belongs to more than a group) (2130f83e1a2f627dc6c1479067a17f671bc3f308)
- [x] ensure local package take `IgnoreGroup` into account when upgrading (8e474b4709a341ee76cbc56ae54663e7235f848a)

This incidentally overrides the previous decision in #501.
See also #267 as an extra error can be easily trigerred by IgnoreGroup prompt.

**Comment by ChuckDaniels87** [comment]
I'll backport these changes to `pacaur 5.0` when the whole issue is completed.

**Comment by rmarquis** [comment]
Done in above mentionned commits.

**Comment by ChuckDaniels87** [comment]
Backport completed and GetIgnoredGrps() documented.
