### ISSUE TITLE
Problems after using pacman-optimize with the last pacaur update

### ISSUE THREAD

**Issue by Nhoya** [rmarquis/pacaur#694]
###### Version

`pacaur -v`

```
4.7.8
```

###### Description
After using `sudo pacman-optimize` 
`/var/lib/pacman/local/libxrender-0.9.10-1/desc` is `-rw-r--r-- 1 root root 335 25 mar 22.28 /var/lib/pacman/local/libxrender-0.9.10-1/desc` and pacaur is trying to open it every time i need to update or need to  install something, and of course raising a permission denied error

```
sudo ls -lah /var/lib/pacman/local/libxrender-0.9.10-1
totale 92K
d---------    2 root root 4,0K 25 mar 22.28 .
drwxr-xr-x 1358 root root  76K 14 mag 17.03 ..
-rw-r--r--    1 root root  335 25 mar 22.28 desc
-rw-r--r--    1 root root  421 25 mar 22.28 files
-rw-r--r--    1 root root  841  5 ott  2016 mtree
```

I'm not sure if this is and issue relative to last `pacaur` update behaviour or `pacman-optimize` so let me know if this is the wrong place

I fixed the problem manualli giving the permissions to `/var/lib/pacman/local/libxrender-0.9.10-1`

**Comment by rmarquis** [comment]
Not pacaur related.
