### ISSUE TITLE
Pacaur proceeds at prompts, even if input is not yes/no

### ISSUE THREAD

**Issue by three-comrades** [rmarquis/pacaur#696]
###### Version

`pacaur -v`

```
pacaur 4.7.8
```

###### Description

When pacaur prompts for viewing the 'build files diff' or the PKGBUILD (and if I understand the code correctly, also for install scripts) and you enter anything other than `y` or `n`, pacaur accepts the input and proceeds as if `n` was chosen.

###### Expected behavior
When prompted for yes/no and the user answers with something different, I see three possible actions that would make sense to me:
* Ask the question again.
* Abort the program.
* Choose the default value (which I'd expect to be `yes`, if the prompt asks for `Y/n`) 

###### Output

`pacaur -y python-icalendar` 

```
$ pacaur -y python-icalendar
:: resolving dependencies...
:: looking for inter-conflicts...

AUR Packages  (1)     Old Version  New Version

aur/python-icalendar               3.11.4-1                  

:: Proceed with installation? [Y/n] 

:: Retrieving package(s)...
Cloning into 'python-icalendar'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (4/4), done.
:: View python-icalendar PKGBUILD? [Y/n] x
:: Checking python-icalendar integrity...
==> Making package: python-icalendar 3.11.4
[... and so on ...]
```

###### Debug output

`$ bash -x pacaur -y python-icalendar`

Output (cropped after the prompt) see [here](https://gist.github.com/three-comrades/37ddef6c4dd3b6eeb5c556852d2da935)

**Comment by rmarquis** [comment]
This is actually consistent with pacman behavior.

**Comment by three-comrades** [comment]
Can you elaborate where the behavior of pacman is consistent with pacaur? The pacman prompts I just tested (for installation/download and removal) cancel the program for wrong input. But, more importantly, pacman only proceeds once you hit return. In contrast, pacaur seems to proceed after a key was pressed.

I now realize that's the actual problem for me: I use a tiling WM, and sometimes I don't notice that the wrong window has focus and start typing. Usually that is not a problem, because all programs I use don't do anything, until I hit return. For pacaur such a mistake results in unintentionally answering a series of its prompts.

**Comment by rmarquis** [comment]
```
$ sudo pacman -S expac
warning: expac-8-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version  New Version  Net Change  Download Size

extra/expac  8-1          8-1            0.00 MiB       0.01 MiB

Total Download Size:   0.01 MiB
Total Installed Size:  0.03 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] x
```
`x` -> select `n` by default. Granted, that could be interpreted as "stop the whole operation", but imho the edit view isn't comparable to a final install prompt.

The "no hit return" is done on purpose. This is a design choice, as the main purpose of pacaur is to provide a "fast workflow" with minimum user interaction, and assume users know what they are doing (see #371).

**Comment by three-comrades** [comment]
Thanks for elaborating. I think it is meant as "stop the whole operation", but I understand you don't want that behavior for the edit view. I would argue that choosing the default that is displayed would make more sense, but I guess I'll just apply a local patch then :)

**Comment by rmarquis** [comment]
Yes. I usually don't release new versions very often, so hopefully it isn't much work to maintain a local patch. I'd also suggest to look into pacman hook to automate patching if needed.

**Comment by three-comrades** [comment]
In the unlikely case anybody else will care in the future: 

I decided to simply reprint the prompt. If anybody is interested, see [here](https://github.com/three-comrades/pacaur/commit/b4e5572df5a03847758c15750ed30af73810ffd6). I don't know much about bash programming, so no promises. So far, seems to work for me.
