### ISSUE TITLE
Proceed() doesn't wait for enter.

### ISSUE THREAD

**Issue by nikparo** [rmarquis/pacaur#699]
###### Version

```
pacaur 4.7.8
```

###### Description

I have found something I consider a usability issue - Unlike pacman, pacaur does not wait for enter on most `proceed()` prompts. Due to how PKGBUILD diffs work (sometimes prints and exits if the whole thing if it's short, sometimes scrolling and waiting for `q` to quit), I often press down out of habit, essentially skipping several `:: Proceed .... [Y/n]` prompts. This wouldn't be a problem if the prompt waited for `enter`.

As such, I would suggest changing:
```
read -r -n 1 answer
```
to
```
read -r answer
```
in `Proceed()`.

**Comment by rmarquis** [comment]
See #371.

**Comment by nikparo** [comment]
Ok. In case someone else finds this, I have managed to reduce this happening to me by setting git to always use a pager, even on short diffs:
```
git config --global core.pager 'less -+F'
```
... Maybe something similar could be added to pacaur? E.g.
```
diffcmd="git -c pager.diff='less -+F' log ..."
```

**Comment by rmarquis** [comment]
I don't want to force this behavior on everybody, but I can add a additional notes section in the man page if you send a PR.
