### ISSUE TITLE
replace cower search and json parsing code with jq

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#702]
Pacaur uses some internal crappy, ugly but working (and suprisingly robust) json parser code - mostly because I didn't want to use jshon and associated deps and that it has some shortcoming.

However, `jq` in `[community]` is a nice alternative with very little footprint. It is also becoming a somewhat standard in the AUR ecosystem (used by asp, aurutils, ...). 
Also, nowadays cower is used mainly for its powerful search feature, which could probably be replicated using `jq`. Consider replacing the current code with some jq calls.

- [ ] replace in-house json parsing code
- [ ] replicate cower search feature (maybe as an external program)

**Comment by ChuckDaniels87** [comment]
Moving this new feature from 5.0 milestone to 4.8?

**Comment by rmarquis** [comment]
That 4.8 milestone is quite theoretical - don't know if that will be done at all.
This said, this change is quite easy. It's only 4 lines of code to replace. It would add a new dep so I don't want to add it to the current 4.7.x branch, which is bugfix and minor improvements only.

**Comment by rmarquis** [comment]
Since `jq` provides regex support, we might think about using it to replicate the powerful search function of cower and get rid of cower as AUR dependency.

**Comment by ChuckDaniels87** [comment]
I think that is a nice idea, you kill two birds with one stone. I suppose some extra work on this issue too.

**Comment by rmarquis** [comment]
Yes. I don't have the time to work on this right now, but if `jq` is to be used in the future then it makes sense to make the full use of it.

**Comment by AladW** [comment]
Well, I'll be curious on how you guys implement it. I couldn't `jq` my way out of a paper bag but a nice person sent me patches. :smile:

**Comment by rmarquis** [comment]
I'm actually doing a 180 degree rurn here, and dropping this idea. See #708.
