### ISSUE TITLE
pacaur downloads same version

### ISSUE THREAD

**Issue by mustaqimM** [rmarquis/pacaur#703]
###### Version
```
pacaur 4.7.8
```

###### Description

pacaur downloads the same version specified in the PKGBUILD even though that is the version already installed. In the example, the `anbox` PKGBUILD specifies a [version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=anbox-image) but `pacaur` attempts to redownload it. I've seen it do this with a few non-git/aur packages where it needs to download a single file.

###### Output

```bash
pacaur -S anbox-image                                 
```

```bash
:: Package anbox-image not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...
:: anbox-image-2017.04.12-1 is up to date -- reinstalling

AUR Packages  (1)  Old Version   New Version 

aur/anbox-image    2017.04.12-1  2017.04.12-1               

:: Proceed with installation? [Y/n]
```

**Comment by rmarquis** [comment]
I don't see any bug... what did you expect?

**Comment by mustaqimM** [comment]
@rmarquis If the same version is found then it should re-install instead of re-downloading what's already in the cache.

**Comment by rmarquis** [comment]
True, but the downloaded file is not in the cache, or the cache path is not accessible for some reason. I just tried to install twice in a row and everything works fine:

```
$ pac -S anbox-image
:: Package anbox-image not found in repositories, trying AUR...
:: resolving dependencies...
:: looking for inter-conflicts...
:: anbox-image-2017.04.12-1 is up to date -- reinstalling

AUR Packages  (1)  Old Version   New Version 

aur/anbox-image    2017.04.12-1  2017.04.12-1       (cached)

:: Proceed with installation? [Y/n]
```

Check your cache and see if the file is present. Default path is `$HOME/.cache/pacaur`, but the cache path might differ, depending if you modified the `SRCDEST` in makepkg.conf.
