### ISSUE TITLE
Dependency tree not shown when dependency is unresolved

### ISSUE THREAD

**Issue by kitling** [rmarquis/pacaur#707]
###### Version

`pacaur -v`

```
pacaur 4.7.8
```

###### Description

If a package upgrade is ignored due to it being unresolved, then detailed dependency tree information is not printed. 

It should be noted that I am having this problem because I am (currently) running a systemdless system (specifically using obarun), but I'm sure that this could come up in other situations as well. I may change this soonish. I have not looked through the list of dependencies to see what is causing this yet, but I'm not looking forward to it. EDIT: while it hasn't finished yet, makepkg -sri does not appear to be having any issues with unresolved packages. ¯\_(ツ)_/¯

Related to #676, #173?

###### Output

`pacaur -Sa ffmpeg-nvenc`

```
:: resolving dependencies...
:: libsystemd: ignoring package upgrade
:: Unresolved dependency 'libsystemd'
```

###### Debug output

`bash -x pacaur -Sa ffmpeg-nvenc`

1.5k line log moved to external paste service
https://paste.pound-python.org/show/VjZqcmzwoOQtUgSTNWhL/

**Comment by rmarquis** [comment]
Pacaur is an Arch Linux AUR helper, it's untested and unsupported on any other derivatives. I'll not spend my free time debugging issues that don't exist on Arch Linux (feel free to report valid bugs though, or to mandate me for support).

**Comment by kitling** [comment]
What you say is fair, so I guess I should try and reproduce this on stock arch at some point. :P
