### ISSUE TITLE
deprecate AUR specific short command options

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#712]
Pacaur provides two sets of command options, one for AUR only specific actions and another one that extends regular pacman options. While this allows quite a lot of flexibility in the way users can use pacaur, this has however the downside of being quite complex to maintain, not to mention being completely ugly.

Also, the usage of two sets of options that somewhat overlap isn't straightforward to understand, as some options haven't the same meaning in one set or another (f.e. `-y`). To this day, I still see users mixing both sets of options and not understanding how to use pacaur without actually reading the man page.

For theses reasons, I'd like to deprecate the AUR specific short command options, and use only "long" options, similarly to what auracle (cower-ng, see #708) does. F.e, instead of using`-s` and `--search`, simply implement `search` as the AUR only option. The pacman extension set should stay unchanged, still allowing the short `-s` and long `--search` options, to be used with `-S` or `--sync`.

Implementing a temporary "translator" of the old AUR-only options to the new one with a warning message might be needed here. 

Also, simplifiying the getops structure would help. See this [reference](http://wiki.bash-hackers.org/howto/getopts_tutorial) and [blog post](https://sookocheff.com/post/bash/parsing-bash-script-arguments-with-shopts/) to handle nested getops in a much readable form.

**Comment by rmarquis** [comment]
For the sake of consistency and code simplification, each pacman command that is extended to the AUR should have a direct AUR specific command equivalent:

```
-S  -> sync
-Ss -> search
-Si -> info
-Sw -> downloadonly
-Su -> sysupgrade
-Sc -> clean
-Qu -> check
```

* `makepkg` should be renamed to `downloadonly` (as per pacman convention)
* `update` should be renamed to `sysupgrade` (as per pacman convention)
* `clean` should be added (#715)
* `download` should be removed. There isn't a pacman equivalent as ABS integration isn't done in pacaur for a variety of reason, it can be done better done directly by `cower -d` / `auracle download`, and could be readded once pacman eventually integrates ABS.

**Comment by abouvier** [comment]
Why don't you use the `getopt` command instead of the `getopts` built-in? It is much more powerful and supports native long option names. This command is provided by `util-linux` which is in the `base` and `base-devel` group. No more `$OPTARG` ugly hacks needed! See `/usr/share/doc/util-linux/getopt/getopt-parse.bash`.

**Comment by rmarquis** [comment]
There are a number of reasons that made me choose `getopts` over `getopt` in the past: built-in, more robust with option that requires an argument - though I don't know if that still the case, but the bottom line is that I hate both. I am planning to use the `parseopts` library provided by makepkg instead.

**Comment by rmarquis** [comment]
Partially done in f67d43bfbda08bdd9f6ef86729f57a4a71580f68, bb0222622e8f13702c35fc482018ebc316ef789b, 9291462bef4467c7a992c076c617e73e06b5d061 and 60add4bb62e38b6c713e6fd40094a925a32f25e3.

Still missing:
* `clean` and `cleanall` implementation (#715)
* selective target implementation (still undecided what do do here)

**Comment by blueyed** [comment]
As stated in https://github.com/rmarquis/pacaur/pull/744#discussion_r131551592 it seems odd that `downloadonly` builds a package?!

> -Sw -> downloadonly

makes sense.

> makepkg should be renamed to downloadonly (as per pacman convention)

This is what I don't get probably.

**Comment by rmarquis** [comment]
The logic behind this choice is to have similarly names flags as the repo operation. Since `-Sw` is `downloadonly`, I choose it as the `-Swa` equivalent too, but this might not be a wise decision. With retrospect, the long pacman options might not be known very well if at all, so this won't help in clearing any confusion.

While `sync`, `info`, `search` and `clean` are unambiguous, `downloadonly`, `sysupgrade` and `upgrades` might very well be. Here is another proposal:

```
-Sw -> buildonly
-Su -> upgrade
-Qu -> check
```

`downloadonly` could be kept for downloading the PKGBUILD only (equivalent to current `-d` short option).

**Comment by rmarquis** [comment]
Adjusted in 668393e762c07db0a52920c02bca3708a6416108.

**Comment by rmarquis** [comment]
Download only / clone only is better left to cower/auracle or any other command line shortcut.
