### ISSUE TITLE
clean work directory before running makepkg

### ISSUE THREAD

**Issue by rmarquis** [rmarquis/pacaur#714]
Some projects fail when the directory isn't cleared beforehand (such as meson based projects, like `auracle`).

This is an issue with regular packages that are built in the same directory as the PKGBUILD (without BUILDDIR defined), but also with VCS packages. Running `-C` flag of makepkg should be enough, but let's keep in mind that VCS packages source shouldn't be removed entirely either. Special checks might be necessary here (?).

**Comment by rmarquis** [comment]
Fixed in dd683eec6b43d41918dd05f0c3a772c7c34b074a.

**Comment by chetgurevitch** [comment]
In the case of packages supporting incremental builds the opposite is desirable, any chance this could be made configurable?
