### ISSUE TITLE
Memory leak using Docker?

### ISSUE THREAD

**Issue by chrissound** [rmarquis/pacaur#717]
Here is my Dockefile I'm using.
```
FROM greyltc/archlinux:latest
MAINTAINER Edward Hernandez

RUN pacman -q --noconfirm -Syyuu
RUN pacman -q --noconfirm -S  \
		base-devel    \
		curl          \
		expac         \
		git           \
		openssl       \
		yajl

RUN sed -i '/NOPASSWD/s/\#//' /etc/sudoers
RUN useradd -r -g wheel build

WORKDIR /build
RUN chown -R build /build

WORKDIR /home/build
RUN chown -R build /home/build
USER build
RUN gpg --recv-keys --keyserver hkp://pgp.mit.edu 1EB2638FF56C0C53

ENV PATH="/usr/bin/core_perl:${PATH}"
WORKDIR /build
RUN git clone https://aur.archlinux.org/cower.git
WORKDIR /build/cower
RUN makepkg --noconfirm -i

WORKDIR /build
RUN git clone https://aur.archlinux.org/pacaur.git
WORKDIR /build/pacaur
RUN makepkg --noconfirm -i

USER root

ENV AURDEST /build
ENV PACMAN pacaur

WORKDIR /

RUN pacman -S --noconfirm nano
ENV EDITOR "nano"

RUN paccache -r -k0
RUN pacaur -Scc
RUN rm -rf /usr/share/man/*
RUN rm -rf /tmp/*
RUN rm -rf /var/tmp/*
```

Within this docker container, if I do a `pacaur -S neovim` it just seems to start a memory leak and a recursive process call , output from top:
![2017-07-04-19 13 45](https://user-images.githubusercontent.com/1499652/27839976-427660dc-60ed-11e7-9558-fb11ef1716b3.jpeg)

Any ideas how I can debug this?

**Comment by chrissound** [comment]
`pacaur --help`, `pacaur -s neovim` works fine.

**Comment by chrissound** [comment]
If I do a strace on the host I see:
` sudo strace -p 19256
strace: Process 19256 attached
wait4(-1, `

**Comment by rmarquis** [comment]
Does neovim builds with makepkg? Pacaur builds using `makepkg -o && makepkg -es`.

In the past, I got some issue with neovim, with the way the installation was done triggering an upstream bug (see #197, #325). This particular issue has been solved both in the pacaur install code and upstream neovim code, but I wouldn't exclude another neovim issue here.

**Comment by chrissound** [comment]
This occurs with `pacaur -S nano` and `pacaur -S linux` as well.

**Comment by rmarquis** [comment]
Again, does this happen with makepkg only?
Also, might be sudo related. I'd suggest to turn off the `sudoloop` and see if the issue still happen.

**Comment by chrissound** [comment]
Sorry, how could I verify that (makepkg)?

How do I turn off sudoloop?

**Comment by chrissound** [comment]
Setting `sudoloop=false` in /etc/xdg/pacaur/config results in the same behaviour.

**Comment by rmarquis** [comment]
By running makepkg manually: `makepkg -o && makepkg -es`.

**Comment by chrissound** [comment]
```
[build@66a32e4f4154 /]$ makepkg -o && makepkg -es
==> ERROR: You do not have write permission to create packages in /.
    Aborting...

==> ERROR: An unknown error has occurred. Exiting...
```
```
[root@66a32e4f4154 /]# makepkg -o && makepkg -es
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.

==> ERROR: An unknown error has occurred. Exiting...
```
```
[build@66a32e4f4154 /]$ sudo makepkg -o && sudo makepkg -es
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.

==> ERROR: An unknown error has occurred. Exiting...
```

**Comment by rmarquis** [comment]
Oh, I see `neovim` is actually a community package, not an AUR package. Makepkg shouldn't be involved at all here. You can install it directly with pacman.

And yes, using makepkg as root isn't possible anymore (since a few years already). You'll need to run as a user. I really know how docker works, but this is out of scope of the usage intended for pacaur in any case.

**Comment by chrissound** [comment]
Well thanks for your help anyway.

I did try doing this in the user's directory:
```
makepkg -o && makepkg -es
==> ERROR: install file (neovim.install) does not exist or is not a regular file.

==> ERROR: An unknown error has occurred. Exiting...
```

**Comment by chrissound** [comment]
Okay so I downloaded the neovim.install directory as well and now get this in top:

![2017-07-05-17 18 05](https://user-images.githubusercontent.com/1499652/27874029-0077295a-61a6-11e7-9880-c67550d9efa3.jpeg)

**Comment by rmarquis** [comment]
All right, I understand the issue:

> ENV PACMAN pacaur

You're telling pacaur to use itself each time it needs to call pacman. Don't do that.

**Comment by chrissound** [comment]
Which does not make sense? The above happens with `makepkg -o && makepkg -es`. Why would pacaur be called... Oh just saw your message.

**Comment by chrissound** [comment]
Thank you! That has indeed fixed it.

**Comment by rmarquis** [comment]
yw.

**Comment by rmarquis** [comment]
I've added a sanity check in a5db31d99076b1eaa5e2eb6478cc3e3c25cf055e so pacaur will refuse to work when `PACMAN` is set to pacaur.
