### ISSUE TITLE
Integrate Arch Linux News feature request

### ISSUE THREAD

**Issue by drws** [rmarquis/pacaur#718]
This is a proposition to integrate [Arch Linux News](https://www.archlinux.org/news/) to pacaur. These announcements are an essential read before updating (Arch Wiki [also instructs](https://wiki.archlinux.org/index.php/General_recommendations#Package_management)) and while having updates so well integrated such as in the case of a modern Linux desktop system, it's unpractical to be necessary to use a browser or a RSS reader to correctly perform such a low level system operation as update. And it's a very forgettable thing.

I think these announcements should be more integrated into the system and pacaur could provide a way to achieve that. I suppose the feature would be activated by passing a flag and a quick hack I'm currently using parses the News site [RSS feed](https://www.archlinux.org/feeds/news/) and displays it in less before executing pacaur. From my point of view, something similar should suffice, maybe with pacaur also asking which ones to "clear" and not display next time, but nothing more complicated than that. Simple, but effective so that the user does not miss anything important.

This is also one of the main features of [Pacmatic](http://kmkeen.com/pacmatic/). Its other features to automate boring pre-update tasks are also very interesting.

**Comment by rmarquis** [comment]
I consider this feature out-of-scope, as third party extra tools can be easily chained to pacaur, provided they have support for alternative pacman binary. This is the case for powerpill: if you define the `$pacman_program` variable as 'pacaur', pacmatic will use it. This variables can be exported in your .bashrc or .zshrc (see powerpill man page).

I have even seen some people using pacmatic with pacaur, which itself is chained to powerpill which then calls pacman (`pacmatic > pacaur > powerpill > pacman`), though this is not something I've personally tried.

I'm however not sure if pacmatic will pass all argument to pacaur, but it does at least work for the important tasks (updating with `-Syu`).
