### ISSUE TITLE
Document $PACMAN

### ISSUE THREAD

**Issue by drws** [rmarquis/pacaur#719]
$PACMAN variable description is missing in the manpage and README or am I missing something?

**Comment by rmarquis** [comment]
As stated in the environement section of the man page, this is documented in makepkg(8). Since there is no special behaviour about it, there is no need to duplicate it.

**Comment by drws** [comment]
Isn't there variable pacmanBin and not PACMAN? I thought pacmanBin is meant to be set at build time and PACMAN at runtime.

I'd also say that there is no need to detail it, but it is not even mentioned in the main help pages. Is it really that optimal solution to have variable descriptions scattered around like that? How do I access the description after package is installed if I don't have the source (since I consider that to be temporary files and mount the package download/build folder to /tmp)?

**Comment by rmarquis** [comment]
`pacmanbin` is an internal variable, it is not meant to be used directly.

Pacaur is built on the assumption that the user knows about pacman and makepkg. As such, there are a LOT of environment variables and commands that aren't directly documented but that "just work" as pacaur is a makepkg and pacman wrapper. Duplicating all the pacman and makepkg documentation doesn't make sense, but referring to that documentation in the man page does (and is indeed done).

What is missing is a check to prevent `$PACMAN` to be set to pacaur (see #717). That commit will be pushed in the repo soon.

> How do I access the description after package is installed if I don't have the source (since I consider that to be temporary files and mount the package download/build folder to /tmp)?

That's not the default behavior, and thus your problem. I frankly don't care that you don't want to read makepkg or pacman man page.

**Comment by drws** [comment]
I have read both pacman and pacaur manpages before and I agree on the default behavior part. What I've missed is makepkg's manpage. And what you've missed is that I only tried to help, even though wrong. No need for cockiness, although I like your style.
