### ISSUE TITLE
download source

### ISSUE THREAD

**Issue by vendforce** [rmarquis/pacaur#725]
###### Os 
Arch - Gnome Shell

###### Version
pacaur 4.7.10

###### Description 
pacaur -d switch not downloading some source applications

pacaur -d skype  ## downloads source files 
pacaur -d ettercap ##  does'nt download or find source yet pacaur -Ss ettercap displays file

many others don't download or find the source files why is this ?

**Comment by rmarquis** [comment]
`ettercap` isn't a valid AUR package, it is available in the [community] repo.
