### ISSUE TITLE
fix your help documentation !!! & the switches !!!!!!

### ISSUE THREAD

**Issue by vendforce** [rmarquis/pacaur#727]
#### Version
pacaur 4.7.10

#### Lack of Documentation in help options !!
why is the  'w' switch not listed in the help options?  and don't give me the whole, its in the arch wiki or listed somewhere else crap, all help options should be listed in the program  

#### Note my sarcasm is due to your fucking arrogant behaviour to have a message like below
don't put things like that in a issue post request , your not very professional !!! 

#### Arrogance like below should never be put in an issue request . your not linus torvalds !!
 AND FOR GODS SAKE, do not ask support questions on the bug tracker. I'm not here to fix your freaking INCOMPETENCE.
Or.give.me.MONEY. For paying support, see Paypal link in man page.

#### Find Dependence's
pacaur -Sw 0ad
resolving dependencies...
Packages (7) 0ad-data-a21-1  enet-1.3.13-1  gloox-1.0.20-1  miniupnpc-2.0.20170509-1  wxgtk-common-3.0.3.1-7  wxgtk2-3.0.3.1-7  0ad-a21-7

#### -dd switch not doing what it suggests in the help options !!!!! 
use -d Clone the target(s) build files. Pass this option twice to fetch uninstalled dependencies (done recursively). 

#### -dd switch not doing what it is mean't to 
pacaur -dd 0ad
:: resolving dependencies...
:: Retrieving package(s)...
:: no results found

#### Pacaur help options lacking completion !!! 
pacaur -h
usage:  pacaur <operation> [options] [target(s)] -- See also pacaur(8)
operations:
 pacman extension
   -S, -Ss, -Si, -Sw, -Su, -Sc, -Qu
                    extend pacman operations to the AUR
 AUR specific
   -s, --search     search AUR for matching strings
   -i, --info       view package information
   -d, --download   download target(s) -- pass twice to download AUR dependencies
   -m, --makepkg    download and make target(s)
   -y, --sync       download, make and install target(s)
   -u, --update     update AUR package(s)
   -k, --check      check for AUR update(s)
 general
   -v, --version    display version information
   -h, --help       display help information

options:
 pacman extension - can be used with the -S, -Ss, -Si, -Sw, -Su, -Sc operations
   -a, --aur        only search, build or install target(s) from the AUR
   -r, --repo       only search, build or install target(s) from the repositories
 general
   -e, --edit       edit target(s) PKGBUILD and view install script
   -q, --quiet      show less information for query and search
   --devel          consider AUR development packages upgrade
   --foreign        consider already installed foreign dependencies
   --ignore         ignore a package upgrade (can be used more than once)
   --needed         do not reinstall already up-to-date target(s)
   --noconfirm      do not prompt for any confirmation
   --noedit         do not prompt to edit files
   --rebuild        always rebuild package(s)
   --silent         silence output

**Comment by rmarquis** [comment]
Closing and bye bye. Suck it up.
