### ISSUE TITLE
Do not prompt for sudo access if no dependency needed to install

### ISSUE THREAD

**Issue by Brli** [rmarquis/pacaur#728]
###### Version

`pacaur -v`

```
pacaur 4.7.10
```

###### Description

Pacaur would ask for sudo rights after user checked and quit vim prompt about PKGBUILD and .install.

I know it is there because we need to install (make,check)depends for the targeting package.

However, if the dependency tree on the system is complied with the dependencies required, there is no needed to prompt for `pacman -S`.

Thus I suggest that it only prompt for sudo when really needed, not a regular step.

**Comment by rmarquis** [comment]
This is done intentionally. Sudo is prompted right away and not "when really needed" to avoid bothering the user after some building time. This is the fast workflow concept: processing all the prompts at once, then building in the background without any required user interaction.

This said, this concept probably should be clarified in the man page.
