### ISSUE TITLE
Remove fails on multiple files -Rs

### ISSUE THREAD

**Issue by Gibbz** [rmarquis/pacaur#729]
###### Version

`pacaur -v`

pacaur 4.7.9

###### Description

first remove digikam and install pacui

Then run the following command:
pacaur -Rs --noconfirm digikam pacui

###### Output

error: target not found: digikam

and there is no output for pacui. Because the digikam reported an error, pacui also fails. I would expect the default behaviour to continue in the case of an error, so pacui should be removed. 

###### Debug output

`bash -x pacaur -Rs --noconfirm digikam pacui`

.....
+ sudo pacman -R -s --noconfirm digikam pacui
error: target not found: digikam
+ exit

###### Workaround

This is the workaround I am currently using, but it would be great if this was built in to pacaur itself as it takes considerable time to put this together for each script:

remove="digikam pacui"
removearray=($remove)
for p in "${removearray[@]}"
do
    echo "Removing: " ${p}
    pacaur -Rs --noconfirm ${p}
done

**Comment by rmarquis** [comment]
The current behavior is in-line with pacman behavior, so it is the expected bahavior and I have no willingness to change it.
The real question is why do you try to remove a package that is already removed...

A faster and shorter way to script it is to use expac, removing the need for a loop.
```
$ expac -Q %n digikam pacui
pacui
```

On a side note, old version are not supported - version 4.7.10 has been released a week ago.
