### ISSUE TITLE
"tsort: -: input contains a loop:"

### ISSUE THREAD

**Issue by gwpl** [rmarquis/pacaur#734]
Filling template below, just to capture potential issue. (Yes, I've read "important" section and do not count on support. Just hoping to help in development of pacaur as maybe will meet others with similar issues so we may come up with a general fix).

Filling template below:
###### Important

Read me first: [Bug reports](https://github.com/rmarquis/pacaur/wiki/Bug-reports)

AND FOR GODS SAKE, do not ask support questions on the bug tracker. I'm not here to fix your freaking INCOMPETENCE.
Or.give.me.MONEY. For paying support, see Paypal link in man page.

###### Version

`pacaur -v`

```
pacaur 4.7.8
```

###### Description

Enter description of issue here

###### Output

`pacaur  -S pdftk`

```
:: Package pdftk not found in repositories, trying AUR...                                                                                
:: resolving dependencies...                                                                                                             
tsort: -: input contains a loop:                                                                                                         
tsort: gcc-gcj-ecj                                                                                                                       
tsort: gcc63-gcj                                                                                                                         
tsort: gcc63                                                                                                                             
tsort: -: input contains a loop:                                                                                                         
tsort: gcc-gcj-ecj                                                                                                                       
tsort: gcc63-gcj                                                                                                                         
:: dependency cycle detected 
```

###### Debug output

`(bash -x pacaur -S pdftk 2>&1) > pacaur.deb.txt`

Attaching pacaur.deb.txt:
[pacaur.deb.txt](https://github.com/rmarquis/pacaur/files/1171381/pacaur.deb.txt)

**Comment by rmarquis** [comment]
This is actually not a bug, but simply means a dependency cycle has been detected in the dependency chain, and that pacaur is unable to further proceed without manual intervention and bails out.

This is either due to an error in the PKGBUILDs, or in some case one of the dependency requires to be bootstrapped so it can be compiled without its dependency. Please check with the maintainer.
