### ISSUE TITLE
Add an option to ignore architecture

### ISSUE THREAD

**Issue by xogium** [rmarquis/pacaur#736]
###### Version

`pacaur -v`
pacaur 4.7.10

###### Description

It should possible to ignore the architecture array in the pkgbild -- as makepkg can do with the -A option for example. This is needed when you want to upgrade/install any aur package and you are running aarch64, as most of them don't have aarch64 in the arch array. It is a LOT frustrating to have to use pacaur -Se every time and edit the ton of dependencies some packages need (liquidsoap-git) being one). I have to do this every time I want to upgrade from aur as well.

###### Output

`pacaur -S liquidsoap-git` -- pacaur -m and pacaur -Syu will also cause that.
:: Checking ocaml-result integrity...

==> ERROR: ocaml-result is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-topkg integrity...
==> ERROR: ocaml-topkg is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-lablgl integrity...
==> ERROR: ocaml-lablgl is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-easy-format integrity...
==> ERROR: ocaml-easy-format is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-biniou integrity...
==> ERROR: ocaml-biniou is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking cppo integrity...
==> ERROR: cppo is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking perl-xml-dom integrity...
==> ERROR: perl-xml-dom is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-yojson integrity...
==> ERROR: ocaml-yojson is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-xmlm integrity...
==> ERROR: ocaml-xmlm is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-pcre integrity...
==> ERROR: ocaml-pcre is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-ocamlsdl integrity...
==> ERROR: ocaml-ocamlsdl is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-gd4o integrity...
==> ERROR: ocaml-gd4o is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking ocaml-camomile integrity...
==> ERROR: ocaml-camomile is not available for the 'aarch64' architecture.

==> ERROR: An unknown error has occurred. Exiting...
:: Checking liquidsoap-git integrity...
==> ERROR: liquidsoap-git is not available for the 'aarch64' architecture.

It would be really nice to be able to force the build no matter the architecture, and also to get the equivalent of makepkg -sri (ie: download pkgbuild, install build deps, build package, remove build deps, install newly compiled package). Currently all I found was pacaur -S which install build deps, build packages, install packages but leaves a mess of build deps behind, and pacaur -m which build package, remove build deps but doesn't install package or any of its runtime deps -- from aur.

**Comment by rmarquis** [comment]
See #610 and #692.
