### ISSUE TITLE
Request: preserve the scope of variables declared in prepare() to match makepkg

### ISSUE THREAD

**Issue by dbermond** [rmarquis/pacaur#751]
###### Version
```
$ pacaur -v
pacaur 4.7.10
```

###### Description

At the current version, `makepkg` preserves the (non-local) variables that are declared in prepare() function. In this manner, you can declare global variables in prepare() and reuse them in pkgver() and build().

But it seems that `pacaur` destroys the (non-local) variables that are declared in prepare(). As a result, packages that uses this benefit, like [mupen64plus-git](https://aur.archlinux.org/packages/mupen64plus-git/) will fail to build with `pacaur`, but will build fine with `makepkg`. In this way, `pacaur` seems to have an unmatched behavior compared to `makepkg`.

There is a user comment in the mentioned package page reporting a build issue with `pacaur`.

###### Output
```
$ pacaur -S mupen64plus-git
...
:: Installing mupen64plus-git package(s)...
:: mupen64plus-git package(s) failed to install.
:: ensure package version does not mismatch between .SRCINFO and PKGBUILD
:: ensure package name has a VCS suffix if this is a devel package
```

**Comment by rmarquis** [comment]
Except makepkg doesn't preserve non local variables. See #687 for details.
