### ISSUE TITLE
Error when building chromium-dev

### ISSUE THREAD

**Issue by farnoy** [rmarquis/pacaur#760]
###### Version

`pacaur -v`

```
pacaur 4.7.10
```

###### Description

Build of chromium-dev fails because of some exports. See the discussion between nullie and sl1pkn07 here https://aur.archlinux.org/packages/chromium-dev

Is pacaur supposed to affect package builds? I would expect it to behave same as makepkg plus some goodies around it. In this case it looks like it's doing something different than makepkg alone.

**Comment by rmarquis** [comment]
Exporting a variable in `prepare()` isn't supported by `makepkg -o && makepkg -es`. See #687.
