### ISSUE TITLE
Allow replacement of sudo with alternatives

### ISSUE THREAD

**Issue by that1communist** [rmarquis/pacaur#765]
I prefer https://github.com/odedlaz/suex to sudo, and would like it if there was a config option to ask it to call suex rather than sudo.

Thank you for all the hardwork, if there's already a way to do this I apologize.

**Comment by rmarquis** [comment]
I don't have time nor willingness to implement and support different tools because of "user preference". Please fork, or contact me with an offer for paying support.

**Comment by that1communist** [comment]
Cool, was only wondering if it was easy.
