### ISSUE TITLE
Pressing Ctrl+C right before it is asked to view the pkgbuild prevents the pkgbuild to be viewed or modified anymore

### ISSUE THREAD

**Issue by francescosgherzi** [rmarquis/pacaur#773]
###### Version

`pacaur -v`

```
pacaur 4.7.10
```

###### Description

If, when asked to view the pkgbuild, Ctrl+C is pressed, the next time it tries to install the package, pacaur  does not ask you anymore to view the pkgbuild.

###### Output

![2017-11-10-085624_1920x1080_scrot](https://user-images.githubusercontent.com/32344127/32648372-c0e5a424-c5f5-11e7-9c5f-cbc6088040c5.png)

**Comment by rmarquis** [comment]
Yes, because it detects the diff only by default. You can either force the view with the -e flag, or change the setting in the config file.
