### ISSUE TITLE
--force is not forwarded for AUR packages

### ISSUE THREAD

**Issue by Optiligence** [rmarquis/pacaur#776]
###### Version

`pacaur -v`

```
pacaur 4.7.10
```

###### Description

The `--force` option doesn’t have any effect. 

using `sudo pacman -U --force …` works as expected

###### Debug output

Just for testing i used one of my packages (i initially had this problem with streamlink-twitch-gui but that shouldn’t really matter): 

`sudo touch /usr/share/doc/qt/CMake-3.9.6.qch`
`pacaur -S cmake-doc-qch --force`

[pacaur-no-force.txt](https://github.com/rmarquis/pacaur/files/1488480/pacaur-no-force.txt)

**Comment by rmarquis** [comment]
Seems there is an issue when the package is already in the cache. Thanks for the report.

**Comment by rmarquis** [comment]
This issue was introduced in commit a8283551d700ef490bcb394ba7a8fec13225ea46. See #706.

**Comment by rmarquis** [comment]
Fixed in ffcdb3735ce65701ee9ba7dcbb5dc15d6491ec52.
