### ISSUE TITLE
should default pacmanbin to /usr/bin/pacman if pacmanbin is not a valid executable

### ISSUE THREAD

**Issue by Avinash-Bhat** [rmarquis/pacaur#778]
###### Version

`pacaur -v`

```
pacaur 4.7.10
```

###### Description
There shoud be a default fallback for pacmanbin if the pacman bin is not a valid executable

in $HOME/.config/pacaur/config
```
...
pacmanbin=/usr/bin/unknown-exec
```

###### Output

`pacaur -Sy`

```
...
/usr/bin/unknown-exec is not a valid command
```

---
a simple `test -x $pacman` should suffice for this, and then the message can be print that hte config is wrong.

---

when this happens for my usecase:

I have a bootstrap script which automatically installs pacaur, and syncs the config, which by-default uses the powerpill as pacmanbin. The bootstrapping fails as installing powerpill is beyond the script's scope without using pacaur.

I can send a PR for this, but need to know if this will be an acceptable change.

**Comment by rmarquis** [comment]
No, this is out of scope. The `pacmanbin` variable isn't supposed to be changed beyond the `PACMAN` environment variable (you can, but that's a hack).

**Comment by Avinash-Bhat** [comment]
@rmarquis you are right, I removed the setting for `pacmanbin` and set the PACMAN env variable to get it working. I think this is much helpful.

Can there be a way to let others know that pacmanbin is not a valid way to set up pacman backend for pacaur? maybe an update to docs should be enough. This was mentioned in one of the old threads for release v3.3.0 (https://bbs.archlinux.org/viewtopic.php?pid=1216059#p1216059)

**Comment by rmarquis** [comment]
The current documentation is up to date. 

Referring to a ~5 year-old information in a forum thread shouldn't be done blindly when the project is often updated.

**Comment by Avinash-Bhat** [comment]
I understand that a ~5 year old document should not be used blindly, but
when the aforementioned thread is the first in the search results for
pacaur+and+powerpill, users woud generally take it and expect it to work
correctly (and it does -- until a level).  I still think this should be
mentioned in the readme and man page.

**Comment by rmarquis** [comment]
Official documentation takes priority over any Google search result. Not sure what I could add more than what is in the man page already.

**Comment by Avinash-Bhat** [comment]
> Not sure what I could add more than what is in the man page already.

I was talking about adding ways to configure the pacman backend. Also since the same is not there in the official document, the users will go to the google search result. This can cause issues like the ones I faced. So we should add new section on how to configure pacaur in the official document, so anyone who stumbles upon this issue needn't be reading the whole script to figure that the issue is with an unsupported configuration.
