### ISSUE TITLE
Question: Why deprecate AUR specific commands?

### ISSUE THREAD

**Issue by Nepoxx** [rmarquis/pacaur#779]
From the readme:

> Note: The AUR specific commands short options (-y, -s, -i, -d, -m, -u, -k) and their respective long options (--sync, --search, --info, --download, --makepkg, --update, --check) are now deprecated and will be removed in a future release.

Why? What's the "proper" workflow when searching a package then?

**Comment by rmarquis** [comment]
See #712.
